### PR TITLE
Remove the proposal of the single workload endpoint from KEP#168-2

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind cleanup
/kind api-change

#### What this PR does / why we need it:
The single workload endpoint is redundant, as we can achieve the same goals using LocalQueue endpoint. We'd like to narrow the scope of KEP#168-2 and leave it as a potential follow-up feature.

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
@PBundyra @mimowo If we don't implement the single workload endpoint, we need to implement similar logic in the kueue kubectl plugin, right?

1. Call `GET /apis/visibility.kueue.x-k8s.io/VERSION/namespaces/LQ_NAMESPACE/localqueues/LQ_NAME/pendingworkloads?offset=0&limit=1000`
2. Extract the dedicated pending workload from the result of step 1

I think it might be better to implement almost logic in the server side as much as possible.

**Comment by mimowo** [comment]
>  If we don't implement the single workload endpoint, we need to implement similar logic in the kueue kubectl plugin, right?

Correct 

> I think it might be better to implement almost logic in the server side as much as possible.

Indeed. The PR proposes to just decouple this part of work, so that it can be prioritized independently. So, the idea was, that it would be added when needed, for example for the kueuecli. However, I'm not sure decoupling is a good idea in this case. WDYT?

**Comment by alculquicondor** [comment]
I would just leave it in the same KEP, possibly highlighting that it's not implemented yet.

**Comment by alculquicondor** [comment]
Not a good-first-issue actually....

Ideally, we should have a single endpoint that covers both pending and admitted workloads. Not that easy.

**Comment by mimowo** [comment]
> Ideally, we should have a single endpoint that covers both pending and admitted workloads. Not that easy.

Hm, but I think it still makes sense to expose the endpoint as in the KEP, just for pending, so that it would return the positions. I think the positions don't  think we have well defined positions for admitted workload, so we would need to re-design the API, which is a separate KEP then, I think.

**Comment by alculquicondor** [comment]
IMO, looking at the "pending workloads" of a (Local/Cluster)Queue makes a lot of sense, and we should keep these endpoints long term.

For the case of workload, it might make sense to just have an endpoint for "workload", period. Although it's unclear which fields we would need for an admitted Workload that isn't already in the Workload status. My main worry is that a user does a GET for "pending workload X" and it gets 404, just because the workload was admitted.
All these implications need to be explored in a future KEP.

**Comment by mimowo** [comment]
> For the case of workload, it might make sense to just have an endpoint for "workload", period. Although it's unclear which fields we would need for an admitted Workload that isn't already in the Workload status. My main worry is that a user does a GET for "pending workload X" and it gets 404, just because the workload was admitted.
> All these implications need to be explored in a future KEP.

SGTM, in that case, we just close this PR, and eventually complete this KEP with the new endpoint. 

As for the worry about 404, indeed, we could mitigate this scenario by doing the `/workload` endpoint, but analogously we could get 404 just before the Job completed and the workload is deleted, but we can discuss the implications in the future KEP indeed.

**Comment by tenzen-y** [comment]
> My main worry is that a user does a GET for "pending workload X" and it gets 404, just because the workload was admitted.
> All these implications need to be explored in a future KEP.

I agree with this concern. We should have another KEP if we want to have the `workloads` endpoint.

**Pull request merged**
