### PR TITLE
[makefile] Use the cached MPI module to get its CRDs for integration tests

### LINKED ISSUE #801: Use the cached MPI module to get its CRDs for integration tests.
**What would you like to be cleaned**:
Use the cached MPI module to get its CRDs for integration tests.

ref: https://github.com/kubernetes-sigs/kueue/pull/667#discussion_r1202934583

**Why is this needed**:
Speed up integration tests, cleanup Makefile.

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Use the cached MPI module to get its CRDs for integration tests.
#### Which issue(s) this PR fixes:

Fixes #801 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Review by kerthcet — COMMENTED** [review]
/lgtm

**Pull request merged**
