### PR TITLE
[kueuectl] Move exec.LookPath("kubectl") to RunE function.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Move `exec.LookPath("kubectl")` to RunE function in kueuectl pass-through commands to return an error only on execute this commands.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by trasc — COMMENTED** [review]
/lgtm
/approve

**Review by mimowo — COMMENTED** [review]
/cherry-pick website
I synced with @mbobrovskyi that it does not impact the website directly, but it is useful to avoid conflicts, per comment: https://github.com/kubernetes-sigs/kueue/pull/3104#issuecomment-2367634161.
I think it is safe to cherry-pick in this case, and will save a manual cherry-pick.

**Pull request merged**
