### PR TITLE
Fix pod-group tas tests

### LINKED ISSUE #3695: Fleky Test: TopologyAwareScheduling for Pod group when Creating a Pod group
**What happened**:

Periodic Tests failed on "End To End TAS Suite: kindest/node:v1.31.1: [It] TopologyAwareScheduling for Pod group when Creating a Pod group Should place pods based on the ranks-ordering".

```shell
{Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:91 with:
Error matcher expects an error.  Got:
    <nil>: nil failed [FAILED] Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:91 with:
Error matcher expects an error.  Got:
    <nil>: nil
In [AfterEach] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/tas/pod_group_test.go:85 @ 12/01/24 16:48:43.849
}
```

**What you expected to happen**:

No errors.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-tas-e2e-main/1863261324973182976

**Anything else we need to know?**:

Screenshot 2024-12-02 at 15 55 06

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #3696: Fleky Test: TopologyAwareScheduling for MPIJob when Creating a MPIJob
**What happened**:

Periodic Tests failed on "End To End TAS Suite: kindest/node:v1.31.1: [It] TopologyAwareScheduling for MPIJob when Creating a MPIJob Should place pods based on the ranks-ordering".

```shell
{Expected success, but got an error:
    <*errors.StatusError | 0xc0002a99a0>: 
    resourceflavors.kueue.x-k8s.io "tas-flavor" already exists
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "resourceflavors.kueue.x-k8s.io \"tas-flavor\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "tas-flavor",
                Group: "kueue.x-k8s.io",
                Kind: "resourceflavors",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    } failed [FAILED] Expected success, but got an error:
    <*errors.StatusError | 0xc0002a99a0>: 
    resourceflavors.kueue.x-k8s.io "tas-flavor" already exists
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "resourceflavors.kueue.x-k8s.io \"tas-flavor\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "tas-flavor",
                Group: "kueue.x-k8s.io",
                Kind: "resourceflavors",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
In [BeforeEach] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/tas/mpijob_test.go:65 @ 12/01/24 16:48:43.896
```

**What you expected to happen**:

No errors.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-tas-e2e-main/1863261324973182976

**Anything else we need to know?**:

Screenshot 2024-12-02 at 15 55 06

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mykysha**
#### What type of PR is this?
/kind bug
/kind flake
/kind failing-test

#### What this PR does / why we need it:
Fix e2e pod-group TAS tests

#### Which issue(s) this PR fixes:

Fixes #3695
Fixes #3696 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/lgtm
Thanks!

**Comment by mimowo** [comment]
Awesome!
/approve

**Pull request merged**
