### PR TITLE
Add e2e test for JobSet fix on suspend

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind cleanup

#### What this PR does / why we need it:

WIP because for now this is just an e2e that documents the issue. We will be able to fix it once https://github.com/kubernetes-sigs/jobset/pull/625 is fixed at the JobSet side, and is bumped in Kueue.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by kannon92** [comment]
Testing https://github.com/kubernetes-sigs/kueue/pull/2865 with jobset update.

**Comment by kannon92** [comment]
@mimowo when you get a chance do you want to rebase this?

**Comment by mimowo** [comment]
Rebased, example failure before the rebase:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2700/pull-kueue-test-e2e-main-1-30/1830548852046827520 (they were failing consistently for all e2e runs)

**Pull request merged**
