### PR TITLE
[test/int] Wait for workload admission change in rayjob preemption test.

### LINKED ISSUE #1943: Flaky integration test for RayJob
**What happened**:

```
RayJob Controller Suite: [It] Job controller with preemption enabled Should preempt lower priority rayJobs when resource insufficient expand_less	20s
{Timed out after 5.001s.
Expected
    <bool>: true
to be false failed [FAILED] Timed out after 5.001s.
Expected
    <bool>: true
to be false
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/controller/jobs/rayjob/rayjob_controller_test.go:735 @ 04/03/24 17:48:18.402
}
```

**What you expected to happen**:

No flakiness

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1777/pull-kueue-test-integration-main/1775579633484304384

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

It is possible that somehow our new timeout (5s) is too aggressive and we might want to increase it back 10s.

But it's worth investigating if something else could be going on.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?
/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:
Wait for workload admission change in rayjob preemption integration  test.
#### Which issue(s) this PR fixes:

Maybe fixes #1943

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/lgtm
/approve
/hold

This looks good to me, and I think those checks had a high flakiness potential.

However, I'm not convinced that it would solve the flakiness that we saw, because the check that failed is effectively unchanged.

**Comment by alculquicondor** [comment]
passed 3/5
/test pull-kueue-test-integration-main

**Comment by trasc** [comment]
passed 4/5
/test pull-kueue-test-integration-main

**Comment by trasc** [comment]
>However, I'm not convinced that it would solve the flakiness that we saw, because the check that failed is effectively unchanged

The change, indirectly, doubles the time we wait for the job to be unsuspended.

**Comment by alculquicondor** [comment]
/hold cancel

Let's keep the issue open and we can let the bot close it if we don't see the report again.

**Pull request merged**
