### PR TITLE
Prepare release-0.7 branch

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind documentation

#### Which issue(s) this PR fixes:

Part of #2305

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/hold

I still didn't create the release-0.7 branch. Once I do, I'll change the target for this PR.

**Review by tenzen-y — COMMENTED** [review]
Thank you for this update.
Once you create a release-0.7 branch, feel free to merge this PR.
/lgtm

**Pull request merged**
