### PR TITLE
[e2e] Fix visibility tests.

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

[e2e] Fix visibility tests.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
Please update also PR description with a link to the dashboard showing the tests failing, and preference the issue with e2e tests PR.

**Review by tenzen-y — COMMENTED** [review]
/approve

**Comment by mimowo** [comment]
For reference the visibility tests are now failing consistently. https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-e2e-main-1-29&width=20

However this is covered by another bug which is being worked on here https://github.com/kubernetes-sigs/kueue/pull/1831, that the failing tests are covered by 0 exit code returned.

**Comment by tenzen-y** [comment]
> For reference the visibility tests are now failing consistently. https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-e2e-main-1-29&width=20
> 
> However this is covered by another bug which is being worked on here #1831, that the failing tests are covered by 0 exit code returned.

Good summarize!

**Comment by mimowo** [comment]
Also for reference the regression was introduced in https://github.com/kubernetes-sigs/kueue/pull/1695. FYI @astefanutti

**Comment by astefanutti** [comment]
> Also for reference the regression was introduced in #1695. FYI @astefanutti

Ah, thanks for the heads-up. I had probably tested it without the visibility API enabled and trusted CI. Glad to see you found #1830.

**Pull request merged**
