### PR TITLE
Bump mpi-operator to v0.4.0

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Currently, we use an untagged version (`master` branch) for the mpi-operator.
However, we should use the tagged version (released version).

So I manually upgraded the mpi-operator version to v0.4.0 since we should upgrade it before releasing v0.3.0.

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by kerthcet** [comment]
For what reason, can you add to the description?

**Comment by tenzen-y** [comment]
> For what reason, can you add to the description?

Currently, we use an untagged version. So I think we should use the tagged version.

**Comment by tenzen-y** [comment]
Updated the description.

**Comment by alculquicondor** [comment]
/lgtm
/approve
:partying_face:

**Pull request merged**
