### PR TITLE
Fix CmpNoOrder in case of duplicated items

### LINKED ISSUE #1143: Function ```CmpNoOrder``` in ```pkg/util/slices``` fails for a few edge cases
**What happened**: Given slices A[1,1,2], and B[1,2,2] or  A[1,2] B[1,1] function ```CmpNoOrder``` returns wrong output - as if those slices were equal.

**What you expected to happen**: The function should return ```false``` as those slices differ.

**How to reproduce it (as minimally and precisely as possible)**: Call the function with mentioned arguments.

**Anything else we need to know?**: None

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind bug
/kind failing-test

#### What this PR does / why we need it:
Bug fix ```CmpNoOrder``` from ```pkg/utils/slices``` package. Added unit tests, some of them failed on the previous implementation.

#### Which issue(s) this PR fixes:
Fixes #1143

#### Does this PR introduce a user-facing change?
```release-note NONE

```

### CODE REVIEW

**Comment by mimowo** [comment]
/lgtm
/assign @alculquicondor 
I would also retitle to something more telling, such as "Fix CmpNoOrder in case of duplicated items'

**Comment by alculquicondor** [comment]
/retitle Fix CmpNoOrder in case of duplicated items
/approve

**Pull request merged**
