### PR TITLE
Fix shellcheck not working

### LINKED ISSUE #1795: Address all the disabled warnings given by shell check
**What would you like to be cleaned**:
In https://github.com/kubernetes-sigs/kueue/pull/1552, We added shellcheck to the repository. Currently, we are ignoring alot of shellcheck warnings.

```shell
# Currently disabled these errors will take care of them later
DISABLED_ERRORS="SC2002,SC3028,SC3054,SC3014,SC3040,SC3046,SC3030,SC3010,SC3037,SC3045,SC3006,SC3018,SC3016,SC3011,SC3044,SC3043,SC3060,SC3024"
```

This issue tracks the progress we make on addressing all the disabled errors/warnings given by shellcheck. See https://github.com/kubernetes-sigs/kueue/pull/1552 for more information.
 
**Why is this needed**:
The goals of ShellCheck addressing all the warnings are:

- To point out and clarify typical beginner's syntax issues that cause a shell to give cryptic error messages.

- To point out and clarify typical intermediate level semantic problems that cause a shell to behave strangely and counter-intuitively.

- To point out subtle caveats, corner cases and pitfalls that may cause an advanced user's otherwise working script to fail under future circumstances.

### PR DESCRIPTION
**Pull request by Vandit1604**
#### What type of PR is this?
/kind fix

#### What this PR does / why we need it:
Disable ignoring warnings and error for shellcheck

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Vandit1604** [comment]
@tenzen-y Could you check if shellcheck is working fine for you now.

**Review by tenzen-y — COMMENTED** [review]
I confirmed that shellcheck works fine on my local after this PR is included.
Thank you!

/lgtm
/approve

**Comment by trasc** [comment]
@tenzen-y I think we can remove the hold form this PR.

**Comment by tenzen-y** [comment]
> @tenzen-y I think we can remove the hold form this PR.

Oops, I forgot to cancel the holding. Thanks!
/hold cancel

**Pull request merged**
