### PR TITLE
Regenerate a CRD for the worklods when upgrading k8s.io dependencies to v0.26.3

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
I regenerated a CRD for the workloads when upgrading k8s.io dependencies to v0.26.3.

#### Which issue(s) this PR fixes:

Fixes #647

### CODE REVIEW

**Comment by tenzen-y** [comment]
Same #511.

```shell
Webhook Suite: [It] Queue validating webhook when Updating a Queue Should allow the change of status
{Expected
    <int32>: 0
to equal
    <int32>: 3 failed [FAILED] Expected
    <int32>: 0
to equal
    <int32>: 3
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/integration/webhook/localqueue_test.go:44 @ 03/20/23 10:42:41.591
}
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/651/pull-kueue-test-integration-main/1637764333616238592

/retest

**Comment by alculquicondor** [comment]
/lgtm
/approve

Thanks!

**Comment by tenzen-y** [comment]
This PR is ready to merge.
/hold cancel

**Pull request merged**
