### PR TITLE
Graduate LendingLimit to Beta

### PR DESCRIPTION
**Pull request by macsko**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Graduate LendingLimit feature to beta and enable it by default.

Feature flag is now enabled by default also in the tests. Added new test cases to verify a cases when `LendingLimit` field is set without a feature flag enabled.

#### Does this PR introduce a user-facing change?

```release-note
Graduated LendingLimit to Beta and enabled by default.
```

### CODE REVIEW

**Comment by gabesaba** [comment]
/lgtm

Thanks for promoting this. Once we can remove the false branch in 0.10, the codebase will be easier to understand/read :)

**Review by alculquicondor — COMMENTED** [review]
/approve

FYI @kerthcet

**Comment by kerthcet** [comment]
Got that, thanks for the work @macsko

**Pull request merged**
