### PR TITLE
Fix the broken link in the doc site

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
I fixed the broken link in the doc site.

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by alculquicondor** [comment]
maybe we should rename the page back to `quotas`, to match the title https://kueue.sigs.k8s.io/docs/tasks/administer_cluster_resources/

**Comment by tenzen-y** [comment]
> maybe we should rename the page back to `quotas`, to match the title https://kueue.sigs.k8s.io/docs/tasks/administer_cluster_resources/

It makes sense.

**Comment by tenzen-y** [comment]
@alculquicondor Updated.

**Comment by alculquicondor** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
