### PR TITLE
Make LossLessDefaulter selective to only prevent dropping fields outside of schema

### LINKED ISSUE #3174: Make LossLessDefaulter selective to only prevent dropping fields outside of schema
**What would you like to be added**:

Investigate making the LossLessDefaulter in Kueue to only prevent dropping fields outside of schema. 
This is a follow up from the discussion: https://github.com/kubernetes-sigs/kueue/pull/3132#discussion_r1782255326

And follow up to the issue: https://github.com/kubernetes-sigs/kueue/issues/2878

**Why is this needed**:

* Long term we may want to remove some fields in Kueue webhooks, and it would be hard with the current LossLessDefaulter
* Making LossLessDefaulter selective could possibly let us promote it as an opt-in defaulter in controller-runtime, allowing for:
  - reduced maintenance cost by moving from Kueue to controller-runtime
  - allow sharing the solution with other projects so that they don't need to reinvent the wheel

**Completion requirements**:

Investigate if this is feasible. and what is the implementation complexity, prototype.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Make `LossLessDefaulter` selective to only prevent dropping fields outside of schema.  

#### Which issue(s) this PR fixes:

Fixes #3174

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
> so this is matching [kubernetes-sigs/controller-runtime#2982](https://github.com/kubernetes-sigs/controller-runtime/pull/2982), right?

Yes, I created a PR here to fix it in Kueue. After https://github.com/kubernetes-sigs/controller-runtime/pull/2982 is merged, we can remove it here.

**Comment by mimowo** [comment]
Yes, and we also did it to check all the tests we developed testing other solutions pass with this approach - to gain more confidence in it. 

Indeed, if the fix is merged for controller-runtime I think we don't need to merge it in kueue.

**Comment by alculquicondor** [comment]
That will take time to trickle. OTOH, the current solution works for all of our webhooks today.

**Comment by mbobrovskyi** [comment]
/hold 

Looks like https://github.com/kubernetes-sigs/controller-runtime/pull/2982 almost done.

**Comment by trasc** [comment]
> /hold
> 
> Looks like [kubernetes-sigs/controller-runtime#2982](https://github.com/kubernetes-sigs/controller-runtime/pull/2982) almost done.

Even if it gets merged, it will take some time for it be part of a release  and for kueue to use that release.

**Comment by mimowo** [comment]
I think we have time to wait for now, because the current solution works fine as long as the webhooks don't remove fields.
So I would suggest to close this PR for now. We can re-open if we have a pressing need to allow for removing fields by Kueue webhooks, but for now it seems we can wait.

I opened https://github.com/kubernetes-sigs/kueue/issues/3469 to track it.

**Pull request closed without merging**
