### PR TITLE
Updated workload Inadmissible message when LocalQueue does not exist

### PR DESCRIPTION
**Pull request by rbarberop**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Clarify the queue type that the Workload is Inadmissible to (LocalQueue)

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by alculquicondor** [comment]
/lgtm
/approve
/ok-to-test

Thanks!

**Review by tenzen-y — COMMENTED** [review]
Moreover, can you update the following tests?

https://github.com/kubernetes-sigs/kueue/blob/3268949a656a18b779c6d5369de8a1a92034cef4/test/integration/controller/core/workload_controller_test.go#L79

https://github.com/kubernetes-sigs/kueue/blob/3268949a656a18b779c6d5369de8a1a92034cef4/test/integration/controller/core/workload_controller_test.go#L95

**Review by rbarberop — COMMENTED** [review]
Fixed tests

**Review by rbarberop — COMMENTED** [review]
Fixed tests

**Comment by tenzen-y** [comment]
Great!
Can you squash?

**Comment by alculquicondor** [comment]
/label tide/merge-method-squash
:)

**Comment by tenzen-y** [comment]
> /label tide/merge-method-squash :)

It's useful!
/lgtm

**Pull request merged**
