### PR TITLE
Makefile: Use 'GO_CMD' instead of 'go'

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
I modified Makefile to use 'GO_CMD' instead of 'go'.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Comment by alculquicondor** [comment]
Uhm.... the rule doesn't seem to be working https://github.com/kubernetes-sigs/kueue/blob/main/OWNERS

**Comment by tenzen-y** [comment]
@alculquicondor Is this related?

> WARNING: The approve plugin https://github.com/kubernetes/test-infra/issues/7690. Until that is fixed, filters should only be used for the labels key (as shown in the above example).

https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#filters

**Comment by alculquicondor** [comment]
Yeah... that looks like it.

**Comment by tenzen-y** [comment]
> Yeah... that looks like it.

We need to fix The whole of OWNER... :(

**Pull request merged**
