### PR TITLE
Fix "Failed Pod can be replaced in group" e2e test.

### LINKED ISSUE #3147: [flaky]  End To End Suite: kindest/node:v1.29.4: [It] Pod groups when Single CQ Failed Pod can be replaced in group expand_less
**What happened**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/3145/pull-kueue-test-e2e-main-1-29/1839287537244311552

```
End To End Suite: kindest/node:v1.29.4: [It] Pod groups when Single CQ Failed Pod can be replaced in group expand_less	8s
{Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:258 with:
NotFoundError expects an error failed [FAILED] Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:258 with:
NotFoundError expects an error
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/pod_test.go:259 @ 09/26/24 13:05:20.779
}
```
**What you expected to happen**:

Run successfully. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug
/kind flake
/kind failing-test

#### What this PR does / why we need it:
Fix "Failed Pod can be replaced in group" e2e test.

#### Which issue(s) this PR fixes:

Fixes #3147

#### Special notes for your reviewer:
Sometimes the garbage collector takes more than 5 seconds to delete a finalized Pod. We don't need to wait for the Pod to be removed after it's been replaced; we only need to confirm that the finalizer has been removed.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-integration-main

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/3148/pull-kueue-test-integration-main/1839330236475379712 should be solved by https://github.com/kubernetes-sigs/kueue/pull/3145.

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-integration-main

Due to https://github.com/kubernetes-sigs/kueue/issues/3149.

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
Thanks!

**Pull request merged**
