### PR TITLE
When the leader election is enabled, set true in leaderElectionReleaseOnCancel

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
When the manager is terminated, the leader role replica should voluntarily steps down from its own leader role
so that backup role can take the leader role as soon as possible.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
> When the manager is terminated, the leader role replica should voluntarily steps down from its own leader role
so that backup role can take the leader role as soon as possible.

If we didn't do that it feels like a bug more than just cleanup. Do you know how much delay it was causing? Maybe we could consider this for cherry-picking. WDYT @tenzen-y ?

**Comment by tenzen-y** [comment]
So, I think that cherry-picking this to release-0.8 could bring production env more stability.

**Comment by tenzen-y** [comment]
/release-note-edit
```release-note
Fix a bug that could delay the election of a new leader in the Kueue with multiple replicas env.
```

**Pull request merged**
