### PR TITLE
Add patch permissions for flowcontrol

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Adds necessary patch permission for APF controller

#### Which issue(s) this PR fixes:

Follow up to #1468

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
@alculquicondor Have you seen additional errors separate from #1468?

**Comment by tenzen-y** [comment]
/test pull-kueue-test-integration-main
Due to #1484

**Comment by alculquicondor** [comment]
At least there are no more errors related to APF :)

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1487/pull-kueue-test-e2e-main-1-28/1736816548200321024/artifacts/run-test-e2e-1.28.0/kind-worker2/containers/kueue-controller-manager-55457bd957-t7fk2_kueue-system_manager-ca768b35eb598032cb1a6170eae9724ba956aaa26db58835346aef4aa612a172.log

**Comment by tenzen-y** [comment]
> https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1487/pull-kueue-test-e2e-main-1-28/1736816548200321024/artifacts/run-test-e2e-1.28.0/kind-worker2/containers/kueue-controller-manager-55457bd957-t7fk2_kueue-system_manager-ca768b35eb598032cb1a6170eae9724ba956aaa26db58835346aef4aa612a172.log

It's great to see :) Thanks!

**Comment by alculquicondor** [comment]
When the certs become ready, it doesn't take more than 5 seconds since the first kueue log line. So a greater timeout is unlikely to fix the issue.

I'm currently testing cert-controller 0.9 in an attempt to narrow down a culprit #1489

**Pull request merged**
