### PR TITLE
Bump github.com/ray-project/kuberay/ray-operator from 1.1.1 to 1.2.1.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Bump github.com/ray-project/kuberay/ray-operator from 1.1.1 to 1.2.1.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
/lgtm
/approve
/hold
Do you know and could summarize what was the issue with the original PR?

**Comment by mbobrovskyi** [comment]
> Do you know and could summarize what was the issue with the original PR?

Yes, sure. It happens due to conflict of versions. 

In original PR is using `github.com/prometheus/client_golang v1.19.1` and `github.com/prometheus/common v0.54.0`.
With this version I had an error:

```
could not import k8s.io/component-base/metrics/testutil (-: # k8s.io/component-base/metrics/testutil
vendor/k8s.io/component-base/metrics/testutil/metrics.go:73:59: undefined: expfmt.FmtText)
```

I have updated this dependencies to `github.com/prometheus/client_golang v1.20.2` and `github.com/prometheus/common v0.57.0` to fix it.

**Comment by mimowo** [comment]
Awesome, thanks!
/hold cancel

**Comment by tenzen-y** [comment]
Let's cherry-pick this PR so that users can use the latest KubeRay.

/cherry-pick release-0.8

**Comment by alculquicondor** [comment]
@mbobrovskyi can you prepare the cherry-pick?

**Comment by alculquicondor** [comment]
/release-note-edit

```release-note
Fix support for kube-ray 1.2.x
```

**Comment by andrewsykim** [comment]
thanks folks!

**Pull request merged**
