### PR TITLE
Fix scheduler getting stuck when there are admission failures

### LINKED ISSUE #158: Flaky integration test for the scheduler?
**What happened**:

The integration tests failed with a extraneous message in the logs:

```
ERROR	scheduler	Updating QueuedWorkload status	{"error": "resource name may not be empty"}
    sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).schedule
    	/home/prow/go/src/sigs.k8s.io/kueue/pkg/scheduler/scheduler.go:128
    k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
    	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:188
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
    	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:155
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil
    	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:156
    k8s.io/apimachinery/pkg/util/wait.JitterUntil
    	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:133
    k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
    	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:188
    k8s.io/apimachinery/pkg/util/wait.UntilWithContext
    	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:99
    sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).Start
    	/home/prow/go/src/sigs.k8s.io/kueue/pkg/scheduler/scheduler.go:66
    sigs.k8s.io/kueue/test/integration/scheduler.managerAndSchedulerSetup.func1
    	/home/prow/go/src/sigs.k8s.io/kueue/test/integration/scheduler/suite_test.go:87
```

Full error log: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/157/pull-kueue-test-integration-main/1508537482113716224

So somehow we got a QW without a name? The only way I could see this possibly happen is that we used a QW object without cloning it from the informer cache.

**What you expected to happen**:

No error

**How to reproduce it (as minimally and precisely as possible)**:

No idea. I will try to run the test multiple times.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): main
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:

When requeueing, we need to notify the condition.

Also fixed queue manager to keep the most up-to-date object in a Queue

#### Which issue(s) this PR fixes:

Fixes #158 

#### Special notes for your reviewer:

Used #161 to see that the scheduler issued a requeue, but there was no following scheduling attempts, suggesting that the scheduler was hanging waiting for kueues.

### CODE REVIEW

**Comment by alculquicondor** [comment]
oh well, it wasn't the only bug

**Comment by alculquicondor** [comment]
One more try:
/test pull-kueue-test-integration-main

**Comment by alculquicondor** [comment]
three:

/test pull-kueue-test-integration-main

**Comment by ArangoGutierrez** [comment]
Two:

/test pull-kueue-test-integration-main

**Review by ArangoGutierrez — APPROVED** [review]
Tested locally up to 20 times in a row
/lgtm

**Comment by ArangoGutierrez** [comment]
```bash
[eduardo@fedora-workstation kueue]$ for i in {1..10}; do KUBEBUILDER_ASSETS="/home/eduardo/.local/share/kubebuilder-envtest/k8s/1.23.3-linux-amd64" go test -count=1 ./test/integration/... ; done
ok      sigs.k8s.io/kueue/test/integration/controller/core      12.319s
ok      sigs.k8s.io/kueue/test/integration/controller/job       17.442s
?       sigs.k8s.io/kueue/test/integration/framework    [no test files]
ok      sigs.k8s.io/kueue/test/integration/scheduler    18.471s
ok      sigs.k8s.io/kueue/test/integration/controller/core      12.129s
ok      sigs.k8s.io/kueue/test/integration/controller/job       17.023s
?       sigs.k8s.io/kueue/test/integration/framework    [no test files]
ok      sigs.k8s.io/kueue/test/integration/scheduler    18.359s
ok      sigs.k8s.io/kueue/test/integration/controller/core      12.492s
ok      sigs.k8s.io/kueue/test/integration/controller/job       16.899s
?       sigs.k8s.io/kueue/test/integration/framework    [no test files]
ok      sigs.k8s.io/kueue/test/integration/scheduler    18.539s
ok      sigs.k8s.io/kueue/test/integration/controller/core      12.323s
ok      sigs.k8s.io/kueue/test/integration/controller/job       17.586s
?       sigs.k8s.io/kueue/test/integration/framework    [no test files]
ok      sigs.k8s.io/kueue/test/integration/scheduler    18.429s
ok      sigs.k8s.io/kueue/test/integration/controller/core      12.218s
ok      sigs.k8s.io/kueue/test/integration/controller/job       17.530s
?       sigs.k8s.io/kueue/test/integration/framework    [no test files]
ok      sigs.k8s.io/kueue/test/integration/scheduler    18.470s
ok      sigs.k8s.io/kueue/test/integration/controller/core      12.118s
ok      sigs.k8s.io/kueue/test/integration/controller/job       17.477s
?       sigs.k8s.io/kueue/test/integration/framework    [no test files]
ok      sigs.k8s.io/kueue/test/integration/scheduler    18.160s
ok      sigs.k8s.io/kueue/test/integration/controller/core      12.866s
ok      sigs.k8s.io/kueue/test/integration/controller/job       17.721s
?       sigs.k8s.io/kueue/test/integration/framework    [no test files]
ok      sigs.k8s.io/kueue/test/integration/scheduler    17.931s
ok      sigs.k8s.io/kueue/test/integration/controller/core      12.661s
ok      sigs.k8s.io/kueue/test/integration/controller/job       17.187s
?       sigs.k8s.io/kueue/test/integration/framework    [no test files]
ok      sigs.k8s.io/kueue/test/integration/scheduler    17.654s
ok      sigs.k8s.io/kueue/test/integration/controller/core      12.668s
ok      sigs.k8s.io/kueue/test/integration/controller/job       17.594s
?       sigs.k8s.io/kueue/test/integration/framework    [no test files]
ok      sigs.k8s.io/kueue/test/integration/scheduler    17.709s
ok      sigs.k8s.io/kueue/test/integration/controller/core      11.767s
ok      sigs.k8s.io/kueue/test/integration/controller/job       17.127s
?       sigs.k8s.io/kueue/test/integration/framework    [no test files]
ok      sigs.k8s.io/kueue/test/integration/scheduler    18.417s
```
Ran this multiple times locally ✅

**Comment by alculquicondor** [comment]
I was actually never able to reproduce locally

**Comment by ArangoGutierrez** [comment]
> 

with 
```bash
$ for i in {1..30}; do KUBEBUILDER_ASSETS="/home/eduardo/.local/share/kubebuilder-envtest/k8s/1.23.3-linux-amd64" go test -count=1 ./test/integration/... ; done
```
I was once, is one really hard to catch

**Review by ahg-g — COMMENTED** [review]
I don't see unit tests added to cover the fixes

**Review by alculquicondor — COMMENTED** [review]
I forgot that we already had async unit tests, which came very handy.

**Comment by ahg-g** [comment]
tide/merge-method-squash

/lgtm

**Pull request merged**
