### PR TITLE
Use nginx image on StatefulSet example.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Use nginx image on StatefulSet example.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
/cherry-pick website
Thanks!

**Comment by mimowo** [comment]
@mbobrovskyi do you know why "cherry-pick website" didn't work? 
I think we should cherry-pick it, can you prepare the PR manually?

**Comment by mbobrovskyi** [comment]
> @mbobrovskyi do you know why "cherry-pick website" didn't work? I think we should cherry-pick it, can you prepare the PR manually?

I'm not sure why, but the `/cherry-pick` tag doesn’t work if other tags are set on one comment.

**Pull request merged**
