### PR TITLE
[scalability] Collect extra information by default (metrics and logs)

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

To collect more data which will help us diagnose regressions, or failures. 

The logs can be helpful to understand why some certain workloads took long. 

The metrics can be helpful to understand how the dynamics changes over time during the test (e. g. first we accumulate pending workloads, then gradually process).

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

To eval the performance I checked 5 builds for `scrape 5s + logs`:
1787881265534341120
1788122597204955136
1788130374614781952
1788133679826997248
1788136923525550080
And 12 builds for `scrape 1s + logs + cpu profile`:
1787379334198071296
1783914210393067520
1787401375009738752
1787442170244894720
1787454666427076608
1787461693572386816
1787463978864087040
1787486099027791872
1787488286453796864
1787493923178942464
1787500095751589888
1787519348999458816
The `base` is taken from the `default_rangespec.yaml`

|  | base | scrape 5s + logs  | scrape 1s + logs + cpu profile  |
|---|---|---|---|
| wallTimeMs |  351116| 352075 (+0.27%) | 356409 (+1.5%)|
| maxrss | 445012 | 451190  (+1.4%)| 459065 (+3.1%)|
| avg. time to admit small | 6666 | 6609 (-) | 7402 (+11%) |
| avg. time to admit medium | 76768 | 77711 (+1.2%) | 78878 (+2.7%) |
| avg. time to admit large | 215468 | 217186 (+0.8%) | 218507 (+1.4%) |

Also, I feel that having good defaults allows us to cleanup the configuration for the root Makefile. If one needs custom options they can still be passed via `SCALABILITY_EXTRA_ARGS`, analogously to `GINKGO_ARGS`.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by trasc** [comment]
Let's only change the Makefile or the test-infra job definition.

**Comment by mimowo** [comment]
> Let's only change the Makefile or the test-infra job definition.

I prefer not to change the test-infra, because it would make the testing harder (the values would be in two places). 

I'm with changing the Makefile, but can you provide the reasoning? 

It seems reasonable to set the defaults down in main.go. Less code, and they still can be adjusted if needed by the env. var.

**Comment by trasc** [comment]
> > Let's only change the Makefile or the test-infra job definition.
> 
> I prefer not to change the test-infra, because it would make the testing harder (the values would be in two places), and duplication between the periodic and pull jobs, which we don't need.
> 
> I'm ok with changing the Makefile only, but can you provide the reasoning?
> 
> It seems reasonable to set the defaults down in main.go. Less code, and they still can be adjusted if needed by the env. var.

The changes will be a lot less. Additionally the default true boolean flags look strange to me. 

In the Makefile we can have something like : 

```make

ifndef NO_SCALABILITY_KUEUE_LOGS
SCALABILITY_EXTRA_ARGS +=  --withLogs=true --logToFile=true
endif

SCALABILITY_SCRAPE_INTERVAL ?= 5s
ifndef NO_SCALABILITY_SCRAPE
SCALABILITY_SCRAPE_ARGS +=  --metricsScrapeInterval=$(SCALABILITY_SCRAPE_INTERVAL)
endif

ifdef SCALABILITY_SCRAPE_URL
SCALABILITY_SCRAPE_ARGS +=  --metricsScrapeURL=$(SCALABILITY_SCRAPE_URL)
endif
```

**Comment by trasc** [comment]
> I'm not convinced this is simpler than as proposed in the first commit, but I'm also ok to follow the suggestion, pushed in the last commit. PTAL.

/lgtm

**Pull request merged**
