### PR TITLE
typo for reference

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
This fixes a typo in the documentation.
/kind documentation

#### What this PR does / why we need it:
Fixing a minor typo in the docs.  README.m should be named README.md
#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by kerthcet** [comment]
Hi @kannon92 you need to sign the CLA first.

**Comment by kannon92** [comment]
> Hi @kannon92 you need to sign the CLA first.

Hey! Thanks for that.  I signed after I committed but I think I gotta look more into this!

**Comment by kannon92** [comment]
Going to close and reopen to see if that fixes the CLA.

**Pull request closed without merging**
