### PR TITLE
Allow specifiying pod and container security context

### LINKED ISSUE #874: Chart misses settings for securitycontext
**What would you like to be added**:
The chart has a fixed securityContext for the manager, which only sets allowPrivilegeEscalation to false. There are several more hardening settings to apply, like running as a specific user and enforcing a readOnlyRootFilesystem.
**Why is this needed**:
It is best practice to harden pods as much as possible, especially when it comes to controllers
**Completion requirements**:
Support a `.controllerManager.manager.podSecurityContext` and `.controllerManager.manager.securityContext` field whose value is simply inserted into the pod spec. The default can stay the same as now but will be defined in the chart values instead of the template. This allows compatibility with any future additions as well.

### PR DESCRIPTION
**Pull request by bh-tt**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Allows the kueue manager to run in more restriced namespaces.
#### Which issue(s) this PR fixes:

Fixes #874

#### Does this PR introduce a user-facing change?

```release-note
Allow specifying the manager pod and container security context instead of hardcoded values
```

### CODE REVIEW

**Comment by bh-tt** [comment]
Do I need to sign that CLA to merge this tiny merge request? Yes I'm doing this during work hours as part of our effort to harden our kubernetes deployments, but I'd really rather not bother our legal department with this.

**Comment by alculquicondor** [comment]
> Do I need to sign that CLA to merge this tiny merge request? Yes I'm doing this during work hours as part of our effort to harden our kubernetes deployments, but I'd really rather not bother our legal department with this.

I'm sorry, but any change requires a signed CLA. The good thing is that once you signed this CLA, you can send PRs to any Linux Foundation project, including kubernetes.

**Comment by bh-tt** [comment]
Alright, let me forward it to our legal department then.

**Comment by bh-tt** [comment]
I dont see how a change to the chart (which is probably not used in the test?) causes a test failure, so just going to try a retest.

/retest

**Comment by alculquicondor** [comment]
It just looks like we have too many tests cases and we need to increase the timeout :)

**Comment by alculquicondor** [comment]
Opened #888

**Comment by bh-tt** [comment]
Alright the CLA check passes.

**Comment by tenzen-y** [comment]
> Alright the CLA check passes.

Thanks for your contribution!

**Pull request merged**
