### PR TITLE
Fix for JobWithSkip in case when job is not found

### LINKED ISSUE #1450: High churn cluster with pod only causing stuck queue and overcommitment
**What happened**:

Workloads are not deleted even though the pods are deleted, keeping a dangling finalizer and thus the queue gets stuck

**What you expected to happen**:

Work is processed correctly

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The queue shows > 1000 admitted workloads, even though only about 110 are allowed:

Bildschirmfoto 2023-12-13 um 19 44 45

The following shows that there are stucked workloads on the ClusterQueue "background" stuck since a few hours.
Bildschirmfoto 2023-12-13 um 19 59 04

workloads have a deletion timestamp and finalizer, which is hours old (pod does not exist anymore)
Bildschirmfoto 2023-12-13 um 20 18 36

looks like that is not finialized, even though the "JobFinished" condition is true on the workflow (example from a different stuck workload): 

Bildschirmfoto 2023-12-14 um 08 08 31

Deleting the finalizer, causes the admitted "workload" resources to get cleaned up. Restarting the controller didn't resolve the error.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.28.3-eks
- Kueue version (use `git describe --tags --dirty --always`): v0.5.1
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by achernevskii**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

* If pod is not found, it shouldn't be skipped, since there could be a dangling workload that should be finalized.

* Add an integration test for the case when pod is finalized and deleted before the workload finalizer is removed.

#### Which issue(s) this PR fixes:

Fixes #1450

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Fix a bug in the pod integration that unexpected error will occur when the pod isn't find
```

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Fix a bug in the pod integration that unexpected errors will occur when the pod isn't found
```

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Fix a bug in the pod integration where a Workload can be left with a finalizer when a pod is not found.
```

**Pull request merged**
