### PR TITLE
Add FAR AI as an adopter to kueue

### PR DESCRIPTION
**Pull request by rhaps0dy**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Add FAR AI as an adopter. I was asked to do so by @kerthcet 

Question: what kind of contact should we have in the contact column? Must it be a GitHub username?

### CODE REVIEW

**Comment by alculquicondor** [comment]
> Question: what kind of contact should we have in the contact column? Must it be a GitHub username?

Yes, preferably. But I would be ok leaving it empty.

**Comment by tenzen-y** [comment]
@rhaps0dy Can you sign the CLA?

**Comment by kerthcet** [comment]
> Must it be a GitHub username?

Yes, I think you can leave your github name there, thanks a lot @rhaps0dy  🎉

**Comment by rhaps0dy** [comment]
Thanks all! @tenzen-y I finally managed to sign the CLA. Let me know if there's something else I should do!

**Pull request merged**
