### PR TITLE
reference readme misspelling

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
There is a minor type in one of the README file suffix. 
#### Which issue(s) this PR fixes:

Fixes #
README.m should be README.md in docs/reference.

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
Good catch
/lgtm

**Comment by alculquicondor** [comment]
:see_no_evil:

**Pull request merged**
