### PR TITLE
Cleanup the TODO in the integration test

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Cleanup the left over TODO after it has been addressed in https://github.com/kubernetes-sigs/kueue/pull/2131

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Oops, great catch! Thanks!
/lgtm
/approve

**Comment by tenzen-y** [comment]
Let's cherry pick this PR as well 
/cherry-pick release-0.6

**Comment by mbobrovskyi** [comment]
@tenzen-y #2241 2241

**Pull request merged**
