### PR TITLE
Add Deployment e2e test.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Add Deployment e2e test.

#### Which issue(s) this PR fixes:

Prepare for #3528

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
> > @mbobrovskyi @mimowo
> > Is there any reason why we need to implement E2E for deployment integration? It seems that the Deployment E2E testings do not have any cases where we need to deploy the kube-controller-manager during testings.
> > Have you seen the situations where we should deploy the kube-contrller-manager to verify the behaviors? I'm wondering if we should remove such E2E testings. If we justify this E2E, we need to implement E2E testings for all integrations.
> 
> The deployment integration is very complex and differs from other jobs. I would keep it as is to ensure it works correctly. Also this is just prepare PR for more complex cases like this
> 
> https://github.com/kubernetes-sigs/kueue/blob/998d17cf826497f4a17c883f32ff6eceebce172f/test/e2e/singlecluster/deployment_test.go#L134
> 
> .

Yes, I know the Deployment integration mechanism. But, we typically add E2E testings only when the feature deeply depends on the Node behavior since the Node emulations are very tricky.

IIRC, the Deployment does not have Node depending feature, and there would be enough integration testings. 
Have you ever seen the Node-depending features for the Deployment?

**Comment by mimowo** [comment]
@tenzen-y The underlying mechanism for each of the integrations is different - for Deployment we use single pod integration, for STS we use pod groups, and for Jobs we use GenericJob reconciler. So, the e2e tests for Job aren't redundant and it makes sense to cover the new integrations with e2e tests rigorously. 

I think the main reason we have e2e tests for job isn't actually dependence on node, but just testing the interplay between the Job controller and the controllers in Kueue. The same goes for Deployments and StatefulSets - we want to check the interplay between the k8s controllers, and the controllers in Kueue.

**Comment by tenzen-y** [comment]
> I think the main reason we have e2e tests for job isn't actually dependence on node (i actually don't know about such test in Kueue), but just testing the interplay between the Job controller and the controllers in Kueue. The same goes for Deployments and StatefulSets - we want to check the interplay between their corresponding k8s controllers, and the controllers in Kueue. I believe this is also the reason we have e2e tests for the PodGroup integration - the overall complexity of the feature, and interplay between an external controller managing the group and Kueue.

So, does that mean that this E2E aims to verify the behavior couple of Kueue and kube-controller-manager?
Is it enough the integration testings? What is the primary reason that we added this E2E, but we did not add E2E for RayCluster?

**Pull request merged**
