### PR TITLE
[config] Add cohorts CRD in the kustomization

### LINKED ISSUE #2981: Flaky MultiKueue e2e Test
MultiKueue [AfterEach] when The connection to a worker cluster is unreliable Should update the cluster status to reflect the connection state

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2971/pull-kueue-test-multikueue-e2e-main/1831326376158826496

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
[config] Add cohorts CRD in the kustomization. (missed in #2693)

#### Which issue(s) this PR fixes:

Fixes #2981

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mimowo** [comment]
The change lgtm, but can you explain why this omission is causing MK the tests to flake? Would the single cluster tests also flake?

**Comment by alculquicondor** [comment]
cc @gabesaba

**Comment by trasc** [comment]
> The change lgtm, but can you explain why this omission is causing MK the tests to flake? Would the single cluster tests also flake?

Because the Cohorts CRDs are not installed, the controller runtime  periodically kills the controller manager.

```
2024-09-04T13:49:46.73520991Z stderr F 2024-09-04T13:49:46.735096309Z	ERROR	setup	kueue/main.go:195	Could not run manager	{"error": "failed to wait for cohort caches to sync: timed out waiting for cache to be synced for Kind *v1alpha1.Cohort"}
```

Intended this is not related to multikueue and is the cause for other farriers for the same PR.

**Comment by alculquicondor** [comment]
Thanks for the clarification
/approve

**Pull request merged**
