### PR TITLE
Website release 0.5

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

The website now points to the `website` branch. From now on, we can develop documentation for the latest changes in the `main` branch.
We will merge `main` into `website` at the time of release.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
@alculquicondor @trasc I can not see the following commits in this PR. Is this intended?

- https://github.com/kubernetes-sigs/kueue/commit/60e9111d710750bb9579ac975935dccd711aca7f
- https://github.com/kubernetes-sigs/kueue/commit/f978bb54163088ff3701b32117d7122d6e0d26ce
- https://github.com/kubernetes-sigs/kueue/commit/7e8d24d7f09e7df08b034ae87609f354a49a0757
- https://github.com/kubernetes-sigs/kueue/commit/63e7c7334c3732145c0696efa927eefdd1b68d55
- https://github.com/kubernetes-sigs/kueue/commit/c9191ba864cfcca4038d5d259e1add4f9dc2a27f

**Comment by alculquicondor** [comment]
oh, my fault. I think I forgot to pull from upstream before creating this PR.

**Comment by alculquicondor** [comment]
Opened #1117

**Pull request merged**
