### PR TITLE
Introduce the ClusterAutoscaler APIs module

### LINKED ISSUE #1345: Failed to perform "go list -modfile=./go.mod -m all"
**What happened**:
I could not perform `go list -modfile=./go.mod -m all` to get all dependencies list, and I faced the following errors:

```shell
$ go list -modfile=./go.mod -m all
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kube-scheduler@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kubectl@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/legacy-cloud-providers@v0.0.0: invalid version: unknown revision v0.0.0
```

**What you expected to happen**:
The command is successful.

**How to reproduce it (as minimally and precisely as possible)**:
We can reproduce with `go list -modfile=./go.mod -m all` on our local.

**Anything else we need to know?**:
I guess that the error was caused by cluster-autoscaler dependencies. Actually, once I remove the cluster-autoscaler dependencies from our `go.mod`, and then the above error went away.

Also, I found that we can avoid the above error once I specify the module versions in the following:

```diff
go 1.21

require (
...
	sigs.k8s.io/structured-merge-diff/v4 v4.4.1
)

+replace (
+	k8s.io/dynamic-resource-allocation => k8s.io/dynamic-resource-allocation v0.28.3
+	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.28.3
+	k8s.io/kubectl => k8s.io/kubectl v0.28.3
+	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.28.3
+)
...
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`): main branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
I replaced the `k8s.io/autoscaler/cluster-autoscaler` with the `k8s.io/autoscaler/cluster-autoscaler/apis` because https://github.com/kubernetes/autoscaler/pull/6315/ is finally merged.

#### Which issue(s) this PR fixes:

Fixes #1345

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by trasc** [comment]
https://github.com/kubernetes-sigs/kueue/blob/a751ffd7e902e61e56f24c499eeffb5b7ec5f7af/Makefile#L400-L404

needs an update

**Comment by tenzen-y** [comment]
> https://github.com/kubernetes-sigs/kueue/blob/a751ffd7e902e61e56f24c499eeffb5b7ec5f7af/Makefile#L400-L404
> 
> needs an update

Yes, that's right.
Also, we need to upgrade Golang version to v1.22 due to https://github.com/kubernetes/autoscaler/commit/eb5d875837a16cbb3a6b0eefb9fde41d9ecbcd85.

```
go: downloading k8s.io/autoscaler/cluster-autoscaler v0.0.0-20240320105552-09954b6741cb
go: k8s.io/autoscaler/cluster-autoscaler@v0.0.0-20240320105552-09954b6741cb requires go >= 1.22; switching to go1.22.1
go: downloading go1.22.1 (darwin/arm64)
go: downloading k8s.io/autoscaler/cluster-autoscaler v0.0.0-20240320105552-09954b6741cb
```

Or, putting https://github.com/kubernetes/autoscaler/tree/09954b6741cbb910971916c079f45f6e8878d192/cluster-autoscaler/config/crd to https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/apis/provisioningrequest would be better.

@alculquicondor @x13n WDYT?

**Comment by x13n** [comment]
Putting the CRD in CA apis module makes sense to me, it has to be in sync with the code there anyway.

**Comment by alculquicondor** [comment]
I'm also ok upgrading to golang 1.22

But all the APIs should be in the separate module

**Comment by tenzen-y** [comment]
@x13n @alculquicondor Thank you for responding.
I can take both approaches.
Let me try them.

**Comment by tenzen-y** [comment]
> @x13n @alculquicondor Thank you for responding. I can take both approaches. Let me try them.

Raised at https://github.com/kubernetes/autoscaler/pull/6651

**Comment by mwielgus** [comment]
https://github.com/kubernetes/autoscaler/pull/6651 is merged.

**Comment by tenzen-y** [comment]
> [kubernetes/autoscaler#6651](https://github.com/kubernetes/autoscaler/pull/6651) is merged.

Thank you!

**Comment by tenzen-y** [comment]
@alculquicondor This PR is ready for review.

**Review by alculquicondor — COMMENTED** [review]
Thank you so much @tenzen-y!!!!

This was a long effort that simplifies the maintainability of our deps greatly!

**Comment by tenzen-y** [comment]
> Thank you so much @tenzen-y!!!!
> 
> This was a long effort that simplifies the maintainability of our deps greatly!

I appreciate to collaboration with SIG-Autoscaling (@x13n and @mwielgus)!

@alculquicondor btw maybe you forgot to add `/lgtm`  label 🙃

**Comment by alculquicondor** [comment]
I did indeed forget :)

/lgtm

**Comment by tenzen-y** [comment]
@alculquicondor How about cherry-picking this into the release-0.6 branch?

**Comment by alculquicondor** [comment]
I'm not too sure about that. Why do you suggest it?

Also, I'm not sure what's the origin of the Job failure.

**Comment by tenzen-y** [comment]
> I'm not too sure about that. Why do you suggest it?

Cherry-picking would allow cluster-admins to avoid https://github.com/kubernetes-sigs/kueue/issues/1345 error.

**Comment by tenzen-y** [comment]
```
...
[FAILED] Test Report unavailable because a Ginkgo parallel process disappeared
    The aggregated report could not be fetched for a ReportAfterSuite node.  A
    Ginkgo parallel process disappeared before it could finish reporting.
...
This occurs if a parallel process exits before it reports its results to the
Ginkgo CLI.  The CLI will now print out all the stdout/stderr output it's
collected from the running processes.  However you may not see anything useful
in these logs because the individual test processes usually intercept output to
stdout/stderr in order to capture it in the spec reports.
```

Maybe this is the reason 🧐

**Comment by tenzen-y** [comment]
I guess that this error occurred by throttling CPU performance because integration tests often use larger CPUs.

https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&from=1711225845388&to=1711398645388&var-org=kubernetes-sigs&var-repo=kueue&var-job=pull-kueue-test-integration-main&var-build=All&refresh=30s&viewPanel=136

https://github.com/kubernetes/test-infra/blob/ce9cda237cf4b7518433dcd0ee90255e15c9c031/config/jobs/kubernetes-sigs/kueue/kueue-presubmits-main.yaml#L58-L59

**Comment by tenzen-y** [comment]
> https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&from=1711225845388&to=1711398645388&var-org=kubernetes-sigs&var-repo=kueue&var-job=pull-kueue-test-integration-main&var-build=All&refresh=30s&viewPanel=136

It seems that we need to set 8 Cores in the limit.
@alculquicondor WDYT?

**Comment by tenzen-y** [comment]
> One of my teammates is working in splitting the Multikueue E2E test into its own job. Let's decide if the limits are ok after that.

That makes sense. 
/test pull-kueue-test-integration-main

**Comment by tenzen-y** [comment]
> > I'm not too sure about that. Why do you suggest it?
> 
> Cherry-picking would allow cluster-admins to avoid #1345 error when cluster-admins implement a separate controller for the in-house job.
> 
> [MODIFIED COMMENT]

@alculquicondor How about this?

**Comment by tenzen-y** [comment]
> @alculquicondor: #1872 failed to apply on top of branch "release-0.6":
> 
> ```
> Applying: Introduce the ClusterAutoscaler APIs module
> Using index info to reconstruct a base tree...
> M	Makefile
> M	cmd/kueue/main.go
> M	go.mod
> M	go.sum
> M	pkg/controller/admissionchecks/provisioning/controller.go
> M	pkg/controller/admissionchecks/provisioning/controller_test.go
> M	pkg/controller/admissionchecks/provisioning/indexer_test.go
> M	test/integration/controller/admissionchecks/provisioning/provisioning_test.go
> Falling back to patching base and 3-way merge...
> Auto-merging test/integration/controller/admissionchecks/provisioning/provisioning_test.go
> Auto-merging pkg/controller/admissionchecks/provisioning/indexer_test.go
> CONFLICT (content): Merge conflict in pkg/controller/admissionchecks/provisioning/indexer_test.go
> Auto-merging pkg/controller/admissionchecks/provisioning/controller_test.go
> Auto-merging pkg/controller/admissionchecks/provisioning/controller.go
> Auto-merging go.sum
> CONFLICT (content): Merge conflict in go.sum
> Auto-merging go.mod
> CONFLICT (content): Merge conflict in go.mod
> Auto-merging cmd/kueue/main.go
> Auto-merging Makefile
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 Introduce the ClusterAutoscaler APIs module
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

ACK

**Pull request merged**
