### PR TITLE
Add mbobrovskyi to the top level reviewer

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
I'm proposing to promote @mbobrovskyi to the top-level reviewer.
His contributions are the following:

- Review: https://github.com/kubernetes-sigs/kueue/pulls?q=is%3Apr+reviewed-by%3Ambobrovskyi+-author%3Ambobrovskyi+created (10)
- Opend PRs: https://github.com/kubernetes-sigs/kueue/pulls/mbobrovskyi (231)

Most actively involving PRs as a reviewer:

- https://github.com/kubernetes-sigs/kueue/pull/2280
- https://github.com/kubernetes-sigs/kueue/pull/2570
- https://github.com/kubernetes-sigs/kueue/pull/2880
- https://github.com/kubernetes-sigs/kueue/pull/2988
- https://github.com/kubernetes-sigs/kueue/pull/3076
- https://github.com/kubernetes-sigs/kueue/pull/2364

He became a community member 5 moths ago: https://github.com/kubernetes/org/issues/4915

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
/hold
for @alculquicondor and @mimowo

**Comment by alculquicondor** [comment]
Those are staggering contributions!

+1

/approve

**Comment by mimowo** [comment]
Thank you for all the contributions, great work!

+1

**Comment by tenzen-y** [comment]
@alculquicondor @mimowo Could you add lgtm tag to this PR?

**Pull request merged**
