### PR TITLE
Remove alculquicondor from OWNERS

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

I'm super proud of what we have achieved with this project that started almost 3 years ago.
We not only built important features for real users, but we did so with care and passion for writing good software.
And it paid off. Kueue is an important building block for large and small companies doing AI training on Kubernetes.

I am confident that @tenzen-y and @mimowo can lead the project to higher levels. And we are already seeing multiple other contributors stepping up with designs, code and ideas.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

/hold

I can still help around until Friday, but I wanted to have the PR ready to go :)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
> @alculquicondor: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Even the tests are not happy about it.

**Comment by mimowo** [comment]
Aldo, congrats for driving the successful project from the ground up. You've not only led the project but also the whole community around it, on issues, on PRs, on slack and more.

Good luck on your next endeavours, and always feel free to return, send a PR or chime into discussions :).

**Comment by alculquicondor** [comment]
/hold cancel

Thank you all 😭

**Comment by tenzen-y** [comment]
> /hold cancel
> 
> Thank you all 😭

😭😭😭

**Pull request merged**
