### PR TITLE
update jobset to 0.6.0

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
JobSet needs to be updated to fix some Kueue+JobSet integration bugs
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Support for JobSet 0.6
```

### CODE REVIEW

**Comment by mimowo** [comment]
Please update release notes saying "Support for JobSet 0.6"

**Comment by kannon92** [comment]
Updated.

**Comment by mimowo** [comment]
Should we also update it in hack/internal/tools/go.mod](https://github.com/kubernetes-sigs/kueue/blob/e27bd2d66d244193b71b9ce8e1ac02a6b4fee447/hack/internal/tools/go.mod#L152)? cc @mbobrovskyi

**Comment by mbobrovskyi** [comment]
Yes, we also need to update hack/internal/tools/go.mod.

**Comment by kannon92** [comment]
Should be all good now.

**Comment by mimowo** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
