### PR TITLE
[kjobctl] Add list RayJob command.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Add list RayJob command on kjobctl.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mszadkow** [comment]
lgtm
I've payed most attention to the tests, they look good

**Review by trasc — COMMENTED** [review]
please rebase, otherwise LGTM

**Comment by mimowo** [comment]
/approve
@trasc would you like to give the final pass?

**Review by trasc — COMMENTED** [review]
/lgtm

**Pull request merged**
