### PR TITLE
Added guide for pod-level integration with Argo Workflows

### LINKED ISSUE #74: Support Argo workflows
This is lower priority than https://github.com/kubernetes-sigs/kueue/issues/65, but it would be good to have an integration with a workflow framework.

Argo supports the suspend flag, the tricky part is that the suspend is for the whole workflow, meaning a QueuedWorkload would need to represent the resources of the whole workflow, and so starting a workflow means reserving capacity for the whole DAG. 

Ideally Argo would create jobs per sequential step, resource reservation happens one step at a time.

### PR DESCRIPTION
**Pull request by sam-leitch-oxb**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Adds documentation on how to integrate with Argo Workflows using plain pod management.

#### Which issue(s) this PR fixes:
Related to #74 

#### Does this PR introduce a user-facing change?
```release-note
Added documentation on pod-level integration with Argo Workflows.
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Hi @sam-leitch-oxb, any reason why you closed this PR?

**Comment by chenxi-seu** [comment]
@alculquicondor Hi, there seems to be progressive strides towards amalgamating Argo workflow support with Kueue. I am very interested in this feature and was hoping to get some updates on its progress and any future plans. Could you please share any information about the current status or expected timelines?

**Comment by sam-leitch-oxb** [comment]
> Hi @sam-leitch-oxb, any reason why you closed this PR?

Need some time to get the CLA approved (using a corporate account)
I didn't want to hold up anything in the interim.

**Comment by tenzen-y** [comment]
> @alculquicondor Hi, there seems to be progressive strides towards amalgamating Argo workflow support with Kueue. I am very interested in this feature and was hoping to get some updates on its progress and any future plans. Could you please share any information about the current status or expected timelines?

@chenxi-seu You can track Argo integration at https://github.com/argoproj/argo-workflows/issues/12363 and #74.

**Review by agilgur5 — COMMENTED** [review]
Nice guide, this is helpful!

I couldn't comment on the PR in-line as the fork was deleted (GH was throwing an error), so a comments below:

For the very last line: Did you mean `plugin` instead of `resource`?
`http` and `plugin` actually do create Pods, it's just not documented much (I found this out only after being a contributor for many months. it's very vaguely mentioned [in the `http` template docs](https://argo-workflows.readthedocs.io/en/release-3.4/http-template/#argo-agent) and manifests linked therein). They create an `agent` Pod if one does not exist in the Workflow's namespace. If one already exists, it gets re-used.

**Comment by kannon92** [comment]
I think this would be worth getting into kueue's site. Going to open up a PR and resurrect this.

**Comment by kannon92** [comment]
https://github.com/kubernetes-sigs/kueue/pull/3897

**Pull request closed without merging**
