### PR TITLE
TAS: Support RayCluster.

### LINKED ISSUE #3372: TAS: support all Job CRDs (including Pods)
**What would you like to be added**:

Add support for all Job CRDs. Currently we have Job and JobSet covered.

This consists two parts:
- computation of the TopologyRequest as in [here](https://github.com/kubernetes-sigs/kueue/blob/1e6d6cc6ae5124bd0317adf34724656bdbe7a812/pkg/controller/jobs/jobset/jobset_controller.go#L124)
-  validation as in [here](https://github.com/kubernetes-sigs/kueue/blob/1e6d6cc6ae5124bd0317adf34724656bdbe7a812/pkg/controller/jobs/jobset/jobset_webhook.go#L135)

The above should be unit tested (new TestPodSets function per CRD).
I suggest one PR per CRD so that we can release at any point, even if not all are done.

**Why is this needed**:

This is part of https://github.com/kubernetes-sigs/kueue/issues/2724 which can be easily separated as another task.
To support TAS for all Job CRDs, it is a point of the plan in the [spreadsheet](https://docs.google.com/spreadsheets/d/1MXCjKZtAfqBTb61bJo46u7jIUqRIlu1NrYj1L8Xz-UU/)

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Support TAS for RayJob.

#### Which issue(s) this PR fixes:

Part of #3372

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
what was the problem fixed?

**Comment by mbobrovskyi** [comment]
> what was the problem fixed?

Conflict with new PodSetTopologyRequest() that expected ObjectMeta instead Template.

**Comment by mimowo** [comment]
thanks!
/lgtm

**Pull request merged**
