### PR TITLE
doc: website jobset url

### PR DESCRIPTION
**Pull request by googs1025**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
- fix website url
- %w can be used only once in a format string
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Please split this in two PRs, as the changes are targeting completely unrelated things.

Also, we would like to cherry-pick the changes to the website without cherry-picking the other.

**Comment by googs1025** [comment]
@alculquicondor Thanks for the suggestion. done!

**Comment by tenzen-y** [comment]
> @alculquicondor Thanks for the suggestion. done!

@googs1025 Aldo meant that we should split this PR into 2 separate PRs (code changes and document changes)

**Review by tenzen-y — COMMENTED** [review]
/ok-to-test
/lgtm
/approve

**Pull request merged**
