### PR TITLE
Support kubeflow.org/paddlejob

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
I added the paddlejob-controller to the frameworkjob-manager.

#### Which issue(s) this PR fixes:

Part-of https://github.com/kubernetes-sigs/kueue/issues/297

#### Special notes for your reviewer:
I verified the behavior using https://github.com/kubernetes-sigs/kueue/pull/1148 example in the real cluster.

#### Does this PR introduce a user-facing change?

```release-note
Support kubeflow.org/paddlejob
```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
/lgtm

**Comment by mimowo** [comment]
@tenzen-y feel free to cancel the hold.

**Comment by tenzen-y** [comment]
> @tenzen-y feel free to cancel the hold.

Thank you!
/hold cancel

**Pull request merged**
