### PR TITLE
Optimize and extend deployment unit tests.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Optimize and extend deployment unit tests.

#### Which issue(s) this PR fixes:

Prepare for #3555

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve

**Comment by mbobrovskyi** [comment]
Resolved conflicts.

**Pull request merged**
