### PR TITLE
Add IBM Research to Kueue adoptors page

### PR DESCRIPTION
**Pull request by dgrove-oss**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Adds IBM Research to Adoptors page. 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
/approve

**Comment by mimowo** [comment]
Thank you as well! cc @mwielgus @mwysokin

**Comment by mwysokin** [comment]
THIS IS AWESOME ❤️ 

Great achievement and kudos to the maintainers @tenzen-y @mimowo 🎉 

@dgrove-oss It's really amazing to see the IBM family committing to Kueue 🖖

**Pull request merged**
