### PR TITLE
Use variadic function to set levels in TopologyWrapper

### LINKED ISSUE #3662: TAS: Use ResourceFlavorWrapper and TopologyWrapper for testing
**What would you like to be cleaned**:

Use the wrappers to setup objects for TAS testing.

**Why is this needed**:

To make the code more consistent (as we use this strategy for other tests), and the shorter.

Example lengthy code: [here](https://github.com/kubernetes-sigs/kueue/blob/560e4340b746aa811cec06b7a072a1a3faedc80f/pkg/scheduler/scheduler_test.go#L4060-L4114).
See below the code for setting up ClusterQueue [here](https://github.com/kubernetes-sigs/kueue/blob/560e4340b746aa811cec06b7a072a1a3faedc80f/pkg/scheduler/scheduler_test.go#L4115-L4119)

### PR DESCRIPTION
**Pull request by mykysha**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Change Levels method of TopologyWrapper to the variadic function to ease the declaration process.

#### Which issue(s) this PR fixes:

Part of #3662 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/lgtm
Thanks!

**Review by mbobrovskyi — APPROVED** [review]

**Comment by mimowo** [comment]
/cherry-pick release-0.9
as commented in https://github.com/kubernetes-sigs/kueue/pull/3819

**Comment by mimowo** [comment]
/cc @mykysha please prepare the cherry-pick for this PR and https://github.com/kubernetes-sigs/kueue/pull/3769 manually using the ./hack/cherry_pick_pull.sh.
cc @mbobrovskyi

**Comment by mykysha** [comment]
@mimowo done in https://github.com/kubernetes-sigs/kueue/pull/3823

**Pull request merged**
