### PR TITLE
Update latest version to v0.8.1

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Update latest version to v0.8.1

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes-sigs/kueue/issues/2985

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by mimowo** [comment]
Forced pushed without changes to retrigger the netifly build which was running for >50min and looked stuck.

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
