### PR TITLE
[Makefile] Use $(PROJECT_DIR) instead of $(shell pwd) 

### LINKED ISSUE #920: Use  `$(PROJECT_DIR)` instead of  ` $(shell pwd)` in the Makefile where ever it's possible.
**What would you like to be cleaned**:
Use  `$(PROJECT_DIR)` instead of  ` $(shell pwd)` in the Makefile where ever it's possible.

Wait for #762 to be merged first.

**Why is this needed**:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Use $(PROJECT_DIR) instead of $(shell pwd) in the Makefile where ever it's possible.

#### Which issue(s) this PR fixes:

Fixes #920

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by trasc** [comment]
wait for #762 to be merged

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
