### PR TITLE
Match release-0.1 tags in manifests

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

To facilitate the installation of the latest image of the release.

#### Which issue(s) this PR fixes:

Part of #197

### CODE REVIEW

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]
Also update https://github.com/kubernetes-sigs/kueue/blob/release-0.1/docs/setup/install.md#install-the-latest-development-version  so it points to the released manifests

**Comment by alculquicondor** [comment]
I will do that in the main branch after we have actually published them

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
