### PR TITLE
Remove kubebuilder:docs-gen marker from tests.

### PR DESCRIPTION
**Pull request by mszadkow**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
We are not generating docs with kubebuilder and this is not needed in tests.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/lgtm
Thanks!

**Review by mbobrovskyi — APPROVED** [review]

**Comment by mimowo** [comment]
/approve
Thanks!

**Pull request merged**
