### PR TITLE
remove the deprecated annotations for provisioningrequests

### LINKED ISSUE #2747: Remove deprecated ProvisioningRequest annotations
**What would you like to be cleaned**:
Since [this PR](https://github.com/kubernetes-sigs/kueue/pull/2726), we started supporting the new ProvisioningRequest annotations, but we did not remove deprecated annotations so that we can maintain backward compatibility with the previous ClusterAutoscaler versions.

So, based on the Kubernetes deprecation policy, as we discussed [here](https://github.com/kubernetes-sigs/kueue/pull/2726#discussion_r1697928601), we would like to stop using deprecated ProvisioningRequest annotations here:

https://github.com/kubernetes-sigs/kueue/blob/e34732589c27f1d82f4e90c0d15c59ebb5f05e28/pkg/controller/admissionchecks/provisioning/constants.go#L22-L23

**Why is this needed**:
Deprecated annotations will be removed in the future ClusterAutocaler version.

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind deprecation
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #2747 

#### Does this PR introduce a user-facing change?

```release-note
Remove deprecated ProvisioningRequest annotations
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
/hold

We need to keep supporting deprecated annotations for a while, like a year.

**Comment by mimowo** [comment]
> We need to keep supporting deprecated annotations for a while, like a year.

I agree, IIUC if we remove the annotations now, then the coming release of Kueue will not support the older versions of CA.

I'm wondering what is the last version of CA which supported the old annotations, and the first version of CA which supports the new annotations. Do you know @yaroslava-serdiuk ?

**Comment by yaroslava-serdiuk** [comment]
@mimowo The first CA version that supports ProvisoningRequests and used old annotations is 1.30.1 and in 1.30.2 we deprecated old annotations and introduced a new ones.

**Comment by mimowo** [comment]
Thanks, 1.30.1 is still very new. I think we need to wait until it gets EOL and only then drop the support in Kueue.

**Comment by kannon92** [comment]
Ah sorry. I read the issue and thought it was ready to deprecate.

/close

**Pull request closed without merging**
