### PR TITLE
Fix unclosed action error.

### LINKED ISSUE #2682: manager unclosed action
Hello 
Sorry for reporting this small thing.

**What happened**: 
```
helm install kueue kueue/ --create-namespace --namespace kueue-system --set enableCertManager=true
Error: parse error at (kueue/templates/manager/manager.yaml:59): unclosed action
```

**What you expected to happen**:
```helm install kueue kueue/ --create-namespace --namespace kueue-system --set enableCertManager=true
NAME: kueue
LAST DEPLOYED: Tue Jul 23 23:20:02 2024
NAMESPACE: kueue-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Anything else we need to know?**:
```
    resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
```
```
resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10 }}
```
**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: v1.28.2
- Kueue version (use `git describe --tags --dirty --always`): v0.8.0-1-g78783a26-dirty
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`):
- Install tools: Helm
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix "unclosed action" error.

#### Which issue(s) this PR fixes:

Fixes #2682

#### Special notes for your reviewer:
This issue reproduced with helm v3.5.2.

#### Does this PR introduce a user-facing change?

```release-note
Helm: Fix a bug for "unclosed action error".
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
@mbobrovskyi Could you share the result with the `helm template` when we specify the resources?

**Comment by mbobrovskyi** [comment]
Yes, sure.

```yaml
---
# Source: kueue/templates/manager/manager.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kueue-controller-manager
  namespace: 'kueue-system'
  labels:
    helm.sh/chart: kueue-0.1.0
    app.kubernetes.io/name: kueue
    app.kubernetes.io/instance: kueue
    control-plane: controller-manager
    app.kubernetes.io/version: "v0.8.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kueue
      app.kubernetes.io/instance: kueue
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kueue
        app.kubernetes.io/instance: kueue
        control-plane: controller-manager
      annotations:
        charts.kueue.x-k8s.io/config-checksum: 8d11b03bf6e627c5ad2a0c1691a59ddb427c389c8e0a1c6247cff31da2e86ecf
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args:
        - --config=/controller_manager_config.yaml
        - --zap-log-level=2        
        command:
        - /manager
        image: "us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue:v0.8.0"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        name: manager
        ports:
        - containerPort: 8082
          name: visibility
          protocol: TCP
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - mountPath: /controller_manager_config.yaml
          name: manager-config
          subPath: controller_manager_config.yaml
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0"
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kueue-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: kueue-webhook-server-cert
      - configMap:
          name: kueue-manager-config
        name: manager-config
```

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Helm: Fix a bug for "unclosed action error".
```

**Comment by tenzen-y** [comment]
> /lgtm

Oh, what a timing :) That's completely same timing :)

**Pull request merged**
