### PR TITLE
Update pod controller to reconcile not found pods

### LINKED ISSUE #1450: High churn cluster with pod only causing stuck queue and overcommitment
**What happened**:

Workloads are not deleted even though the pods are deleted, keeping a dangling finalizer and thus the queue gets stuck

**What you expected to happen**:

Work is processed correctly

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The queue shows > 1000 admitted workloads, even though only about 110 are allowed:

Bildschirmfoto 2023-12-13 um 19 44 45

The following shows that there are stucked workloads on the ClusterQueue "background" stuck since a few hours.
Bildschirmfoto 2023-12-13 um 19 59 04

workloads have a deletion timestamp and finalizer, which is hours old (pod does not exist anymore)
Bildschirmfoto 2023-12-13 um 20 18 36

looks like that is not finialized, even though the "JobFinished" condition is true on the workflow (example from a different stuck workload): 

Bildschirmfoto 2023-12-14 um 08 08 31

Deleting the finalizer, causes the admitted "workload" resources to get cleaned up. Restarting the controller didn't resolve the error.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.28.3-eks
- Kueue version (use `git describe --tags --dirty --always`): v0.5.1
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by achernevskii**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

* If pod is not found, it shouldn't be skipped, since there could be a dangling workload that should be finalized.

* Update `Skip` method for the pod controller to return false if the pod is not found.

* Add an integration test for the case when pods are finalized and deleted before the workload finalizer is removed.

#### Which issue(s) this PR fixes:

Fixes #1450

#### Special notes for your reviewer:

The integration test could be replaced with a unit test for the sake of testing speed increase.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
1. Can you explain what happens in this line when the Pod doesn't exist?

https://github.com/kubernetes-sigs/kueue/blob/d7b31dab1ab75a2bb647a114669a87c7149d237b/pkg/controller/jobframework/reconciler.go#L178

2. I think this fix is still incomplete. This is relying on the fact that a key for the Pod made it to the work queue. This will not be true if the kueue controller restarts after the Pods have been deleted. Hence, I think a better solution is to remove the workload finalizer in the workload controller when it has a Finished condition or the ownerReferences are empty https://github.com/kubernetes-sigs/kueue/pull/1454#discussion_r1427329374

**Comment by achernevskii** [comment]
> Can you explain what happens in this line when the Pod doesn't exist?

`GetDeletionTimestamp` will return a nil pointer to `metav1.Time`, IsZero will return true:
https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/time.go#L60-L62
And the job reconciler won't try to finalize a non-existing job.


I could add an additional check, to make sure that the job is found and not rely on the behaviour of `IsZero`and `GetDeletionTimestamp`.

**Comment by alculquicondor** [comment]
> I could add an additional check, to make sure that the job is found and not rely on the behaviour of IsZeroand GetDeletionTimestamp.

No, I think your answer is enough.

Can you open a separate PR to solve the problem via the workload finalizer instead? I want to see which of the PRs is simpler so that it can be cherry-picked to release-0.5.

**Comment by alculquicondor** [comment]
Ah right, other jobs don't have `Skip`.

Can you also cherry-pick into release-0.5 if the automatic one doesn't work?

/cherry-pick
/lgtm
/approve

**Comment by tenzen-y** [comment]
> @tenzen-y: #1512 failed to apply on top of branch "release-0.5":
> ```
> Applying: Update pod controller to reconcile not found pods
> Using index info to reconstruct a base tree...
> M	pkg/controller/jobs/pod/pod_controller.go
> M	test/integration/controller/jobs/pod/pod_controller_test.go
> Falling back to patching base and 3-way merge...
> Auto-merging test/integration/controller/jobs/pod/pod_controller_test.go
> Auto-merging pkg/controller/jobs/pod/pod_controller.go
> CONFLICT (content): Merge conflict in pkg/controller/jobs/pod/pod_controller.go
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 Update pod controller to reconcile not found pods
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> 
> ```
> 
> <details>
> 
> In response to [this](https://github.com/kubernetes-sigs/kueue/pull/1512#issuecomment-1870541876):
> 
> >/cherry-pick release-0.5
> 
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
> </details>

@achernevskii Can you create a cherry-pick PR?

**Comment by achernevskii** [comment]
Created a separate fix pull request #1524

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Fix a bug in the pod integration that unexpected error will occur when the pod isn't find
```

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Fix a bug in the pod integration that unexpected errors will occur when the pod isn't found
```

**Pull request merged**
