### PR TITLE
Self-nominate pbundyra as a Kueue reviewer

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
I believe I met all the [requirments](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-1) to become a reviewer, and it would be a great pleasure of mine to become one.

Check-list:
- [X] Member for at least 3 months [link](https://github.com/kubernetes/org/issues/4795)
- [X] Primary reviewer for at least 5 PRs to the codebase: [15 reviews](https://github.com/kubernetes-sigs/kueue/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3Apbundyra+-author%3Apbundyra)
- [X] Reviewed or merged at least 20 substantial PRs to the codebase: [48 merged PRs](https://github.com/kubernetes-sigs/kueue/pulls?q=is%3Apr+is%3Amerged+author%3Apbundyra)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by PBundyra** [comment]
/assign @mimowo 
cc @tenzen-y

**Comment by mimowo** [comment]
> I believe I met all the https://github.com/kubernetes-sigs/kueue/issues/3331 to become a reviewer, and it would be a great pleasure to become one

Please update the description to have a checklist for the requirements based on https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-1

**Comment by mimowo** [comment]
+1, thank you for the contributions!

**Review by tenzen-y — COMMENTED** [review]
Thank you for your contribution!
/lgtm
/approve

**Pull request merged**
