### PR TITLE
Delete ClusterQueueSnapshot.Lendable

### PR DESCRIPTION
**Pull request by gabesaba**
#### What type of PR is this?
/kind cleanup
#### What this PR does / why we need it:
Only used in test code

related to #2502 cleanup

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve

**Comment by gabesaba** [comment]
thanks for the review!

/retest

**Pull request merged**
