### PR TITLE
[website] Using docsy instead GitHub style Note.

### LINKED ISSUE #1755: Introduce the docsy style Note
**What would you like to be cleaned**:
It would be better to replace a simple markdown style Note with the docsy style shortcode.

The sample of Docsy style: https://github.com/kubernetes-sigs/kueue/blob/main/site/content/en/docs/tasks/setup_sequential_admission.md#enabling-waitforpodsready

**Why is this needed**:
The shortcode could be emphasize the Notes.

/kind documentation

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Using docsy instead GitHub style Note.

#### Which issue(s) this PR fixes:

Fixes #1755

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by trasc — COMMENTED** [review]
/lgtm

**Comment by mbobrovskyi** [comment]
> / approve / cherry-pick release-0.8

Maybe website?

**Comment by mimowo** [comment]
> > / approve / cherry-pick release-0.8
> 
> Maybe you mean website?

Yes, thanka

**Pull request merged**
