### PR TITLE
Bump shellcheck version v0.9.0 -> v0.10.0.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Bump shellcheck version v0.9.0 -> v0.10.0.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by trasc — COMMENTED** [review]
/lgtm

**Review by mimowo — COMMENTED** [review]
/approve
Maybe for future we could consider managing this version via dependabot as well. WDYT @tenzen-y ?

**Pull request merged**
