### PR TITLE
Align the retryDelayMinutes deprecation notice with the standard form

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
API deprecation notice should be aligned with standardized form so that linter can detect the deprecation comment in external projects.

https://go.dev/wiki/Deprecated

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by mbobrovskyi — COMMENTED** [review]
I think we missed to generate helm templates and website references.

**Comment by tenzen-y** [comment]
> I think we missed to generate helm templates and website references.

Ah, that's true. Thanks. I updated this PR.

**Review by mbobrovskyi — COMMENTED** [review]
/lgtm

Thanks!

**Pull request merged**
