### PR TITLE
Add adopters to top menu

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

To improve awareness of the page

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
This PR has conflicts.

**Comment by alculquicondor** [comment]
yup, working through it... too many adopters lately :)

**Comment by tenzen-y** [comment]
> yup, working through it... too many adopters lately :)

It great to hear :)

**Comment by alculquicondor** [comment]
I'm not sure how to modify the design of the page if I put it on the top level :(

We can leave that for a follow up.

/hold cancel

**Review by tenzen-y — COMMENTED** [review]
Looks great.
/lgtm

screenshot_2023-11-14 7 29 24

**Comment by tenzen-y** [comment]
@alculquicondor Can I remove this branch, `adopters-home`?

**Comment by alculquicondor** [comment]
That's what happens when I open a PR this late :)

**Pull request merged**
