### PR TITLE
e2e speedup

### PR DESCRIPTION
**Pull request by pajakd**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We want to decrease the execution time of the e2e tests. In order to do so, I want to create a separate make target for the multikueue tests and remove multikueue tests from the existing test-e2e target (this PR) and run them in a separate job in the presubmits/periodic tests (separate PR as this is in a different repository).

Plus it fixes a typo in test/e2e/multikueue/suite_test.go 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```
NONE

### CODE REVIEW

**Review by trasc — COMMENTED** [review]
Overall LGTM, but yes we need the test-infra side as well, also regarding that maybe we can just add ` test-multikueue-e2e` target to the already existing jobs.

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
NONE
```

**Comment by alculquicondor** [comment]
This change brings e2e jobs down to 8 min, which is great.

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
