### PR TITLE
Refactor update(Flavor|Cohort)Usage to take FlavorResourceQuantitiesFlat

### PR DESCRIPTION
**Pull request by gabesaba**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Preparation for #2596, where we want to add usage to Cohort without needing a workload. See [WIP Commit](https://github.com/gabesaba/kueue/commit/c3277c97cadc5653505b6a86add07d0c1f1b5dc6) for example of intended usage.

Additionally, gets us closer to #2447 cleanup.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve

**Comment by mimowo** [comment]
/hold
To investigate if the failure is related https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2633/pull-kueue-test-unit-main/1813897188141436928. Feel free to cancel the hold if not related

**Comment by gabesaba** [comment]
thanks for the review!

the failure is unrelated. different suite, and noisy field:
```
        - 			CreationTimestamp: v1.Time{Time: s"2024-07-18 11:29:27 +0000 UTC"},
        + 			CreationTimestamp: v1.Time{Time: s"2024-07-18 11:29:26 +0000 UTC"},
```

/unhold

**Pull request merged**
