### PR TITLE
WIP: Add import mode to job reconciler

### PR DESCRIPTION
**Pull request by nstogner**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Allow for existing jobs to be imported into Kueue by disabling suspension/stopping of jobs that do not have admitted Workloads. This allows Kueue to create Workload objects and quota to be reconciled for existing workloads. Intended to facilitate the installation of Kueue into a running cluster.

Example steps for adopting Kueue:

1. Ensure all new jobs in a cluster contain kueue labels.
2. Create all ClusterQueues, etc.
3. Run Kueue in import-mode.
4. Wait for all non-labeled jobs to finish.
5. Validate expected Workload admission statuses exist.
6. Switch Kueue into non-import-mode.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
@mimowo wdyt?

**Comment by mimowo** [comment]
> @mimowo wdyt?

I like it in principle, and I think this is going to be important. I would like to ask some questions to clarify the process though:

> 1. Ensure all new jobs in a cluster contain kueue labels.

which kueue labels concretely, just `queue-name` or some other too? This entails a separate script I guess which iterates over all jobs and patches them, right?

> 2. Create all ClusterQueues, etc.
> 3. Run Kueue in import-mode.
> 4. Wait for all non-labeled jobs to finish.

How we would have non-labeled jobs since we added the labels in step (1.)

> 5. Validate expected Workload admission statuses exist.
> 6. Switch Kueue into non-import-mode.

Additional, extra question: do we need to deal / how do we deal with overcommitted resources? Meaning, say someone has running jobs exceeding the quota configured in point (2.). 

I see three options:
1. import them all and temporarily run overcommited, 
2. import them all and preempt some to get under quota
3. import gradually, never exceeding the quota

My preference would be for (1.) as this is a special mode anyway, but would like to clarify. This may actually require a small KEP to discuss pros / cons. But overall, +1 for the feature.

**Comment by nstogner** [comment]
> which kueue labels concretely, just queue-name or some other too? This entails a separate script I guess which iterates over all jobs and patches them, right?

> How we would have non-labeled jobs since we added the labels in step (1.)

I guess there are multiple paths that could be taken, I was describing one where there is a system that is responsible for submitting new jobs, and that system is first updated to start submitting jobs as if Kueue were in place. All labels for identifying queues, pod group sizes, etc. would be included even though Kueue is not yet in place. You could also run a script to label running workloads, but my description was assuming that you would just allow those workloads to age out before running Kueue. A user could take either or both approaches (age-out / script-label).

> Additional, extra question: do we need to deal / how do we deal with overcommitted resources? Meaning, say someone has running jobs exceeding the quota configured in point (2.).

My original thought was the following which sounds like your (1.):

Allow Kueue to create Workloads for all running jobs during import mode. While suspension/stopping is disabled, some of these Workloads would have an admitted condition and some would not, but all would continue to run. The administrator could then inspect which of the running Workloads are considered admissible under the new Kueue system they are introducing. They could then turn off import-mode and allow the Workloads in violation to be evicted as per the quotas they have defined in the queues - or they could change their queues until all workloads fit in their queues.

**Comment by alculquicondor** [comment]
I guess Kueue would still mark a Workload with Eviction=true even if it doesn't actually stop the jobs/pods. So an administrator could inspect Workload objects and make sure no critical jobs are marked for eviction before disabling import mode.
Could you confirm this?

**Comment by nstogner** [comment]
> Could you confirm this?

Yes, I will test this now.

**Comment by mimowo** [comment]
> I was describing one where there is a system that is responsible for submitting new jobs, and that system is first updated to start submitting jobs as if Kueue were in place. All labels for identifying queues, pod group sizes, etc. would be included even though Kueue is not yet in place.

got it, thanks for explaining.

> My original thought was the following which sounds like your (1.): 
> Allow Kueue to create Workloads for all running jobs during import mode. While suspension/stopping is disabled, some of these Workloads would have an admitted condition and some would not, but all would continue to run. 

sgtm, thanks for explaining, this is what I would expect, but we should test this manually, and some integration tests would be nice as part of the PR.

**Comment by nstogner** [comment]
@alculquicondor A quick manual test appears to confirm the behavior of the Eviction condition being added but not acted upon (and resources not freed up for the preemptor job to use - while under `importMode: true`).

I can start to add some automated tests.

```bash
➜  jobs git:(import-mode) ✗ k get workloads                                                
NAME                     QUEUE        ADMITTED BY     AGE
job-p1-job-lvhfn-a62d1   user-queue                   5m40s
job-p2-job-sr7rp-badd1   user-queue   cluster-queue   10m
➜  jobs git:(import-mode) ✗ k get workloads job-p2-job-sr7rp-badd1 -oyaml | grep -B 3 Evict
    message: Preempted to accommodate a higher priority Workload
    reason: Preempted
    status: "True"
    type: Evicted
➜  jobs git:(import-mode) ✗ k get pods
NAME                 READY   STATUS    RESTARTS   AGE
p2-job-sr7rp-gbwlt   1/1     Running   0          11m
p2-job-sr7rp-kh9xv   1/1     Running   0          11m
p2-job-sr7rp-lw5rw   1/1     Running   0          11m
➜  jobs git:(import-mode) ✗ # Set importMode: false ...
➜  jobs git:(import-mode) ✗ k edit cm -n kueue-system kueue-manager-config
configmap/kueue-manager-config edited
➜  jobs git:(import-mode) ✗ k delete pods -n kueue-system --all
pod "kueue-controller-manager-574bffb9cf-xcjgv" deleted
➜  jobs git:(import-mode) ✗ k get pods -n kueue-system -w
NAME                                        READY   STATUS    RESTARTS   AGE
kueue-controller-manager-574bffb9cf-rbtdn   1/2     Running   0          10s
kueue-controller-manager-574bffb9cf-rbtdn   2/2     Running   0          13s
^C%                                                                                                           
➜  jobs git:(import-mode) ✗ k get workloads
NAME                     QUEUE        ADMITTED BY     AGE
job-p1-job-lvhfn-a62d1   user-queue   cluster-queue   7m20s
job-p2-job-sr7rp-badd1   user-queue                   12m
➜  jobs git:(import-mode) ✗ k get pods
NAME                 READY   STATUS        RESTARTS   AGE
p1-job-lvhfn-c4zzg   1/1     Running       0          12s
p1-job-lvhfn-ll89q   1/1     Running       0          12s
p1-job-lvhfn-xmprj   1/1     Running       0          12s
p2-job-sr7rp-gbwlt   1/1     Terminating   0          12m
p2-job-sr7rp-kh9xv   1/1     Terminating   0          12m
p2-job-sr7rp-lw5rw   1/1     Terminating   0          12m
```

**Comment by tenzen-y** [comment]
> @alculquicondor A quick manual test appears to confirm the behavior of the Eviction condition being added but not acted upon (and resources not freed up for the preemptor job to use - while under `importMode: true`).
> 
> I can start to add some automated tests.
> 
> ```shell
> ➜  jobs git:(import-mode) ✗ k get workloads                                                
> NAME                     QUEUE        ADMITTED BY     AGE
> job-p1-job-lvhfn-a62d1   user-queue                   5m40s
> job-p2-job-sr7rp-badd1   user-queue   cluster-queue   10m
> ➜  jobs git:(import-mode) ✗ k get workloads job-p2-job-sr7rp-badd1 -oyaml | grep -B 3 Evict
>     message: Preempted to accommodate a higher priority Workload
>     reason: Preempted
>     status: "True"
>     type: Evicted
> ➜  jobs git:(import-mode) ✗ k get pods
> NAME                 READY   STATUS    RESTARTS   AGE
> p2-job-sr7rp-gbwlt   1/1     Running   0          11m
> p2-job-sr7rp-kh9xv   1/1     Running   0          11m
> p2-job-sr7rp-lw5rw   1/1     Running   0          11m
> ➜  jobs git:(import-mode) ✗ # Set importMode: false ...
> ➜  jobs git:(import-mode) ✗ k edit cm -n kueue-system kueue-manager-config
> configmap/kueue-manager-config edited
> ➜  jobs git:(import-mode) ✗ k delete pods -n kueue-system --all
> pod "kueue-controller-manager-574bffb9cf-xcjgv" deleted
> ➜  jobs git:(import-mode) ✗ k get pods -n kueue-system -w
> NAME                                        READY   STATUS    RESTARTS   AGE
> kueue-controller-manager-574bffb9cf-rbtdn   1/2     Running   0          10s
> kueue-controller-manager-574bffb9cf-rbtdn   2/2     Running   0          13s
> ^C%                                                                                                           
> ➜  jobs git:(import-mode) ✗ k get workloads
> NAME                     QUEUE        ADMITTED BY     AGE
> job-p1-job-lvhfn-a62d1   user-queue   cluster-queue   7m20s
> job-p2-job-sr7rp-badd1   user-queue                   12m
> ➜  jobs git:(import-mode) ✗ k get pods
> NAME                 READY   STATUS        RESTARTS   AGE
> p1-job-lvhfn-c4zzg   1/1     Running       0          12s
> p1-job-lvhfn-ll89q   1/1     Running       0          12s
> p1-job-lvhfn-xmprj   1/1     Running       0          12s
> p2-job-sr7rp-gbwlt   1/1     Terminating   0          12m
> p2-job-sr7rp-kh9xv   1/1     Terminating   0          12m
> p2-job-sr7rp-lw5rw   1/1     Terminating   0          12m
> ```

It's a curious behavior. If the preemptor job has higher priority than the evited job, what happens?

**Comment by mimowo** [comment]
One more conceptual question: 

Context: IIUC during the import, we create workloads, along with their admission to resource flavors, while the jobs are running.

Is it actually always possible to reconstruct the workload's PodSet admission based on the running pods? Mappoing PodSetAssignment resourceName (say CPU) to resource flavor (given the already running pods), see here: https://github.com/kubernetes-sigs/kueue/blob/bd2d09c287fe6ba6efd2991de741209972f8d9d4/apis/kueue/v1beta1/workload_types.go#L91C2-L91C84.

Say, a job might be running pods scattered across nodes corresponding to different flavors (because there was no specific nodeSelector), so there might not always be a reliable way to create the PodSetAssignments (IIUC). If my understanding is correct, could this be an issue, or we don't rely on that?

**Comment by alculquicondor** [comment]
/close
in favor of https://github.com/kubernetes-sigs/kueue/tree/main/cmd/importer

**Pull request closed without merging**
