### PR TITLE
WIP: Make a reciever of FlavorResourceQuantites.For pointer

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
For the `FlavorResourceQuantities`, `Add` uses the pointer receiver, `For` uses the non pointer receiver.
But, it would be better to use either a pointer or nonpointer receiver across all functions for the struct.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by gabesaba** [comment]
Is this an improvement? Since `FlavorResourceQuantities` is a map type, I don't think we gain anything by using a pointer, and the new code is a less clean - 3 lines instead of 1, and have to deref inside ()

The only reason we used pointer receiver in the `Add` method is so that it could handle the null map case

**Comment by tenzen-y** [comment]
> Is this an improvement? Since `FlavorResourceQuantities` is a map type, I don't think we gain anything by using a pointer, and the new code is a less clean - 3 lines instead of 1, and have to deref inside ()

That sounds reasonable.

> The only reason we used pointer receiver in the Add method is so that it could handle the null map case

If so, shouldn't we use the non pointer `f` for `Add` function like the following since map type already pointer type, right?

```golang
func (f FlavorResourceQuantities) Add(fr FlavorResource, v int64) {
	if f == nil {
		f = make(FlavorResourceQuantities)
	}
...
```

**Comment by tenzen-y** [comment]
> > Is this an improvement? Since `FlavorResourceQuantities` is a map type, I don't think we gain anything by using a pointer, and the new code is a less clean - 3 lines instead of 1, and have to deref inside ()
> 
> That sounds reasonable.
> 
> > The only reason we used pointer receiver in the Add method is so that it could handle the null map case
> 
> If so, shouldn't we use the non pointer `f` for `Add` function like the following since map type already pointer type, right?
> 
> ```go
> func (f FlavorResourceQuantities) Add(fr FlavorResource, v int64) {
> 	if f == nil {
> 		f = make(FlavorResourceQuantities)
> 	}
> ...
> ```

Oh, I found the above code. NVM.

**Comment by trasc** [comment]
> > Is this an improvement? Since `FlavorResourceQuantities` is a map type, I don't think we gain anything by using a pointer, and the new code is a less clean - 3 lines instead of 1, and have to deref inside ()
> 
> That sounds reasonable.
> 
> > The only reason we used pointer receiver in the Add method is so that it could handle the null map case
> 
> If so, shouldn't we use the non pointer `f` for `Add` function like the following since map type already pointer type, right?
> 
> ```go
> func (f FlavorResourceQuantities) Add(fr FlavorResource, v int64) {
> 	if f == nil {
> 		f = make(FlavorResourceQuantities)
> 	}
> ...
> ```

You only change the local f , not the caller.

we can replace the Add method with something like `append`, and.

``` 
f = Append(f, k, v)
```

**Comment by mimowo** [comment]
/close 
based on https://github.com/kubernetes-sigs/kueue/pull/2689#issuecomment-2257935546

**Pull request closed without merging**
