### PR TITLE
[kjobctl] refactor to use utilmaps.SortedKeys

### PR DESCRIPTION
**Pull request by alexandear**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR simplifies implementation of `describeConfigMap` by using `utilmaps.SortedKeys` and removing the `sortMapKeys` function.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by mbobrovskyi — COMMENTED** [review]
/lgtm
Thanks!

**Comment by mimowo** [comment]
cc @mwysokin

**Comment by mbobrovskyi** [comment]
@alexandear could you please fix test?

**Comment by alexandear** [comment]
> @alexandear could you please fix test?

fixed

**Comment by mbobrovskyi** [comment]
One more :)

**Comment by mbobrovskyi** [comment]
/lgtm
Thanks!

**Pull request merged**
