### PR TITLE
Add release checklist to add new periodic for patch release

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
We want to make sure we have coverage on release branches
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by kannon92** [comment]
/assign @mimowo @tenzen-y 

We discussed this [here](https://github.com/kubernetes/test-infra/pull/33833#issuecomment-2511902305)

**Review by mimowo — COMMENTED** [review]
I think updating them will typically be one PR, so maybe better to inline?

**Comment by mimowo** [comment]
I was thinking about a single point, the current form kind of suggests there would be two PRs, no?

**Comment by kannon92** [comment]
> I was thinking about a single point, the current form kind of suggests there would be two PRs, no?

There isn't an example that shows both though.

**Pull request merged**
