### PR TITLE
Add release notes to the body of the pull request on create cherry-pick.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Add release notes to the body of the pull request on create cherry-pick.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
TBH, I would like to work on the script improvement at k/k before we move this forward.
I would like to keep using the same script as the k/k one.

**Comment by mbobrovskyi** [comment]
> TBH, I would like to work on the script improvement at k/k before we move this forward. I would like to keep using the same script as the k/k one.

I think it's a good idea! I will create PR on k/k. Thanks.

**Review by tenzen-y — COMMENTED** [review]
These changes are approved at https://github.com/kubernetes/kubernetes/pull/126925.
@mbobrovskyi So, could you align only with approved changes?

**Comment by mbobrovskyi** [comment]
> These changes are approved at [kubernetes/kubernetes#126925](https://github.com/kubernetes/kubernetes/pull/126925). @mbobrovskyi So, could you align only with approved changes?

Yes, that what we have. Only difference with Copyright year.

**Review by tenzen-y — COMMENTED** [review]
Thanks.
/lgtm
/approve

**Pull request merged**
