### PR TITLE
Increase timeout for lint

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

In the bots, linter runs with 2 cores, which can go over the timelimit

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
Uhm. Even if we increase the timeout, CI fails.

- 7m

```
go: downloading github.com/prometheus/common v0.32.1
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading google.golang.org/protobuf v1.28.0
go: downloading github.com/mattn/go-runewidth v0.0.9
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
/home/prow/go/src/sigs.k8s.io/kueue/bin/golangci-lint run --timeout 7m0s
make: *** [Makefile:162: ci-lint] Killed
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/806/pull-kueue-verify-main/1663892809674919936

- 10m

```
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/prometheus/common v0.32.1
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading google.golang.org/protobuf v1.28.0
go: downloading github.com/mattn/go-runewidth v0.0.9
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
/home/prow/go/src/sigs.k8s.io/kueue/bin/golangci-lint run --timeout 10m0s
make: *** [Makefile:162: ci-lint] Killed
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/824/pull-kueue-verify-main/1663915921636331520

**Comment by alculquicondor** [comment]
Let's rerun the test a few times with 15min. If it times out, then it's probably being sigkilled

**Comment by alculquicondor** [comment]
Passed 1/3

/test pull-kueue-verify-main

**Comment by alculquicondor** [comment]
Passed 2/3

/test pull-kueue-verify-main

**Comment by alculquicondor** [comment]
Passed 3/3

/assign @trasc

**Pull request merged**
