### PR TITLE
Fix the broken links in the documents

### PR DESCRIPTION
**Pull request by tenzen-y**
Signed-off-by: tenzen-y <yuki.iwai.tz@gmail.com>

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
I fixed the broken links in the documents.

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by kerthcet** [comment]
/lgtm

Thanks.

**Comment by alculquicondor** [comment]
/approve

Thanks! If you don't mind, can you cherry-pick to the release-0.2 branch?

**Comment by tenzen-y** [comment]
> /approve
> 
> Thanks! If you don't mind, can you cherry-pick to the release-0.2 branch?

@alculquicondor Thanks for the review.
Sure, I will do it.

**Pull request merged**
