### PR TITLE
Increase log level in k8s components

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Increases log level of k8s components in order to diagnose problems such as #1372 in the future.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by kannon92** [comment]
/hold
/lgtm

Holding to prevent a merge.

**Comment by alculquicondor** [comment]
No point in holding. We will see if there are failures in the future.

/hold cancel

**Pull request merged**
