### PR TITLE
Bump GO to 1.20

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
With the upcoming https://github.com/kubernetes-sigs/kueue/issues/659 release, is always good to revisit dependencies 

#### Special notes for your reviewer:
`make build image-build test test-integration`
run to completion after this change

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Depends on https://github.com/kubernetes/test-infra/pull/29225
/hold

**Comment by ArangoGutierrez** [comment]
A soft rebase is all it needed :)

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by ArangoGutierrez** [comment]
> Depends on https://github.com/kubernetes/test-infra/pull/29225
> /hold

/Unhold

**Pull request merged**
