### PR TITLE
[kueuectl] Add stop/resume localqueue commands.

### LINKED ISSUE #2138: [kueuectl] Add resume LocalQueue command
**What would you like to be added**:
Add resume LocalQueue command.

**Why is this needed**:
To resumes admission of Workloads coming from the given LocalQueue. This requires adding StopPolicy to LocalQueue and enforcing its changes in ClusterQueue (#2109).

Design details https://github.com/kubernetes-sigs/kueue/tree/main/keps/2076-kueuectl#resume-localqueue.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

### PR DESCRIPTION
**Pull request by rainfd**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Add stop/resume localqueue commands.

#### Which issue(s) this PR fixes:
Fixes #2138 #2139

#### Does this PR introduce a user-facing change?

```release-note
CLI: Add stop/resume localqueue commands
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
Good Job! Thanks!
LGTM

/assign @trasc

**Review by trasc — COMMENTED** [review]
/lgtm
/approve

**Review by alculquicondor — COMMENTED** [review]
/approve

**Comment by mbobrovskyi** [comment]
/release-note-edit ```
CLI: Add stop/resume localqueue commands
```

**Comment by mbobrovskyi** [comment]
/release-note-edit ```CLI: Add stop/resume localqueue commands```

**Comment by mbobrovskyi** [comment]
/release-note-edit ```release-note CLI: Add stop/resume localqueue commands```

**Comment by mbobrovskyi** [comment]
/release-note-edit 

```release-note 
CLI: Add stop/resume localqueue commands
```

**Pull request merged**
