### PR TITLE
Remove the kubebuilder PROJECT file

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

We used the kubebuilder to set up this repository. But, now, we drive this repository by ourselves.
To avoid the following errors, I removed the kubebuilder PROJECT file.

~~When we use the kubebuilder v4 locally and road the completions with `source <(kubebuilder completion bash)`, every shell launching (`./.bashrc`) we always face the error and shell launching goes to fail:~~

```shell
Error: no plugin could be resolved with key "go.kubebuilder.io/v3" for project version "3"
Usage:
  kubebuilder [flags]

Examples:
The first step is to initialize your project:
    kubebuilder init [--plugins=<PLUGIN KEYS> [--project-version=<PROJECT VERSION>]]

<PLUGIN KEYS> is a comma-separated list of plugin keys from the following table
and <PROJECT VERSION> a supported project version for these plugins.

                             Plugin keys | Supported project versions
-----------------------------------------+----------------------------
               base.go.kubebuilder.io/v4 |                          3
 deploy-image.go.kubebuilder.io/v1-alpha |                          3
                    go.kubebuilder.io/v4 |                          3
         grafana.kubebuilder.io/v1-alpha |                          3
      kustomize.common.kubebuilder.io/v2 |                          3

For more specific help for the init command of a certain plugins and project version
configuration please run:
    kubebuilder init --help --plugins=<PLUGIN KEYS> [--project-version=<PROJECT VERSION>]

Default plugin keys: "go.kubebuilder.io/v4"
Default project version: "3"


Flags:
  -h, --help                     help for kubebuilder
      --plugins strings          plugin keys to be used for this subcommand execution
      --project-version string   project version (default "3")

FATA no plugin could be resolved with key "go.kubebuilder.io/v3" for project version "3"
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Should we get rid of the scaffolding settings altogether? It was good to get the project started, but we don't really use it anymore. Do you?

**Comment by tenzen-y** [comment]
> Should we get rid of the scaffolding settings altogether? It was good to get the project started, but we don't really use it anymore. Do you?

That is a good point. Let me convert this PR to remove PROJECT file.

**Comment by alculquicondor** [comment]
we should also remove all tags using `+kubebuilder:scaffold`

**Comment by tenzen-y** [comment]
> we should also remove all tags using `+kubebuilder:scaffold`

You're right. I removed the markers for kubebuilder scaffolding.

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Pull request merged**
