### PR TITLE
Update ray examples.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Ray job and ray cluster examples very old and not working with ray-operator v1.1.0 and newer.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
/kind documentation
IIUC - since this impacts documentation.

**Comment by mimowo** [comment]
Are these examples from  KubeRay (https://raw.githubusercontent.com/ray-project/kuberay/v1.1.1/ray-operator/config/samples/ray-job.sample.yaml)?

**Comment by mbobrovskyi** [comment]
Yes, exactly. And also from https://raw.githubusercontent.com/ray-project/kuberay/v1.1.1/ray-operator/config/samples/ray-cluster.autoscaler.yaml for RayCluster. Just added `kueue.x-k8s.io/queue-name` label, `suspend` and `shutdownAfterJobFinishes`.

**Comment by mimowo** [comment]
Are the new examples working with RayOperator `<v1.1.0`? Do we support ray-operator `<v1.1.0`?

**Comment by mimowo** [comment]
I don't think the questions are blocking though. It is better to have an example that works on new version rather than old :)

**Comment by mbobrovskyi** [comment]
@mimowo I tested with kuberay v1.0.0 and it's working fine.

**Comment by mimowo** [comment]
> @mimowo I tested with kuberay v1.0.0 and it's working fine.

Thanks for checking.
/lgtm
/approve
/cherry-pick website

**Comment by mimowo** [comment]
I consulted with @mbobrovskyi and there might be still some issue with the examples after all. Let's hold until clarified.

**Review by mimowo — COMMENTED** [review]
/lgtm
/hold cancel
/cherry-pick website

**Comment by mimowo** [comment]
> I consulted with @mbobrovskyi and there might be still some issue with the examples after all. Let's hold until clarified.

Changes done since then:
- the snippet embedded in the docs still contained old version of the Ray image
- the docs used `local-queue`, so we update to `user-queue` for consistency with other pages
- provide a link to the original source of the examples

**Pull request merged**
