### PR TITLE
TAS: cleanups after merging main PRs

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

To address non-blocking review remarks for the main PRs:
- https://github.com/kubernetes-sigs/kueue/pull/3266 (one remark done here about Predicate)
- https://github.com/kubernetes-sigs/kueue/pull/3256 (all other remarks)

#### Which issue(s) this PR fixes:

Part of #2724 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Thanks.
/lgtm
/approve
/hold for @PBundyra

**Comment by PBundyra** [comment]
LGTM, I will hold until the final changes to tests are made

**Comment by mimowo** [comment]
> LGTM, I will hold until the final changes to tests are made

should be done now, PTAL

**Comment by PBundyra** [comment]
Thank you!
/hold cancel

**Pull request merged**
