### PR TITLE
[website] Updated RayJob Documentation

### PR DESCRIPTION
**Pull request by vicentefb**
Add one of the following kinds:
/kind documentation

#### What this PR does / why we need it:

Updates RayJob documentation

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?

```release-note
RayJob integration is enabled by default, updated its documentation to reflect this
```

### CODE REVIEW

**Comment by vicentefb** [comment]
cc @andrewsykim @astefanutti

**Review by astefanutti — APPROVED** [review]
LGTM, thanks!

**Comment by mimowo** [comment]
thanks
/lgtm
/assign @tenzen-y @alculquicondor

**Review by tenzen-y — COMMENTED** [review]
In the past, frameworks were disabled in default due to some implementation issues.
So, documentations for other frameworks have the same explained in the "Before you begin" section.

So, can you update the documents for other frameworks as well?

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
NONE
```

In release-0.5, we have already enabled all integrations: https://github.com/kubernetes-sigs/kueue/blob/a60e5f782f889f0436a5e8d718a42e31aa2e153a/config/components/manager/controller_manager_config.yaml#L31-L41 

/cherry-pick website

**Pull request merged**
