### PR TITLE
Skip invalid fswatch tests on Mac OS.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
Some tests for fswatch not working on Mac OS due to errors on fsnotify (https://github.com/fsnotify/fsnotify/issues/636 and https://github.com/fsnotify/fsnotify/issues/637). It's not critical to test it on MacOS, so we can skip it for now until it's fixed on external library.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Is this still a draft?

**Comment by mbobrovskyi** [comment]
Ready for review

**Review by trasc — COMMENTED** [review]
/lgtm

**Review by alculquicondor — COMMENTED** [review]
/approve

**Pull request merged**
