### PR TITLE
[kjobctl] Add local queue validation

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:

Adds validation to check that localqueue exists  and the flag to skip the validation.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/lgtm

Thanks!

**Comment by mimowo** [comment]
/lgtm
/approve
/hold 
in case @mwielgus has some comments

**Pull request merged**
