### PR TITLE
Remove default namespace

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
To fix deployment of the visibility API

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Tested e2e manually

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
What is the reason to remove the namespace?

**Comment by trasc** [comment]
> fix deployment of the visibility API

How about bringing https://github.com/kubernetes-sigs/kueue/blob/main/config/default/role_binding_visibility_transformer.yaml into config/visibility?

**Comment by PBundyra** [comment]
> > fix deployment of the visibility API
> 
> How about bringing https://github.com/kubernetes-sigs/kueue/blob/main/config/default/role_binding_visibility_transformer.yaml into config/visibility?

Thanks @trasc, that's better idea

**Pull request merged**
