### PR TITLE
bump to golang 1.22

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Bump golang to 1.22.
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Testing this right now. https://github.com/kubernetes-sigs/jobset/pull/471 is open but failing for some infrastructure issues.

Want to confirm if its limited to image.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
+1
Actually, I discussed this at https://github.com/kubernetes-sigs/kueue/pull/1872#issuecomment-2010861941.

**Comment by kannon92** [comment]
Okay. I'll open a test-infra PR to add golang 1.22.

**Comment by kannon92** [comment]
Opened https://github.com/kubernetes/test-infra/pull/32301

**Comment by kannon92** [comment]
/hold cancel

CI looks good to go.

**Pull request merged**
