### PR TITLE
KEP: Kueue kubectl plugin

### PR DESCRIPTION
**Pull request by yaroslava-serdiuk**
#### What type of PR is this?
KEP
/kind documentation

#### What this PR does / why we need it:
We want to improve user experience with kueue.

#### Which issue(s) this PR fixes:
Related to https://github.com/kubernetes-sigs/kueue/issues/487, there is already a kep for this issue #977.

### CODE REVIEW

**Comment by yaroslava-serdiuk** [comment]
/assign @vsoch 
@vsoch can you please take a look?

**Comment by vsoch** [comment]
Sorry - are you taking the work that I did (reference https://github.com/kubernetes-sigs/kueue/pull/977) and putting your commit on it? And asking me to help you debug your PR issues? it's one thing to take another's work and extend the commit, but it's another (immoral) step to take it and tag it as your own. That is really inappropriate, imho.

Ping @alculquicondor this is not OK with me.

**Comment by yaroslava-serdiuk** [comment]
> Sorry - are you taking the work that I did (reference #977) and putting your commit on it? And asking me to help you debug your PR issues? it's one thing to take another's work and extend the commit, but it's another (immoral) step to take it and tag it as your own. That is really inappropriate, imho.
> 
> Ping Aldo Culquicondor this is not OK with me.

This is definitely wasn't my intend. It seems to me that the issue #487 is not progressing and I would like to collaborate since you've already have #977 to make a progress on the issue. I processed the issue on my own and asking your point of view (review).

**Comment by yaroslava-serdiuk** [comment]
@vsoch The issue itself is linking your PR, but I updated PR's description to mention it here as well. Apologize to not mention it at the first place.

**Comment by alculquicondor** [comment]
/close

@vsoch I'm sorry for the miscommunication from my side.

We want to make progress on the CLI while avoiding any problems around the missing CLA from your organization. Hence why this PR starts from scratch, with a minimal scope.

However, as discussed offline, a path forward is to take #977 as-is and iterate in follow up PRs.

**Pull request closed without merging**
