### PR TITLE
Set `AS` to uppercase in Dockerfile  to avoid FromAsCasing warning.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Set `AS` to uppercase in Dockerfile  to avoid FromAsCasing warning.

#### Which issue(s) this PR fixes:

Fixes #

https://docs.docker.com/reference/build-checks/from-as-casing/

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by mszadkow — COMMENTED** [review]
lgtm
what about 2 other Dockerfiles

**Comment by mbobrovskyi** [comment]
Good point. Thanks.

**Review by trasc — COMMENTED** [review]
/lgtm

**Review by tenzen-y — COMMENTED** [review]
/approve

**Pull request merged**
