### PR TITLE
Helm: Add Mutating WebhookConfigurations for the AdmissionCheck, RayJob and JobSet

### PR DESCRIPTION
**Pull request by B1F030**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
This PR aims to sync the [webhook.yaml](https://github.com/kubernetes-sigs/kueue/blob/main/charts/kueue/templates/webhook/webhook.yaml) with [manifest.yaml](https://github.com/kubernetes-sigs/kueue/blob/main/config/components/webhook/manifests.yaml) manually first.
Only after those two files in the same sequence, we can push forward to write a [script](https://github.com/kubernetes-sigs/kueue/blob/main/hack/update-helm.sh), and sync the webhook config automatically.
#### Which issue(s) this PR fixes:

part of #1560

#### Does this PR introduce a user-facing change?

```release-note
Add Mutating WebhookConfigurations for the AdmissionCheck, RayJob, and JobSet
```

### CODE REVIEW

**Comment by mimowo** [comment]
Can you explain in the PR description what were the steps to do the sync? In particular, is it manual process or you run some command, or a combination on manual or automatic?

**Comment by B1F030** [comment]
> Can you explain in the PR description what were the steps to do the sync? In particular, is it manual process or you run some command, or a combination on manual or automatic?

OK. I'm trying to sync the [webhook.yaml](https://github.com/kubernetes-sigs/kueue/blob/main/charts/kueue/templates/webhook/webhook.yaml) with [manifest.yaml](https://github.com/kubernetes-sigs/kueue/blob/main/config/components/webhook/manifests.yaml).
Because if we want to use a script to sync webhook config automatically, we need to make those two files in a same sequence first, so that the pull-kueue-verify-main test can pass.

After this PR merged, I can keep push forward to write the script in #1560.

**Review by tenzen-y — COMMENTED** [review]
I meant that we want to work only on adding missing webhookConfigurations (admissionCheck, jobset and rayjob) without any ordering changes in the previous comment:

> Can we work on fixing this webhook configuration in another PR since we should cherry-pick this hotfix to release-0.5?

Regarding ordering changes, we can work in #1560.

**Comment by tenzen-y** [comment]
/release-note

```release-note
Add Mutating WebhookConfigurations for the AdmissionCheck, RayJob and JobSet
```

**Comment by tenzen-y** [comment]
/release-note

```release-note-edit
Add Mutating WebhookConfigurations for the AdmissionCheck, RayJob and JobSet
```

**Comment by B1F030** [comment]
> Regarding ordering changes, we can work in #1560.

Oh, I see. That sounds resonable to me.

**Review by tenzen-y — COMMENTED** [review]
@B1F030 Can you update the PR description?
/lgtm
/approve
/cherry-pick release-0.5

**Comment by B1F030** [comment]
> @B1F030 Can you update the PR description?

Done.

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Add Mutating WebhookConfigurations for the AdmissionCheck, RayJob, and JobSet to helm charts
```

**Pull request merged**
