### PR TITLE
Fix should admit workloads after change queue-name if AvailableReplicas = 0 test.

### LINKED ISSUE #3626: [Flaky E2E] Deployment should admit workloads after change queue-name if AvailableReplicas = 0
**What happened**:
End To End Suite: kindest/node:v1.28.9: [It] Deployment should admit workloads after change queue-name if AvailableReplicas = 0

```
{Expected success, but got an error:
    <*errors.StatusError | 0xc000996960>: 
    workloads.kueue.x-k8s.io "pod-deployment-6d47d84db6-89fv2-c7e95" not found
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "workloads.kueue.x-k8s.io \"pod-deployment-6d47d84db6-89fv2-c7e95\" not found",
            Reason: "NotFound",
            Details: {
                Name: "pod-deployment-6d47d84db6-89fv2-c7e95",
                Group: "kueue.x-k8s.io",
                Kind: "workloads",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    } failed [FAILED] Expected success, but got an error:
    <*errors.StatusError | 0xc000996960>: 
    workloads.kueue.x-k8s.io "pod-deployment-6d47d84db6-89fv2-c7e95" not found
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "workloads.kueue.x-k8s.io \"pod-deployment-6d47d84db6-89fv2-c7e95\" not found",
            Reason: "NotFound",
            Details: {
                Name: "pod-deployment-6d47d84db6-89fv2-c7e95",
                Group: "kueue.x-k8s.io",
                Kind: "workloads",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/deployment_test.go:202 @ 11/25/24 10:17:18.844
}
```

**What you expected to happen**:
No errors.

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3615/pull-kueue-test-e2e-main-1-28/1860988860012433408

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
/kind bug
/kind failing-test
/kind flake

#### Which issue(s) this PR fixes:

Fixes #3626

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
Please explain why this fixes the issue (not obvious to me).

**Comment by mbobrovskyi** [comment]
> Please explain why this fixes the issue (not obvious to me).

Sometimes it happens that new pods created but previous not deleted yet. We are waiting for old pods deleted before check that new are admitted.

**Comment by mimowo** [comment]
/lgtm
/approve
Ok, I'm not sure this is the only problem here, but it will be better to wait for deletion of old pods, so let's give it a try.

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-e2e-main-1-28 pull-kueue-test-e2e-main-1-29 pull-kueue-test-e2e-main-1-30 pull-kueue-test-e2e-main-1-31

1/5

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-e2e-main-1-28 pull-kueue-test-e2e-main-1-29 pull-kueue-test-e2e-main-1-30 pull-kueue-test-e2e-main-1-31

2/5

**Comment by mbobrovskyi** [comment]
/test pull-kueue-test-e2e-main-1-28 pull-kueue-test-e2e-main-1-29 pull-kueue-test-e2e-main-1-30 pull-kueue-test-e2e-main-1-31

4/5

**Pull request merged**
