### PR TITLE
Automated cherry pick of #3770: Deactivate ClusterQueue if there is no Topology

### PR DESCRIPTION
**Pull request by mimowo**
Cherry pick of #3770 on release-0.9.

#3770: Deactivate ClusterQueue if there is no Topology

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
TAS: The CQ referencing a Topology is deactivated if the topology does not exist.
```

### CODE REVIEW

**Comment by mimowo** [comment]
I have adjusted some conflicts manually:
- in the tas/resource_flavor.go - due to the "tolerations" support added for 0.10 - we could actually consider it a bug in 0.9 too, but that is a separate issue
- in the test/integration/tas/tas_test.go - due to the new functions to create default topologies - I don't use these functions on the cherry-pick

**Comment by mimowo** [comment]
One more change required is related to https://github.com/kubernetes-sigs/kueue/pull/3744. I think I would actually prefer to include the cherry-picks of https://github.com/kubernetes-sigs/kueue/pull/3744 and https://github.com/kubernetes-sigs/kueue/pull/3769. They are risk-free as they are test only, and they will help to cherry-pick future PRs.

**Comment by mimowo** [comment]
/hold 
I will rebase after the other PRs are cherry-picked

**Comment by mimowo** [comment]
Rebased now.

**Comment by PBundyra** [comment]
/lgtm 
Thanks!

**Comment by mimowo** [comment]
/approve
FYI the cherry-pick process was initiated by another maintainer in https://github.com/kubernetes-sigs/kueue/pull/3770#issuecomment-2537902711

**Pull request merged**
