### PR TITLE
TAS: fix panic in e2e test when parallelism < completions

### LINKED ISSUE #3620: [TAS Flaky test] TopologyAwareScheduling for Job when Creating a Job Should allow to run a Job with parallelism < completions
**What happened**:

The test flaked on unrelated branch: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3528/pull-kueue-test-tas-e2e-main/1860964874574630912

**What you expected to happen**:

No random failures

**How to reproduce it (as minimally and precisely as possible)**:

Repeat on CI

**Anything else we need to know?**:

```
TopologyAwareScheduling for Job when Creating a Job Should allow to run a Job with parallelism < completions
/home/prow/go/src/sigs.k8s.io/kueue/test/e2e/tas/job_test.go:228
  STEP: verify the workload "e2e-tas-job-nwd4c/job-test-job-3ba63" gets TopologyAssignment becomes finished @ 11/25/24 08:42:28.731
  [PANICKED] in [It] - /home/prow/go/src/sigs.k8s.io/kueue/vendor/github.com/onsi/gomega/internal/async_assertion.go:321 @ 11/25/24 08:42:28.783
• [PANICKED] [1.464 seconds]
TopologyAwareScheduling for Job when Creating a Job [It] Should allow to run a Job with parallelism < completions
/home/prow/go/src/sigs.k8s.io/kueue/test/e2e/tas/job_test.go:228
  [PANICKED] Test Panicked
  In [It] at: /home/prow/go/src/sigs.k8s.io/kueue/vendor/github.com/onsi/gomega/internal/async_assertion.go:321 @ 11/25/24 08:42:28.783
  runtime error: invalid memory address or nil pointer dereference
  Full Stack Trace
    github.com/onsi/gomega/internal.(*AsyncAssertion).buildActualPoller.func3.1()
    	/home/prow/go/src/sigs.k8s.io/kueue/vendor/github.com/onsi/gomega/internal/async_assertion.go:321 +0x186
    panic({0x18d6140?, 0x2bfe7f0?})
    	/usr/local/go/src/runtime/panic.go:785 +0x132
    sigs.k8s.io/kueue/test/e2e/tas.init.func1.3.6.1.1({0x1df0de0, 0xc000467c40})
    	/home/prow/go/src/sigs.k8s.io/kueue/test/e2e/tas/job_test.go:248 +0xcf
    reflect.Value.call({0x1829e00?, 0xc0006125d0?, 0xc0001a5738?}, {0x1b06e7c, 0x4}, {0xc000012f78, 0x1, 0x0?})
    	/usr/local/go/src/reflect/value.go:581 +0xca6
    reflect.Value.Call({0x1829e00?, 0xc0006125d0?, 0xc000467c40?}, {0xc000012f78?, 0xc0006125d0?, 0x1829e00?})
    	/usr/local/go/src/reflect/value.go:365 +0xb9
    github.com/onsi/gomega/internal.(*AsyncAssertion).buildActualPoller.func3()
    	/home/prow/go/src/sigs.k8s.io/kueue/vendor/github.com/onsi/gomega/internal/async_assertion.go:325 +0x11f
    github.com/onsi/gomega/internal.(*AsyncAssertion).match(0xc0002[610](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3528/pull-kueue-test-tas-e2e-main/1860964874574630912#1:build-log.txt%3A610)a0, {0x1dd6f90, 0x2c6dd20}, 0x1, {0x0, 0x0, 0x0})
    	/home/prow/go/src/sigs.k8s.io/kueue/vendor/github.com/onsi/gomega/internal/async_assertion.go:398 +0x179
    github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0xc0002610a0, {0x1dd6f90, 0x2c6dd20}, {0x0, 0x0, 0x0})
    	/home/prow/go/src/sigs.k8s.io/kueue/vendor/github.com/onsi/gomega/internal/async_assertion.go:145 +0x86
    sigs.k8s.io/kueue/test/e2e/tas.init.func1.3.6.1()
    	/home/prow/go/src/sigs.k8s.io/kueue/test/e2e/tas/job_test.go:250 +0x11f
    sigs.k8s.io/kueue/test/e2e/tas.init.func1.3.6()
    	/home/prow/go/src/sigs.k8s.io/kueue/test/e2e/tas/job_test.go:245 +0x991
```

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind flake

#### Which issue(s) this PR fixes:

Fixes #3620

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @PBundyra

**Comment by mimowo** [comment]
/test pull-kueue-test-integration-main
unrelated, opened issue: https://github.com/kubernetes-sigs/kueue/issues/3633

**Comment by mbobrovskyi** [comment]
/lgtm
Thanks!

**Comment by mbobrovskyi** [comment]
/retest

Due to know issue.

**Pull request merged**
