### PR TITLE
Initial .openvex setup

### PR DESCRIPTION
**Pull request by psschwei**
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>

 `#SecuritySlam`

#### What this PR does / why we need it:

This PR adds an initial .openvex directory to the project.

#### Which issue(s) this PR fixes:

This commit is part of the December 2023 Security Slam. 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
For context @alculquicondor  -> https://docs.google.com/document/d/1TLahqW6OpWQXbaVJ-SR8z-o0yLSoGKYTHxPU0PyyjXo/edit

**Review by ArangoGutierrez — APPROVED** [review]
This RP is part of the SecuritySlam organised by CNCF
@alculquicondor @tenzen-y

**Comment by alculquicondor** [comment]
IIUC, the file is a placeholder and a follow PR will introduce the actual logic?

/approve
Leaving LGTM to @ArangoGutierrez

**Comment by psschwei** [comment]
> IIUC, the file is a placeholder and a follow PR will introduce the actual logic?

Yes, that's correct. Follow up is in #1465

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
