### PR TITLE
[test][integration][ray] Fix cleanup for flavors and priority-class

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
[test][integration][ray] Fix cleanup for flavors and priority-class

#### Which issue(s) this PR fixes:

Relates to https://github.com/kubernetes-sigs/kueue/issues/2993

#### Special notes for your reviewer:

The standard go defer is used since 
- https://github.com/onsi/ginkgo/issues/1284

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/lgtm

Thanks!

**Comment by mimowo** [comment]
/approve
Thanks

**Pull request merged**
