### PR TITLE
Update administer_cluster_quotas.md

### PR DESCRIPTION
**Pull request by BinL233**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
.spec.clusterQueue in LocalQueue does not match .metadata.name in ClusterQueue
Changed clusterQueue: "cluster-total" -> clusterQueue: "cluster-queue"

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by BinL233** [comment]
cc @kerthcet

**Review by kerthcet — COMMENTED** [review]
/lgtm
approve
/release-note-none

**Pull request merged**
