### PR TITLE
Bump github.com/golangci/golangci-lint from 1.59.1 to 1.60.1 in /hack/internal/tools

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
I added a commit for fixing lint errors to https://github.com/kubernetes-sigs/kueue/pull/2852.

```go
cmd/kueuectl/app/list/list_clusterqueue.go:206:5: S1009: should omit nil check; len() for []bool is defined as zero (gosimple)
        if o.Active == nil || len(o.Active) == 0 {
           ^
pkg/util/testing/client.go:103:39: printf: non-constant format string in call to (*sigs.k8s.io/kueue/pkg/util/testing.EventRecorder).Eventf (govet)
        tr.Eventf(object, eventType, reason, message)
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
Resolved conflicts.

**Comment by mbobrovskyi** [comment]
/cherry-pick release-0.8

Due to we have an error with linter https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/3052/pull-kueue-verify-release-0-8/1835582478505480192.

**Pull request merged**
