### PR TITLE
[kjobctl] Remove the unused skip-priority-workload flag.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Remove the unused skip-priority-workload flag.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Follow up for https://github.com/kubernetes-sigs/kueue/pull/3537#discussion_r1846155674.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
cc: @mwysokin

**Comment by mimowo** [comment]
cc @mwysokin

**Review by mwysokin — APPROVED** [review]
LGTM 🖖

**Pull request merged**
