### PR TITLE
leaderElectionID should be empty when leaderElection is disabled

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind feature
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Thanks for creating this! LGTM

BTW, it might be better to merge this before merging #399.

**Comment by kerthcet** [comment]
@tenzen-y will you mind to add a LGTM, I think it's approved.

**Comment by tenzen-y** [comment]
> @tenzen-y will you mind to add a LGTM, I think it's approved.

@kerthcet Thanks for taking this up!
/lgtm

**Comment by kerthcet** [comment]
Thanks

**Pull request merged**
