### PR TITLE
feat: update ray-operator to v0.6.0

### LINKED ISSUE #1155: [Ray] Update Go Module version
**What would you like to be added**:
We should upgrade go module version for kuberay.

**Why is this needed**:
Our version is outdated. However, the dependabot could not update the version.

https://github.com/kubernetes-sigs/kueue/blob/f9273bef71e136c0eed659ae19fce178512a6f6a/go.mod#L16
https://github.com/ray-project/kuberay/releases/tag/v0.6.0

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

### PR DESCRIPTION
**Pull request by lowang-bh**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Fixes #1155

#### Does this PR introduce a user-facing change?

```release-note
update ray-operator to v0.6.0
```

### CODE REVIEW

**Comment by trasc** [comment]
/ok-to-test

It's nice to see that kuberay has ray-operator tags now.

**Review by trasc — COMMENTED** [review]
/lgtm

**Comment by trasc** [comment]
/cc @alculquicondor @tenzen-y 
for approve

**Review by tenzen-y — COMMENTED** [review]
/approve

**Pull request merged**
