### PR TITLE
Reformat tables.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Reformat tables.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/approve
/lgtm

**Comment by mimowo** [comment]
/cherry-pick website
So that other cherry-picks to website don't run into conflicts.

**Comment by mimowo** [comment]
@mbobrovskyi could you prepare a manual cherry-pick?

**Comment by mbobrovskyi** [comment]
Should we rebase this branch before https://github.com/kubernetes-sigs/kueue/pull/2909? It will change nothing on the site.

**Comment by mimowo** [comment]
I don't think https://github.com/kubernetes-sigs/kueue/pull/2909 is planned for cherry-picking (it is a new feature impacting API)

**Pull request merged**
