### PR TITLE
Remove v1alpha1 visibility API

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Remove the v1alpha1 Visibility API.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
As we discussed here https://github.com/kubernetes-sigs/kueue/pull/3008#issuecomment-2341838660 we should remove v1alpha1 visibility API on 0.10 version.

#### Does this PR introduce a user-facing change?

```release-note
Removed the v1alpha1 Visibility API.

ACTION REQUIRED: The v1alpha1 Visibility API is deprecated. Please use v1beta1 instead.
```

### CODE REVIEW

**Comment by trasc** [comment]
I think `config/components/visibility/apiservice_v1alpha1.yaml` should be removed also. 
Check the documentation, there may be other references to v1alpha1 there.

**Comment by mimowo** [comment]
I will leave the first pass to @PBundyra

**Comment by PBundyra** [comment]
/lgtm
Thanks!

**Pull request merged**
