### PR TITLE
[fixed] Bump github.com/onsi/gomega from 1.34.0 to 1.34.1

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fixed-up version of #2756 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

Thanks!

Do you know why dependabot failed to update this module?

**Comment by trasc** [comment]
> Do you know why dependabot failed to update this module?

At least in the configuration we are using it's only updating one go.mod at a time, and on rare occasions we need to bump some modules at the same time  (boat in tools and in the main go.mod).

**Comment by tenzen-y** [comment]
> > Do you know why dependabot failed to update this module?
> 
> At least in the configuration we are using it's only updating one go.mod at a time, and on rare occasions we need to bump some modules at the same time (boat in tools and in the main go.mod).

That makes sense. Thanks for investigating that!

**Pull request merged**
