### PR TITLE
Added kueuectl-docs generator.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Added kueuectl-docs generator.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Added details documentation for kubectl-kueue plugin.
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/hold 

Wait for https://github.com/kubernetes/test-infra/pull/32983/files.

**Comment by mbobrovskyi** [comment]
/unhold

Due to https://github.com/kubernetes/test-infra/pull/32983 done.

**Comment by mbobrovskyi** [comment]
/assign @alculquicondor 

Bumped gcb-docker-gcloud to oldest version.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
