### PR TITLE
Update latest version to v0.6.1

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind documentation

#### Which issue(s) this PR fixes:

Part of #1842

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Should we update https://github.com/kubernetes-sigs/kueue/blob/fd70a0bf2e75e3639a0713fee12ddf3b86af51d0/SECURITY-INSIGHTS.yaml as well?

**Comment by alculquicondor** [comment]
oh yes, fixed

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm

**Pull request merged**
