### PR TITLE
Runs the race detector on integration tests.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Runs the race detector and emits any detected race conditions as the suite runs. If any are detected the suite is marked as failed.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Follow up for https://github.com/kubernetes-sigs/kueue/pull/2460#issuecomment-2182995768.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by mszadkow — APPROVED** [review]
lgtm - let's just fix the tests ;)

**Comment by mbobrovskyi** [comment]
Yes, working on it on #2471.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
