### PR TITLE
Replace time.Now() with clock.Now() in pkg/core

### PR DESCRIPTION
**Pull request by TusharMohapatra07**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Replaces `time.Now()` to use the Now() function present inside `clock` package.

#### Which issue(s) this PR fixes:
Part of #3380

#### Special notes for your reviewer:
This PR is work-in-progress. 

```release-note
NONE
```

### CODE REVIEW

**Review by mbobrovskyi — COMMENTED** [review]
What about this one https://github.com/kubernetes-sigs/kueue/blob/9da7a73d8f9ff121996279056f03b950131df89a/pkg/controller/core/clusterqueue_controller.go#L761?

**Comment by TusharMohapatra07** [comment]
@mbobrovskyi done

**Comment by mbobrovskyi** [comment]
/lgtm
Thanks!

**Review by mimowo — COMMENTED** [review]
/approve

**Pull request merged**
