### PR TITLE
Upgrade envtest k8s version to 1.24

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Test the same version as the API packages

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by tenzen-y** [comment]
This is just a question.
Is there any reason not to use K8s v1.25?

**Comment by alculquicondor** [comment]
I would wait for 1.25.1 at least

**Comment by tenzen-y** [comment]
> I would wait for 1.25.1 at least

sounds good.
Thanks!

**Pull request merged**
