### PR TITLE
Simplify code by removing unnecessary conversions

### PR DESCRIPTION
**Pull request by alexandear**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR removes unnecessary conversions throughout the codebase. Additionally, it enables `unconvert` linter to automatically detect these types of redundancies.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by trasc — COMMENTED** [review]
/lgtm

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
