### PR TITLE
Tighten asserts for PodsReady requeueAt by using a fake clock and jitter=0

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

To make the unit test assert on the requeueAt time precisely, not just using "After".

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

WIP because still testing

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
This is a great refactoring!
Thank you!
/lgtm
/hold
for https://github.com/kubernetes-sigs/kueue/pull/2040

**Comment by tenzen-y** [comment]
/hold cancel

@mimowo Need to rebase this PR.

**Comment by mimowo** [comment]
> @mimowo Need to rebase this PR.

Rebased, PTAL

**Review by tenzen-y — COMMENTED** [review]
Thanks!
/lgtm

**Pull request merged**
