### PR TITLE
Move openapi to visibility directory.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Move openapi to visibility directory. It will allow us to use it on both visibility API versions v1alpha1 and v1beta1.

#### Which issue(s) this PR fixes:

Prepare for #2973

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
I synced with @mbobrovskyi who tested e2e manually that it works after merging the openapi generation for alpha and beta. This approach is also used by kube-aggregator as pointed out by Mike: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/generated/openapi/zz_generated.openapi.go

I think it makes sense, but would like to have another pair of eyes.
/cc @PBundyra

**Comment by PBundyra** [comment]
LGTM

**Comment by mimowo** [comment]
/lgtm
/approve
Thanks

**Pull request merged**
