### PR TITLE
test cleanup: replace equality.DeepEqual by gomega.BeComparableTo

### PR DESCRIPTION
**Pull request by dgrove-oss**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:

Cleanup tests introduced in #3026 as [requested](https://github.com/kubernetes-sigs/kueue/pull/3026#discussion_r1805521518) 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/lgtm

Thanks!

**Comment by mbobrovskyi** [comment]
/retest

Due to known issue https://github.com/kubernetes-sigs/kueue/issues/3051.

**Comment by mimowo** [comment]
/approve
Thanks!

**Comment by tenzen-y** [comment]
Thank you!

**Pull request merged**
