### PR TITLE
[provisionong-AC] Check the limits for used resources.

### LINKED ISSUE #2278: Provisioning Admission Check doesn't consider limits
**What happened**:

In k8s, requests is equal to limits when unset.

However, this check only considers the requests:

https://github.com/kubernetes-sigs/kueue/blob/fab6cfe507a3c91659d93355383f1c98fc7a7635/pkg/controller/admissionchecks/provisioning/controller.go#L419

**What you expected to happen**:

To consider the limits.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #2278

#### Special notes for your reviewer:
Check the containers limits for used resources in provisioning admission check controller.

#### Does this PR introduce a user-facing change?

```release-note
Check the containers limits for used resources in provisioning admission check controller and include them in the ProvisioningRequest as requests
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/lgtm
/approve
/hold
I'm verifying whether this is enough to make ProvisioningRequest work.
Basically, I want to make sure that cluster-autoscaler also honors the limits, and not just the requests.

**Comment by trasc** [comment]
> Please also add the logic of requests=limits when creating the PodTemplates.

done

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Check the containers limits for used resources in provisioning admission check controller and include them in the ProvisioningRequest as requests
```

**Pull request merged**
