### PR TITLE
[kjobctl] Copy labels and annotations from template on builder.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Copy labels and annotations from a template on kjobctl builder. This feature will allow us to set additional annotations and labels (e.g. default kueue localqueue label).

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
/assign @trasc 
@mbobrovskyi should we add a release note given this is tagged as a feature?

**Comment by mbobrovskyi** [comment]
> @mbobrovskyi should we add a release note given this is tagged as a feature?

Not sure, because kjobctl is not a scope of kueue.

**Review by trasc — COMMENTED** [review]
/lgtm

**Review by trasc — COMMENTED** [review]
/lgtm

**Pull request merged**
