### PR TITLE
add: custom annotations on service and deployment

### LINKED ISSUE #1619: Add the possibility to add custom annotations to manager pods via helm chart
**What would you like to be added**:

I would like to be able to add additional annotations to the pod via the helm chart

**Why is this needed**:

In order to be able to enable automatic scraping via prometheus (without the CRDs) additional annotations are needed:

```
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
```

Could be a potential fix for #663 as well (because port 8080 is the unprotected port for metrics)

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

### PR DESCRIPTION
**Pull request by tozastation**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

I have changed to be able to set Custom Annotations on Service resources and Deployment's Pod resources via Helm Chart.

#### Which issue(s) this PR fixes:

Fixes #1619 

#### Does this PR introduce a user-facing change?

```release-note
add support allow configuration of custom annotations on Service and Deployment's Pod
```

### CODE REVIEW

**Review by trasc — COMMENTED** [review]
Overall LGTM.

@tozastation do you have a specific use-case for this? Maybe we can document it.

**Comment by tozastation** [comment]
@trasc 
thanks for reviewing!

In Prometheus, we can use Relabel Config to define the scraping target without using the Service Monitor.
For this configuration, we can use the metadata.annotations of the Service or Pod.

The following annotations are available by default in Prometheus' Helm Chart.
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L918

```yaml
prometheus.io/path: /metrics
prometheus.io/port: '8080'
prometheus.io/scrape: 'true'
etc...
```

---

Implementing this with the proposed changes will result in the following

example (values.yaml): Pod Annotations
```yaml
controllerManager:
  manager:
    podAnnotations:
      prometheus.io/path: /metrics
      prometheus.io/port: '8080'
      prometheus.io/scrape: 'true'
```

example (values.yaml): Service Annotations
```yaml
metricsService:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8443'
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: https
```

※ Service Scaraping requires the following additions to the Prometheus configuration.
Follows the Service Monitor configuration: https://github.com/kubernetes-sigs/kueue/blob/main/charts/kueue/templates/prometheus/monitor.yaml

```yaml
scrape_configs:
  - tls_config:
        insecure_skip_verify: true
    authorization:
        credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
```

**Comment by trasc** [comment]
Thanks, 

/lgtm

**Review by tenzen-y — COMMENTED** [review]
I'm wondering if we need to update https://github.com/kubernetes-sigs/kueue/blob/a0290b3f67770b34b6169bcd10e74e07ad831945/hack/update-helm.sh as well.

@tozastation What happens if you perform `make update-helm`?

**Comment by tozastation** [comment]
@tenzen-y 

thanks

The following is the result of the execution.
I checked that there are no git diffs or newly generated files.

```sh
❯ make update-helm
/Users/tozastation/ghq/github.com/tozastation/kueue/bin/controller-gen \
                crd:generateEmbeddedObjectMeta=true output:crd:artifacts:config=config/components/crd/bases\
                paths="./apis/..."
/Users/tozastation/ghq/github.com/tozastation/kueue/bin/controller-gen \
                rbac:roleName=manager-role output:rbac:artifacts:config=config/components/rbac\
                webhook output:webhook:artifacts:config=config/components/webhook\
                paths="./pkg/controller/...;./pkg/webhooks/...;./pkg/util/cert/...;./pkg/visibility/..."
go: downloading github.com/mikefarah/yq/v4 v4.34.1
go: downloading gopkg.in/op/go-logging.v1 v1.0.0-20160211212156-b2cb9fa56473
go: downloading github.com/elliotchance/orderedmap v1.5.0
go: downloading github.com/a8m/envsubst v1.4.2
go: downloading github.com/alecthomas/participle/v2 v2.0.0
go: downloading github.com/goccy/go-yaml v1.11.0
go: downloading github.com/pelletier/go-toml/v2 v2.0.7
SED=/opt/homebrew/opt/gnu-sed/libexec/gnubin/sed ./hack/update-helm.sh
```

**Comment by tenzen-y** [comment]
> @tenzen-y 
> 
> 
> 
> thanks
> 
> 
> 
> The following is the result of the execution.
> 
> I checked that there are no git diffs or newly generated files.
> 
> 
> 
> ```sh
> 
> ❯ make update-helm
> 
> /Users/tozastation/ghq/github.com/tozastation/kueue/bin/controller-gen \
> 
>                 crd:generateEmbeddedObjectMeta=true output:crd:artifacts:config=config/components/crd/bases\
> 
>                 paths="./apis/..."
> 
> /Users/tozastation/ghq/github.com/tozastation/kueue/bin/controller-gen \
> 
>                 rbac:roleName=manager-role output:rbac:artifacts:config=config/components/rbac\
> 
>                 webhook output:webhook:artifacts:config=config/components/webhook\
> 
>                 paths="./pkg/controller/...;./pkg/webhooks/...;./pkg/util/cert/...;./pkg/visibility/..."
> 
> go: downloading github.com/mikefarah/yq/v4 v4.34.1
> 
> go: downloading gopkg.in/op/go-logging.v1 v1.0.0-20160211212156-b2cb9fa56473
> 
> go: downloading github.com/elliotchance/orderedmap v1.5.0
> 
> go: downloading github.com/a8m/envsubst v1.4.2
> 
> go: downloading github.com/alecthomas/participle/v2 v2.0.0
> 
> go: downloading github.com/goccy/go-yaml v1.11.0
> 
> go: downloading github.com/pelletier/go-toml/v2 v2.0.7
> 
> SED=/opt/homebrew/opt/gnu-sed/libexec/gnubin/sed ./hack/update-helm.sh
> 
> ```

Oh, I see. Thank you for checking!
/approve

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Helm: Allow configuration of custom annotations on Service and Deployment's Pod
```

**Pull request merged**
