### PR TITLE
Fix: kueue-manager-role can not update topologies

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?

Report errors like this:
```
{"level":"error","ts":"2024-12-26T05:32:34.012480568Z","caller":"controller/controller.go:316","msg":"Reconciler error","controller":"tas-topology-controller","controllerGroup":"kueue.x-k8s.io","controllerKind":"Topology","Topology":{"name":"default"},"namespace":"","name":"default","reconcileID":"276f685c-1d43-4d07-bf1a-2a062eee43bf","error":"topologies.kueue.x-k8s.io \"default\" is forbidden: User \"system:serviceaccount:kueue-system:kueue-controller-manager\" cannot update resource \"topologies\" in API group \"kueue.x-k8s.io\" at the cluster scope","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224"}
```

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/lgtm
Thanks!

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
/approve

**Comment by mimowo** [comment]
/release-note-edit
```release-note
Fix the permission bug which prevented adding the `kueue.x-k8s.io/resource-in-use` finalizer to the Topology objects, resulting in repeatedly logged errors.
```

**Pull request merged**
