### PR TITLE
release lock as soon as finish using

### LINKED ISSUE #1098: Release the lock as soon as possible when computing the snapashot for CQ visibility
This is a follow up for review remark: https://github.com/kubernetes-sigs/kueue/pull/1069/files/3b1f7c19d16b67a267d30ba8945ae1a3bb2b501e#r1319099583

**What would you like to be cleaned**:

The sort operation can be done once the lock is released.

**Why is this needed**:

Improve performance of Kueue by reducing lock contention.

### PR DESCRIPTION
**Pull request by lowang-bh**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #1098

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
It looks ok, but I have a slight concern, that if there is a panic thrown between Lock and Unlock the lock will remain. It is usually not an issue if the code in between is very simple (sort of like here), but I have a feeling this code may evolve.

I would suggest to wrap the code into a function call and use Lock / defer Unlock pattern for the duration of the function. This could be either in a named function, like "snapshotQueueData", or an unnamed, like we do for example here: https://github.com/kubernetes-sigs/kueue/blob/0ee53de7f2f10ea7eb129f34c143126bdc002ee1/client-go/informers/externalversions/factory.go#L148-L159.

**Review by alculquicondor — COMMENTED** [review]
/approve
/lgtm

**Comment by alculquicondor** [comment]
/lgtm cancel

I'll leave the LGTM to @mimowo

**Comment by tenzen-y** [comment]
> It looks ok, but I have a slight concern, that if there is a panic thrown between Lock and Unlock the lock will remain. It is usually not an issue if the code in between is very simple (sort of like here), but I have a feeling this code may evolve.
> 
> I would suggest to wrap the code into a function call and use Lock / defer Unlock pattern for the duration of the function. This could be either in a named function, like "snapshotQueueData", or an unnamed, like we do for example here:
> 
> https://github.com/kubernetes-sigs/kueue/blob/0ee53de7f2f10ea7eb129f34c143126bdc002ee1/client-go/informers/externalversions/factory.go#L148-L159
> 
> .

It sounds reasonable. The current implementation is a bit dangerous.

**Comment by lowang-bh** [comment]
> It sounds reasonable. The current implementation is a bit dangerous.

Have updated.

**Review by mimowo — COMMENTED** [review]
/lgtm

**Pull request merged**
