### PR TITLE
Sort labels and annotations.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Sort labels and annotations.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
@mbobrovskyi should we be cherry-picking this PR to website? If so, then prepare it manually

**Comment by mbobrovskyi** [comment]
I think no. This is new feature.

**Pull request merged**
