### PR TITLE
[dep] Use jobset v0.5.0

### PR DESCRIPTION
**Pull request by trasc**
#### What this PR does / why we need it:
[dep] Use jobset v0.5.0

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by trasc** [comment]
/cc @tenzen-y 
@mimowo , @tenzen-y  can you have a quick look?

**Comment by tenzen-y** [comment]
> /test pull-kueue-test-e2e-main-1-28 /test pull-kueue-test-e2e-main-1-27

@trasc What is the reason that you restarted some CI jobs?

**Comment by trasc** [comment]
> > /test pull-kueue-test-e2e-main-1-28 /test pull-kueue-test-e2e-main-1-27
> 
> @trasc What is the reason that you restarted some CI jobs?

CI-job setup issues https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1984/pull-kueue-test-e2e-main-1-27/1780092894862905344

**Comment by tenzen-y** [comment]
> > > /test pull-kueue-test-e2e-main-1-28 /test pull-kueue-test-e2e-main-1-27
> > 
> > 
> > @trasc What is the reason that you restarted some CI jobs?
> 
> CI-job setup issues https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1984/pull-kueue-test-e2e-main-1-27/1780092894862905344

I see.
/lgtm
/approve

**Pull request merged**
