### PR TITLE
[release-0.5] Fix: remove workload finalizer if workload is finished

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it: 
Cherry-pick of #1523 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Fix a bug in the pod integration that the pod's finalizer won't be removed even though the pod is finished
```

**Comment by alculquicondor** [comment]
/release-note-edit
```
Remove finalizer from Workloads that are orphaned (have no owners).
```

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Remove finalizer from Workloads that are orphaned (have no owners).
```

**Pull request merged**
