### PR TITLE
Revert "Use Patch instead of Update on jobframework."

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Reverts kubernetes-sigs/kueue#2501

#### Which issue(s) this PR fixes:

Part of #2269

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
NONE
```

**Comment by alculquicondor** [comment]
I'll just remove the release note from the previous PR too.

**Comment by tenzen-y** [comment]
Just confirmations. What is the reason for reverting this change?

**Comment by alculquicondor** [comment]
Because Update is strict (fails if resourceVersion is different), but Patch isn't.

#2553 was trying to fix this as a follow-up, but during review too many questions opened up about whether we are preserving the behavior. So I suggested that we revert the whole thing and put the 2 PRs into one.

**Comment by tenzen-y** [comment]
> Because Update is strict (fails if resourceVersion is different), but Patch isn't.
> 
> #2553 was trying to fix this as a follow-up, but during review too many questions opened up about whether we are preserving the behavior. So I suggested that we revert the whole thing and put the 2 PRs into one.

That makes sense. Thank you for the explanations!

**Comment by tenzen-y** [comment]
due to insufficient computing

/retest

**Pull request merged**
