### PR TITLE
Bump go version

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
It enables us to use new packages introduced in go 1.21. It's required to merge [PR#1141](https://github.com/kubernetes-sigs/kueue/pull/1141)

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
/lgtm cancel
we need to sort out the build first

**Comment by trasc** [comment]
If we want to go with the full pr now, yes. But I have my concerns about asking everybody to update their go version.

**Comment by mimowo** [comment]
> If we want to go with the full pr now, yes. But I have my concerns about asking everybody to update their go version.

I see the concern, but OTOH having the new packages for slices and maps, and reduce the toil for code development and reviewing. I guess the update in unavoidable at some point, so not sure what would be the criteria to choose the right moment. wdyt @tenzen-y @alculquicondor ?

**Comment by tenzen-y** [comment]
> If we want to go with the full pr now, yes. But I have my concerns about asking everybody to update their go version.

@trasc, Could you clarify that you're concerned? What concerns do you think when we enforce using Go 1.21 to contributors?

**Comment by mimowo** [comment]
FYI: `Kubernetes is now built with go 1.21.0` https://github.com/kubernetes/kubernetes/pull/118996 from 3 weeks ago.

**Comment by tenzen-y** [comment]
> > If we want to go with the full pr now, yes. But I have my concerns about asking everybody to update their go version.
> 
> @trasc, Could you clarify that you're concerned? What concerns do you think when we enforce using Go 1.21 to contributors?

I'm still waiting for @trasc's comment.

**Review by tenzen-y — COMMENTED** [review]
@PBundyra Also, we need to update golangci-lint since our using version doesn't support Go 1.21.

https://github.com/kubernetes-sigs/kueue/blob/cc7dbcbdad3666b62c8b9341918675f840b0a9c7/Makefile#L273-L275

**Comment by PBundyra** [comment]
> @PBundyra Also, we need to update golangci-lint since our using version doesn't support Go 1.21.
> 
> https://github.com/kubernetes-sigs/kueue/blob/cc7dbcbdad3666b62c8b9341918675f840b0a9c7/Makefile#L273-L275

Done. Thanks

**Comment by trasc** [comment]
> > > If we want to go with the full pr now, yes. But I have my concerns about asking everybody to update their go version.
> > 
> > 
> > @trasc, Could you clarify that you're concerned? What concerns do you think when we enforce using Go 1.21 to contributors?
> 
> I'm still waiting for @trasc's comment.

It's just that some kueue developers might still be using a later go version. For me personally it's ok, especially if the compatibility with golangci-lint is confirmed.

**Comment by tenzen-y** [comment]
> > > > If we want to go with the full pr now, yes. But I have my concerns about asking everybody to update their go version.
> > > 
> > > 
> > > @trasc, Could you clarify that you're concerned? What concerns do you think when we enforce using Go 1.21 to contributors?
> > 
> > 
> > I'm still waiting for @trasc's comment.
> 
> It's just that some kueue developers might still be using a later go version. For me personally it's ok, especially if the compatibility with golangci-lint is confirmed.

I see. I think developers can switch the Go version according to projects. For example, using [goenv](https://github.com/go-nv/goenv).

**Comment by tenzen-y** [comment]
@PBundyra Could you fix CI errors?

**Comment by trasc** [comment]
> @PBundyra Could you fix CI errors?

@tenzen-y it looks like the errors are caused because the test-infra pr is not merged.

**Comment by tenzen-y** [comment]
> Bump go version for kueue jobs kubernetes/test-infra#30806

We merged the PR 🤔 
https://github.com/kubernetes/test-infra/pull/30806

/retest

**Comment by trasc** [comment]
for e2e wi might need to change `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master` with a newer one, but we neee to make sure it's using go 1.21.1

**Comment by trasc** [comment]
> for e2e we might need to change `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master` with a newer one, but we neee to make sure it's using go 1.21.1

`gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230918-570a399623-master` is using `go version go1.21.1 linux/amd64` it should work to fix e2e 

cc: @PBundyra @tenzen-y

**Comment by PBundyra** [comment]
> > for e2e we might need to change `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master` with a newer one, but we neee to make sure it's using go 1.21.1
> 
> `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230918-570a399623-master` is using `go version go1.21.1 linux/amd64` it should work to fix e2e
> 
> cc: @PBundyra @tenzen-y

Thank you, I've already submitted a PR with this:
https://github.com/kubernetes/test-infra/pull/30863

**Comment by tenzen-y** [comment]
@PBundyra Do you use Go 1.21 in your local? Gomodules seem to be still dirty.

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1153/pull-kueue-verify-main/1706281118673670144

**Comment by trasc** [comment]
@PBundyra  it looks like not all the go.sum changes are committed. 
You can run `make test verify test-integration kind-image-build test-e2e `  before pushing to run most of the checks locally.

**Comment by PBundyra** [comment]
> @PBundyra Do you use Go 1.21 in your local? Gomodules seem to be still dirty.
> 
> https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1153/pull-kueue-verify-main/1706281118673670144

Yes, I use ```go version go1.21.1 linux/amd64```. Sorry for that

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/approve

**Pull request merged**
