### PR TITLE
Check resource deletion in tas e2e tests

### LINKED ISSUE #3695: Fleky Test: TopologyAwareScheduling for Pod group when Creating a Pod group
**What happened**:

Periodic Tests failed on "End To End TAS Suite: kindest/node:v1.31.1: [It] TopologyAwareScheduling for Pod group when Creating a Pod group Should place pods based on the ranks-ordering".

```shell
{Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:91 with:
Error matcher expects an error.  Got:
    <nil>: nil failed [FAILED] Timed out after 5.001s.
The function passed to Eventually failed at /home/prow/go/src/kubernetes-sigs/kueue/test/util/util.go:91 with:
Error matcher expects an error.  Got:
    <nil>: nil
In [AfterEach] at: /home/prow/go/src/kubernetes-sigs/kueue/test/e2e/tas/pod_group_test.go:85 @ 12/01/24 16:48:43.849
}
```

**What you expected to happen**:

No errors.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-tas-e2e-main/1863261324973182976

**Anything else we need to know?**:

Screenshot 2024-12-02 at 15 55 06

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mykysha**
#### What type of PR is this?
/kind cleanup
/kind flake

#### What this PR does / why we need it:
Check object deletion in e2e TAS tests

#### Which issue(s) this PR fixes:

Fixes #3695 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mykysha** [comment]
cc @mbobrovskyi

**Comment by mbobrovskyi** [comment]
/test all

2 of 5

**Comment by mimowo** [comment]
/approve
Feel free to unhold when the testing is over. If the issue re-occurs after merge we can still re-open and hopefully we will know more.

**Comment by mbobrovskyi** [comment]
/test all

3 of 5

**Pull request merged**
