### PR TITLE
Replace utils/maps::Clone function with std maps::Clone function after it was introduced in go 1.21

### LINKED ISSUE #1047: Revisit `pkg/util/maps` and `pkg/util/slices` after switching to go 1.21
**What would you like to be cleaned**:
[Go 1.21](https://tip.golang.org/doc/go1.21) some cages that could simplify our `slices` and `maps` like:
  
New slices package
The new [slices](https://tip.golang.org/pkg/slices) package provides many common operations on slices, using generic functions that work with slices of any element type.

New maps package
The new [maps](https://tip.golang.org/pkg/maps/) package provides several common operations on maps, using generic functions that work with maps of any key or element type.

[min and max](https://tip.golang.org/ref/spec#Min_and_max)

**Why is this needed**:

### PR DESCRIPTION
**Pull request by PBundyra**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:
Fixes #1047

#### Special notes for your reviewer:
PR made according to the [discussion](https://github.com/kubernetes-sigs/kueue/pull/1141#discussion_r1332910569) 

#### Does this PR introduce a user-facing change?
```
NONE
```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
/lgtm
/cc @trasc 
/assign @tenzen-y

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
