### PR TITLE
[kjobctl] Update release version on installation guide.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Update release version on installation guide.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Version is automatically updating on `make prepare-release-branch`. 
https://github.com/kubernetes-sigs/kueue/blob/cfbd456e46efcc782342ebc3b652dff8ba959374/Makefile#L279-L283

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Could you update the issue template as well?
https://github.com/kubernetes-sigs/kueue/blob/main/.github/ISSUE_TEMPLATE/NEW_RELEASE.md

**Comment by mbobrovskyi** [comment]
> Could you update the issue template as well? https://github.com/kubernetes-sigs/kueue/blob/main/.github/ISSUE_TEMPLATE/NEW_RELEASE.md

I think it's not necessary because we already have changes here
https://github.com/kubernetes-sigs/kueue/blob/cfbd456e46efcc782342ebc3b652dff8ba959374/Makefile#L279-L283
and we have https://github.com/kubernetes-sigs/kueue/blob/cfbd456e46efcc782342ebc3b652dff8ba959374/.github/ISSUE_TEMPLATE/NEW_RELEASE.md?plain=1#L23-L26

It was not added because this changes was after release commit.

**Review by mwielgus — APPROVED** [review]
/lgtm

**Comment by tenzen-y** [comment]
> > Could you update the issue template as well? https://github.com/kubernetes-sigs/kueue/blob/main/.github/ISSUE_TEMPLATE/NEW_RELEASE.md
> 
> I think it's not necessary because we already have changes here
> 
> https://github.com/kubernetes-sigs/kueue/blob/cfbd456e46efcc782342ebc3b652dff8ba959374/Makefile#L279-L283
> 
> 
> and we have
> https://github.com/kubernetes-sigs/kueue/blob/cfbd456e46efcc782342ebc3b652dff8ba959374/.github/ISSUE_TEMPLATE/NEW_RELEASE.md?plain=1#L23-L26
> 
> This has not been updated since these changes occurred after the release commit.

I meant that could you update this section?
https://github.com/kubernetes-sigs/kueue/blob/cfbd456e46efcc782342ebc3b652dff8ba959374/.github/ISSUE_TEMPLATE/NEW_RELEASE.md?plain=1#L52

Because https://github.com/kubernetes-sigs/kueue/blob/cfbd456e46efcc782342ebc3b652dff8ba959374/.github/ISSUE_TEMPLATE/NEW_RELEASE.md?plain=1#L23-L26 indicates only release branch.

By mentioning this phase in the https://github.com/kubernetes-sigs/kueue/blob/cfbd456e46efcc782342ebc3b652dff8ba959374/.github/ISSUE_TEMPLATE/NEW_RELEASE.md?plain=1#L52, we can include this change in https://github.com/kubernetes-sigs/kueue/pull/2651 after the next release.

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
/approve

**Comment by tenzen-y** [comment]
No need to create manually cherry-picking since there is not cmd/experimental/kjobctl/docs/installation.md directory in the release-0.8 branch.

**Comment by mbobrovskyi** [comment]
You right.

**Pull request merged**
