### PR TITLE
[e2e/multukueue] Retry creating test setup objects

### LINKED ISSUE #1658: Flaky Multikueue E2E tests
**What happened**:

It looks like the Kueue managers start properly, but somehow they crash later.
As a result, we observe:

```
Internal error occurred: failed calling webhook "mclusterqueue.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-clusterqueue?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
```

In `End To End MultiKueue Suite: kindest/node:v1.28.0: [It] MultiKueue when Creating a multikueue admission check Should run a job on worker if admitted`

**What you expected to happen**:

Kueue managers to continue to run properly

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1607/pull-kueue-test-e2e-main-1-28/1750942764473782272

Note that this PR only changes documentation, so the flakiness is definitely on the multikueue code.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by trasc**
#### What type of PR is this?

/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:

Retry the creation of the test setup objects in e2e multikueue suite.

#### Which issue(s) this PR fixes:

Fixes #1658

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Why do these flaky errors occur even though we verify that all webhook servers work fine here: https://github.com/kubernetes-sigs/kueue/blob/8d023ad2ed1eee1cd9e8aebeb05e8fb90d1671e9/test/e2e/multikueue/suite_test.go#L69-L71

**Comment by tenzen-y** [comment]
> > Why do these flaky errors occur even though we verify that all webhook servers work fine here:
> > https://github.com/kubernetes-sigs/kueue/blob/8d023ad2ed1eee1cd9e8aebeb05e8fb90d1671e9/test/e2e/multikueue/suite_test.go#L69-L71
> 
> The "connection refused" it's most likely caused by "too many opened files" or something similar and it's not a permanent error.

Uhm, as Aldo says, it looks like the kueue-manger sometimes crashes...

> It looks like the Kueue managers start properly, but somehow they crash later.
> As a result, we observe:

/test pull-kueue-test-e2e-main-1-27
/test pull-kueue-test-e2e-main-1-28
/test pull-kueue-test-e2e-main-1-29

**Comment by tenzen-y** [comment]
@trasc I'm wondering if these flaky errors would happen in not BeforeEach. It means that these flaky errors will happen in `AfterEach` as well, right?

**Comment by trasc** [comment]
> Uhm, as Aldo says, it looks like the kueue-manger sometimes crashes...

I was not able to find any signs of this in the failed tests logs.

**Comment by trasc** [comment]
> @trasc I'm wondering if these flaky errors would happen in not BeforeEach. It means that these flaky errors will happen in `AfterEach` as well, right?

I theory it could , but currently we don't have any webhooks on delete operation (which are the unusual operations in After), and since  there are no singes of something like that happening  we should not make the code too complicated now.

**Comment by tenzen-y** [comment]
> > @trasc I'm wondering if these flaky errors would happen in not BeforeEach. It means that these flaky errors will happen in `AfterEach` as well, right?
> 
> I theory it could , but currently we don't have any webhooks on delete operation (which are the unusual operations in After), and since there are no singes of something like that happening we should not make the code too complicated now.

Yes, that's right. We don't have any webhooks for deletion, but if the manager crashes, the deletion of cluserQueue would fail since the cqs have an `in-use` finalizer, isn't it?

**Comment by trasc** [comment]
> > > @trasc I'm wondering if these flaky errors would happen in not BeforeEach. It means that these flaky errors will happen in `AfterEach` as well, right?
> > 
> > 
> > I theory it could , but currently we don't have any webhooks on delete operation (which are the unusual operations in After), and since there are no singes of something like that happening we should not make the code too complicated now.
> 
> Yes, that's right. We don't have any webhooks for deletion, but if the manager crashes, the deletion of cluserQueue would fail since the cqs have an `in-use` finalizer, isn't it?

I don't see the connection between this and the current issue.

**Comment by tenzen-y** [comment]
> > > > @trasc I'm wondering if these flaky errors would happen in not BeforeEach. It means that these flaky errors will happen in `AfterEach` as well, right?
> > > 
> > > 
> > > I theory it could , but currently we don't have any webhooks on delete operation (which are the unusual operations in After), and since there are no singes of something like that happening we should not make the code too complicated now.
> > 
> > 
> > Yes, that's right. We don't have any webhooks for deletion, but if the manager crashes, the deletion of cluserQueue would fail since the cqs have an `in-use` finalizer, isn't it?
> 
> I don't see the connection between this and the current issue.

Uhm, you mean this flaky is cause by connection issues, not crashed manager?

**Comment by trasc** [comment]
> > > > > @trasc I'm wondering if these flaky errors would happen in not BeforeEach. It means that these flaky errors will happen in `AfterEach` as well, right?
> > > > 
> > > > 
> > > > I theory it could , but currently we don't have any webhooks on delete operation (which are the unusual operations in After), and since there are no singes of something like that happening we should not make the code too complicated now.
> > > 
> > > 
> > > Yes, that's right. We don't have any webhooks for deletion, but if the manager crashes, the deletion of cluserQueue would fail since the cqs have an `in-use` finalizer, isn't it?
> > 
> > 
> > I don't see the connection between this and the current issue.
> 
> Uhm, you mean this flaky is cause by connection issues, not crashed manager?

Yes, in the [logs of the test in the issue description](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1607/pull-kueue-test-e2e-main-1-28/1750942764473782272/artifacts/run-test-multikueue-e2e-1.28.0/kind-worker1-control-plane/pods/kube-system_kube-apiserver-kind-worker1-control-plane_75a53bb109c743c359b62982987e1fbc/kube-apiserver/0.log)  you can see that the call for the resource flavor webhook fails repeatedly but eventually succeeds.

```
2024-01-26T18:12:42.611098321Z stderr F W0126 18:12:42.610931       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:42.864432468Z stderr F W0126 18:12:42.864260       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:43.117707945Z stderr F W0126 18:12:43.117547       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:43.371146223Z stderr F W0126 18:12:43.370966       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:43.624523129Z stderr F W0126 18:12:43.624368       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:43.877969918Z stderr F W0126 18:12:43.877797       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:44.131319445Z stderr F W0126 18:12:44.131157       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:44.384643142Z stderr F W0126 18:12:44.384483       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:44.55204889Z stderr F E0126 18:12:44.551626       1 available_controller.go:460] v1alpha1.visibility.kueue.x-k8s.io failed with: failing or missing response from https://10.96.34.222:443/apis/visibility.kueue.x-k8s.io/v1alpha1: Get "https://10.96.34.222:443/apis/visibility.kueue.x-k8s.io/v1alpha1": dial tcp 10.96.34.222:443: connect: connection refused
2024-01-26T18:12:44.55206293Z stderr F W0126 18:12:44.551746       1 handler_proxy.go:93] no RequestInfo found in the context
2024-01-26T18:12:44.55206717Z stderr F E0126 18:12:44.551839       1 controller.go:143] Error updating APIService "v1alpha1.visibility.kueue.x-k8s.io" with err: failed to download v1alpha1.visibility.kueue.x-k8s.io: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
2024-01-26T18:12:44.552070331Z stderr F , Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
2024-01-26T18:12:44.553422735Z stderr F I0126 18:12:44.553319       1 handler_discovery.go:337] DiscoveryManager: Failed to download discovery for kueue-system/kueue-visibility-server:443: 503 error trying to reach service: dial tcp 10.96.34.222:443: connect: connection refused
2024-01-26T18:12:44.553441665Z stderr F I0126 18:12:44.553407       1 handler.go:232] Adding GroupVersion visibility.kueue.x-k8s.io v1alpha1 to ResourceManager
2024-01-26T18:12:44.554118002Z stderr F E0126 18:12:44.553958       1 available_controller.go:460] v1alpha1.visibility.kueue.x-k8s.io failed with: failing or missing response from https://10.96.34.222:443/apis/visibility.kueue.x-k8s.io/v1alpha1: Get "https://10.96.34.222:443/apis/visibility.kueue.x-k8s.io/v1alpha1": dial tcp 10.96.34.222:443: connect: connection refused
2024-01-26T18:12:44.637999229Z stderr F W0126 18:12:44.637819       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:44.891415626Z stderr F W0126 18:12:44.891262       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:45.144689532Z stderr F W0126 18:12:45.144532       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:45.398039669Z stderr F W0126 18:12:45.397895       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:45.553077236Z stderr F W0126 18:12:45.552903       1 handler_proxy.go:93] no RequestInfo found in the context
2024-01-26T18:12:45.553101526Z stderr F E0126 18:12:45.552942       1 controller.go:113] loading OpenAPI spec for "v1alpha1.visibility.kueue.x-k8s.io" failed with: Error, could not get list of group versions for APIService
2024-01-26T18:12:45.553105296Z stderr F I0126 18:12:45.552950       1 controller.go:126] OpenAPI AggregationController: action for item v1alpha1.visibility.kueue.x-k8s.io: Rate Limited Requeue.
2024-01-26T18:12:45.553115876Z stderr F W0126 18:12:45.553019       1 handler_proxy.go:93] no RequestInfo found in the context
2024-01-26T18:12:45.553211187Z stderr F E0126 18:12:45.553120       1 controller.go:102] loading OpenAPI spec for "v1alpha1.visibility.kueue.x-k8s.io" failed with: failed to download v1alpha1.visibility.kueue.x-k8s.io: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
2024-01-26T18:12:45.553216747Z stderr F , Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
2024-01-26T18:12:45.55439132Z stderr F I0126 18:12:45.554274       1 controller.go:109] OpenAPI AggregationController: action for item v1alpha1.visibility.kueue.x-k8s.io: Rate Limited Requeue.
2024-01-26T18:12:45.651305696Z stderr F W0126 18:12:45.651112       1 dispatcher.go:221] Failed calling webhook, failing closed mresourceflavor.kb.io: failed calling webhook "mresourceflavor.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-resourceflavor?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:47.832887026Z stderr F W0126 18:12:47.832722       1 dispatcher.go:221] Failed calling webhook, failing closed mclusterqueue.kb.io: failed calling webhook "mclusterqueue.kb.io": failed to call webhook: Post "https://kueue-webhook-service.kueue-system.svc:443/mutate-kueue-x-k8s-io-v1beta1-clusterqueue?timeout=10s": dial tcp 10.96.160.164:443: connect: connection refused
2024-01-26T18:12:49.610209715Z stderr F W0126 18:12:49.610038       1 handler_proxy.go:93] no RequestInfo found in the context
```

**Comment by trasc** [comment]
> But do we understand what is the root cause of the "connection refused" errors? If this was due to load should we not observe the calls hitting timeouts first?

It will depend if the machine runs out of CPU or file descriptors fist. 

The ` "Operation cannot be fulfilled on admissionchecks.kueue.x-k8s.io \"ac1\": the object has been modified; ... ` could be due to the fact that the admission controllers were not covered #1554 and might run in the both manager instances.
(we should look into this, but we should also cover jobframework reconciler and provisioning ACC)

**Comment by mimowo** [comment]
> > But do we understand what is the root cause of the "connection refused" errors? If this was due to load should we not observe the calls hitting timeouts first?
> 
> It will depend if the machine runs out of CPU or file descriptors fist.
> 

Right, if it was running out of CPU I would expect general slowdown, which I don't see here. The request failed in around 200ms.

So, maybe this is indeed something related to file descriptors, but wouldn't we then expect other things also failing, not just this particular request?

Indeed, some time ago I saw errors with "too many files open" (or as such) when creating locally many kind clusters, but for me it was the cluster creation failing consistently, rather than during test.

> However it should not refuse tcp connections based on that.

Right, but maybe as a result of some error handling the root context we keep gets cancelled (just a speculation)?

**Comment by trasc** [comment]
> EDIT: is there a way to confirm the file descriptor hypothesis?

I cannot think of any.

> EDIT2: it seems if the issue is with exceeding the number of file descriptors, why would retry pass? 

Other connections (sockets) are closed. 

> Also, if confirmed, what is the long-term solution, could we bump the limit?

I can't say.

**Comment by mimowo** [comment]
> > EDIT: is there a way to confirm the file descriptor hypothesis?
> 
> I cannot think of any.
> 

Let me try to run the test in a loop locally to see if I can repro this, then maybe we could have more logs to investigate different hypotheses. 

I'm also wondering what could be other logs which could be handy, but we don't archive.

**Comment by mimowo** [comment]
> Let me try to run the test in a loop locally to see if I can repro this, then maybe we could have more logs to investigate different hypotheses.

In the first attempt I created the clusters and only looped ginkgo (with extra `stress --cpu N` command), but after 37 successful attempts I thought it is fair to interrupt, because the rate of failures is like 1/4 probably. This suggests the tests themselves aren't flaky, but maybe there is an issue with cluster startup, or some resources like suggested above.

I will yet loop the entire procedure of creating clusters, test and teardown.

**Comment by mimowo** [comment]
> Try to gradually limit the fd-s before the test `ulimit -n`  and check if you can reproduce it.

I tried using ulimit -n but no success. Even when I set it to very low values, from the repro script, like 1000 the test passes. Tbh I'm not sure why. Maybe the ulimits the file descriptors for the current shell, and it does not count files open within docker.

However, Im able to repro this locally by looping the entire cycle. Cluster creation test and teardown. Now I'm wondering which log levels to increase. And the failure rate is not that low, probably similar to the one on GitHub. 

One hypothesis, I'm not sure if possible, is that the request is rejected by p&f if the BeforeSuite attempts saturated some qps limit.

**Comment by trasc** [comment]
> > Try to gradually limit the fd-s before the test `ulimit -n`  and check if you can reproduce it.
> 
> I tried using ulimit -n but no success. Even when I set it to very low values, from the repro script, like 1000 the test passes. Tbh I'm not sure why. Maybe the ulimits the file descriptors for the current shell, and it does not count files open within docker.
> 
> However, Im able to repro this locally by looping the entire cycle. Cluster creation test and teardown. Now I'm wondering which log levels to increase. And the failure rate is not that low, probably similar to the one on GitHub.
> 
> One hypothesis, I'm not sure if possible, is that the request is rejected by p&f if the BeforeSuite attempts saturated some qps limit.

Any signs of the kueue-controller-manager being killed?

**Comment by mimowo** [comment]
> Any signs of the kueue-controller-manager being killed?

I don't think so, but so far I only got the failure with default logging. Now increased apiserver to v=5 and kueue to v=6, let's see if this tells anything more when caught.

**Comment by mimowo** [comment]
I just got another idea in the meanwhile, in the `KueueReadyForTesting` we only create ResourceFlavor, but this only check that the RF webhook is working, then in ""wait for check active" we always pass RF creation successfully and fail on ClusterQueue creation. Maybe due to the churn the ClusterQueue webhook is not ready yet? I think we could verify this by adding ClusterQueue creation in  `KueueReadyForTesting`. Let me check if this helps.

**Comment by mimowo** [comment]
Looping to try to test this hypothesis. One indication this might be it is that the tests pass consistently after when reusing the ready clusters, as [here](https://github.com/kubernetes-sigs/kueue/pull/1659#issuecomment-1915002555).

**Comment by mimowo** [comment]
> I did thought about this but connection refused is a OSI L4 error and a missing handler should give a L7 error (http: 4xx).

I think the symptomes are quite similar to what was happening when we didn't wait for ResourceFlavour enough. Maybe these errors are somewhere, I could probably look for them with the increased logs, but currently running the loop to confirm if this helps. 

So far I have got 8 successes in a row, which already suggests it helps, because previously I was observing around 1/4 failures.

> In a bot run (I cannot say which one) the error happen on AdmissionCheck creation.

In that case maybe we also need to check creation of this in the KueueReadyForTesting. Actually, if this is confirmed we should probably test every resource.

**Comment by trasc** [comment]
@mimowo  Can you check if #1674 makes a difference in your local setup? We may hit different instances when calling the webhooks.

**Comment by trasc** [comment]
> Could you describe what you mean? Does it refer to your PR?

#1554 increased the number of  kueue contoller-manager replicas , there is a chance that both of them  are accepting webhook requests by more or less luck `KueueReadyForTesting` hits the replica that works but for the CQ we hit the bad one,.   #1674 keeps the controller manager in "Not Ready" until the setup workloads finishes, hence if a replica is not ready it will not be part of the webhook's server endpoint slice.

**Comment by mimowo** [comment]
> #1554 increased the number of kueue contoller-manager replicas , there is a chance that both of them are accepting webhook requests by more or less luck `KueueReadyForTesting` hits the replica that works but for the CQ we hit the bad one,

I'm not sure this is an issue. First, it would be an issue in a singlecluster as well. Second, what I see in my experiments, for a given webhook type and resource there is only one instance that is registered in the API server, and is used consequently. Attaching example successful logs: [replica 1](https://gist.github.com/mimowo/4a9fd94d0132459c5019474b0d75a5fb), and [replica 2](https://gist.github.com/mimowo/1cc34e29a4b5c1a32170d5c22f48e904).

> https://github.com/kubernetes-sigs/kueue/pull/1674 keeps the controller manager in "Not Ready" until the setup workloads finishes, hence if a replica is not ready it will not be part of the webhook's server endpoint slice.

I see, this makes sense, one potential drawback is that Kueue will take longer time to respond as health (potentially >2min). I guess this approach was considered when introducing the TestForKueueReady in the first iteration, but I'm not sure, maybe this is what we want. Let me cc @alculquicondor for insights.

**Comment by alculquicondor** [comment]
> https://github.com/kubernetes-sigs/kueue/pull/1554 increased the number of kueue contoller-manager replicas , there is a chance that both of them are accepting webhook requests by more or less luck KueueReadyForTesting hits the replica that works but for the CQ we hit the bad one,


That's a very good point!

@astefanutti was looking into modifying the probe implementation to take into consideration that the at least the certs are ready. @astefanutti did you make any progress? Maybe that's a better solution.

**Comment by alculquicondor** [comment]
ah ok, you are doing that in #1674

**Comment by mimowo** [comment]
> > #1554 increased the number of kueue contoller-manager replicas , there is a chance that both of them are accepting webhook requests by more or less luck KueueReadyForTesting hits the replica that works but for the CQ we hit the bad one,
> 
> That's a very good point!
> 
This makes sense indeed. I now can confirm with more testing what was happening. With the `KueueReadyForTesting` we only made sure that the subset of webhooks is functional (for tested resources). However, there could be other webhooks managed by the other replica, using another webhook server. The other webhook server could not necessarily be started at the point of testing. It is more or less random which webhook is registered from which replica. So, essentially we would need to create any resource type managed by Kueue to ensure all webhooks are running. I think this is no go.

**Comment by trasc** [comment]
/close
in favor of #1676

**Pull request closed without merging**
