### PR TITLE
Change queueingStrategy default to BestEffortFIFO

### PR DESCRIPTION
**Pull request by ahg-g**

### CODE REVIEW

**Comment by denkensk** [comment]
Here's one more thing to do.
Listed here

https://github.com/kubernetes-sigs/kueue/pull/135#discussion_r840729523_

**Comment by ahg-g** [comment]
@denkensk are you planning on sending a fix?

**Comment by denkensk** [comment]
@ahg-g  I will send the PR tomorrow(It's about 11pm in my city).
When will we cut down the release?

**Comment by ahg-g** [comment]
Tomorrow sounds great! Thanks :)

**Comment by ahg-g** [comment]
> When will we cut down the release?

We don't have deadlines at this moment, but I think we should try and cut one asap so that people who want to try it don't need to clone the repo and build from head.

**Comment by denkensk** [comment]
I couldn't agree with you more. We need to have a version as soon as possible. And then it will roll up like a snowball.
from 0.0.1 --> 0.1.0 --> 0.2.0

**Pull request merged**
