### PR TITLE
[kjobctl] Fix shell-lint errors

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix shell-lint errors on kjobctl.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2779/pull-kueue-verify-main/1820733879254781952

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
Looks like we don't have `privileged` parameter for `pull-kueue-test-kjobctl`. It can take some time to update it. So just now I propose to merge just quick fix to fix verify test on main branch.

**Comment by mimowo** [comment]
/lgtm
/approve 
This PR ran `pull-kueue-verify-main` and it passed so should also fix https://github.com/kubernetes-sigs/kueue/pull/2781

**Pull request merged**
