### PR TITLE
Introduce slices and maps package to workload package

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
I introduced `golang.org/x/exp/slices` and `golang.org/x/exp/maps` to workload pkg.

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by ahg-g** [comment]
/hold

Those packages are experimental, lets wait until they become officially part of golang pkgs.

**Comment by alculquicondor** [comment]
Agree with @ahg-g. Are they part of golang 1.19? We could consider upgrading.

**Comment by tenzen-y** [comment]
> /hold
> 
> Those packages are experimental, lets wait until they become officially part of golang pkgs.

That makes sense.

**Comment by tenzen-y** [comment]
> Agree with @ahg-g. Are they part of golang 1.19? We could consider upgrading.

As I see, these packages are not yet standard packages in Go1.19.

**Comment by alculquicondor** [comment]
/close
we can reopen once they are available (presumably in go1.10?)

**Pull request closed without merging**
