### PR TITLE
Fix a couple typos

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

#### What type of PR is this?
/kind cleanup
/kind documentation

#### Which issue(s) this PR fixes:

Fixes nothing

#### Special notes for your reviewer:
Spring cleaning

### CODE REVIEW

**Comment by alculquicondor** [comment]
you might want to create a new PR

**Comment by ArangoGutierrez** [comment]
> you might want to create a new PR

#102 is on the same situation, going to focus on others things and circle back to this PR's later today

**Comment by ArangoGutierrez** [comment]
Last try
/check-cla

**Pull request closed without merging**
