### PR TITLE
call export logs for kind on e2e tests

### LINKED ISSUE #1452: E2E Tests should export kind logs
Currently, in Kueue, we directly get the logs of the components of a kind cluster. We are missing some logs and Kind provides a better approach for getting logs of the kind control plane (+ kubelet and others that we are missing).

xpost from https://github.com/kubernetes-sigs/jobset/issues/351#issue-2040591348.

In case of Kueue, we could update https://github.com/kubernetes-sigs/kueue/blob/main/hack/e2e-common.sh#L20 to use `kind export logs $ARTIFACTS`.

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Use `kind export logs` to get way more logs from kind.
#### Which issue(s) this PR fixes:

Fixes #1452 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by kannon92** [comment]
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1453/pull-kueue-test-e2e-main-1-26/1735309115082674176/artifacts/

You can see at this link that this feature is working. We have logs for each kind cluster.

/cc @trasc @tenzen-y

**Comment by trasc** [comment]
It might be a bit harder to navigate in the logs, otherwise LGTM.

**Comment by kannon92** [comment]
@alculquicondor and @tenzen-y WDYT of this? If you think it doesn't add much value, we can close it if you want. We found it helpful on the jobset side as we were missing some logs.

**Comment by alculquicondor** [comment]
we don't know when we will need them :)

/lgtm
/approve

**Pull request merged**
