### PR TITLE
Align all kubebuilder markers with leading space

### PR DESCRIPTION
**Pull request by astefanutti**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR aligns the kubebuilder markers to use a leading space comment consistently.

That's useful to get rid of IDE warnings and automated formatting discrepancies.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
This is just a curious. Which formatter does your IDE use?

**Review by mimowo — COMMENTED** [review]
/lgtm
/assign @tenzen-y @alculquicondor

**Comment by astefanutti** [comment]
> This is just a curious. Which formatter does your IDE use?

I use Goland, with the default setting IIRC. I could probably disable the warnings, and automated formatting, but it's probably better to have consistency in the way these markers are formatted.

**Comment by tenzen-y** [comment]
> > This is just a curious. Which formatter does your IDE use?
> 
> I use Goland, with the default setting IIRC. I could probably disable the warnings, and automated formatting, but it's probably better to have consistency in the way these markers are formatted.

Oh, I see. I use Goland, too, although I disable the automated formatting.

/approve

**Pull request merged**
