### PR TITLE
[kjobctl] Ignore kubectl.kubernetes.io/last-applied-configuration on copying annotations from template.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Ignore `kubectl.kubernetes.io/last-applied-configuration` on copying annotations from template in kjobctl.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
After building objects we have unnecessary `kubectl.kubernetes.io/last-applied-configuration` annotation like this:

```
 annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kjobctl.x-k8s.io/v1alpha1","kind":"JobTemplate","metadata":{"annotations":{},"name":"sample-slurm-template","namespace":"default"},"template":{"spec":{"completionMode":"Indexed","completions":3,"parallelism":3,"template":{"spec":{"containers":[{"image":"python:3-slim","name":"sample-container"}],"restartPolicy":"OnFailure"}}}}}
  creationTimestamp: "2024-09-24T14:51:37Z"
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Isn't it dangourous? Once we drop this field, how the client side applyer track the difference?

**Comment by alculquicondor** [comment]
Actually, I think this line is wrong:

https://github.com/kubernetes-sigs/kueue/blob/650c749be70284e77854c685d180703713ff8ef9/cmd/experimental/kjobctl/pkg/builder/job_builder.go#L45

shouldn't it be `b.buildObjectMeta(template.Template.ObjectMeta)`?

**Comment by mbobrovskyi** [comment]
> Actually, I think this line is wrong:
> 
> https://github.com/kubernetes-sigs/kueue/blob/650c749be70284e77854c685d180703713ff8ef9/cmd/experimental/kjobctl/pkg/builder/job_builder.go#L45
> 
> shouldn't it be `b.buildObjectMeta(template.Template.ObjectMeta)`?

Yeah, I think you right. Thanks!

**Comment by mbobrovskyi** [comment]
> Isn't it dangourous? Once we drop this field, how the client side applyer track the difference?

No, because we are generating object and this annotation shouldn't be.

**Comment by tenzen-y** [comment]
> > Isn't it dangourous? Once we drop this field, how the client side applyer track the difference?
> 
> No, because we are generating object and this annotation shouldn't be.

I see. That makes sense. Thanks.

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
Please update the description to match the change.

**Pull request merged**
