### PR TITLE
Step down kerthcet as approvers

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

It's a great journey to incubate Kueue with a small team since early 2022, now, Kueue becomes a critical project in batch/AI training scenes in cloud native world. What impressed me most is the community vitality, more and more contributors join the community and help this project become better, it's amazing. 

However, I don't have time to review PRs anymore, so I would like to step down from my role. But I will not leave, actually, I'd  like to contribute more in the near future, particularly about the vcjob and the inference service. Let's discuss this later.

Last but not least, thanks all for the continuous efforts!

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by PBundyra** [comment]
Thank you for your contributions @kerthcet!

**Comment by mimowo** [comment]
/approve
Thank you @kerthcet for the contributions!

> However, I don't have time to review PRs anymore, so I would like to step down from my role. But I will not leave, actually, I'd like to contribute more in the near future, particularly about the vcjob and the inference service. Let's discuss this later.

Awesome!

**Pull request merged**
