### PR TITLE
Add topology spread constraints to manager deployment

### PR DESCRIPTION
**Pull request by woehrl01**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds option to specify PDB and topological spread constraint in helm chart

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Helm: Support the topologySpreadConstraints and PodDisruptionBudget
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Hi @woehrl01, could you please sign the CLA?

**Review by tenzen-y — COMMENTED** [review]
/release-note-edit
```release-note
Helm: Support the topologySpreadConstraints and PodDisruptionBudget
```

/lgtm
/approve

**Comment by tenzen-y** [comment]
/release-note-edit
```release-note
Helm: Support the topologySpreadConstraints and PodDisruptionBudget
```

**Comment by tenzen-y** [comment]
@alculquicondor Shouldn't we revert this, then should we open this PR against main branch?

**Comment by alculquicondor** [comment]
Oops, I missed that.

We can just cherry-pick to main. WDYT?

**Comment by tenzen-y** [comment]
> Oops, I missed that.
> 
> We can just cherry-pick to main. WDYT?

Yeah, I'm ok with that. Let's offer to bot.

/cherry-pick main

**Pull request merged**
