### PR TITLE
Typo fixes on all docs and on 'AssignmentClusterQueueState' type

### PR DESCRIPTION
**Pull request by ChristianZaccaria**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:

Typo fixes on all `.md` files + on the `AssigmentClusterQueueState` type and made updates in the codebase accordingly.

This is a follow-on PR from https://github.com/kubernetes-sigs/kueue/pull/1744 . Thanks @mimowo for the previous review and suggestion.

### CODE REVIEW

**Comment by alculquicondor** [comment]
Could you extract the fixes inside `/site` to a separate PR so it's easier to cherry-pick?

**Comment by tenzen-y** [comment]
> Could you extract the fixes inside `/site` to a separate PR so it's easier to cherry-pick?

@ChristianZaccaria Could you address this Aldo's comment?

**Comment by ChristianZaccaria** [comment]
> > Could you extract the fixes inside `/site` to a separate PR so it's easier to cherry-pick?
> 
> @ChristianZaccaria Could you address this Aldo's comment?

Good call, will do soon today and post back.

**Comment by tenzen-y** [comment]
@ChristianZaccaria You need to perform with `make update-toc` in your local to fix CI errors.

**Review by mimowo — COMMENTED** [review]
/lgtm

**Review by tenzen-y — COMMENTED** [review]
/approve

**Pull request merged**
