### PR TITLE
fix(helm): wrong secret name in certificate

### PR DESCRIPTION
**Pull request by EladDolev**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Without these changes the integration with cert-manager is not working

#### Does this PR introduce a user-facing change?

```release-note
Helm Chart: Fix a bug that the kueue does not work with the cert-manager.
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
/approve

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Helm Chart: Fix a bug that the kueue does not work with the cert-manager.
```

**Comment by tenzen-y** [comment]
@EladDolev Could you create a cherry-pick PR? [This script](https://github.com/kubernetes-sigs/kueue/blob/main/hack/cherry_pick_pull.sh) would be helpful.

**Comment by EladDolev** [comment]
Hi @tenzen-y and thanks for your help 🙏 
Have opened [this PR](https://github.com/kubernetes-sigs/kueue/pull/2098) using the tool. Hope that's okay

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Helm: Fix a bug that prevented Kueue to work with the cert-manager.
```

**Pull request merged**
