### PR TITLE
Implement genericjob interface on batchv1.Job

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

xref: https://github.com/kubernetes-sigs/kueue/issues/369

### CODE REVIEW

**Comment by mimowo** [comment]
For a heads up, I'm starting the support for the MPIJob: https://github.com/kubernetes-sigs/kueue/pull/578. For now, I'm not using the interface, but continuing by copy-paste. We may abstract these two implementations once the MPIJob is done. Alternatively, if the interface is merged first I will rebase to use it and potentially adapt to the MPI needs.

**Comment by kerthcet** [comment]
> For a heads up, I'm starting the support for the MPIJob: #578. For now, I'm not using the interface, but continuing by copy-paste. We may abstract these two implementations once the MPIJob is done. Alternatively, if the interface is merged first I will rebase to use it and potentially adapt to the MPI needs.
> 
> FYI: @mwielgus @alculquicondor

One thing to mention about is https://github.com/kubernetes-sigs/kueue/pull/537#discussion_r1106823943, I'd like to provide a full controller, then all you need to do is just implement the Job Interface, do you think this can work well?

**Comment by mimowo** [comment]
> One thing to mention about is [#537 (comment)](https://github.com/kubernetes-sigs/kueue/pull/537#discussion_r1106823943), I'd like to provide a full controller, then all you need to do is just implement the Job Interface, do you think this can work well?

I guess it could be helpful if the interface is abstracted well enough. We need to abstract it anyway at some point. 

If the interface is merged first I may need to adapt it a little bit, but it will be helpful, if the MPI integration is merged first, then we may need to adapt the interface. I think we just continue the efforts and see how we synchronize. When I have a working prototype I may also give you some comments to the interface. WDYT @alculquicondor ?

**Comment by alculquicondor** [comment]
+1

**Comment by alculquicondor** [comment]
/close

Superseded by  #616

**Pull request closed without merging**
