### PR TITLE
README.md: Fix some minor typos

### PR DESCRIPTION
**Pull request by dweineha**
Fix some minor typos in README.md.

#### What type of PR is this?

(The description for the kind documentation only mentions new documentation, not bugfixes for the documentation; maybe there's need for a clarification what kind to use for documentation fixes?)

/kind documentation

#### What this PR does / why we need it:

The PR fixes some typos in README.md. Correctly spelled documentation is nice to have.

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

None

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
Thank you!

**Comment by mimowo** [comment]
@dweineha you need to sign the CLA

**Comment by dweineha** [comment]
Signed.

**Comment by mimowo** [comment]
ah, this does not require a cherry-pick as the main README

**Comment by mimowo** [comment]
@dweineha the /kind documentation is perfectly fine for documentation bugfixes. The label description I see is "
Categorizes issue or PR as related to documentation.". Where is this information "The description for the kind documentation only mentions new documentation" coming from? I think we should update in that case.

**Pull request merged**
