### PR TITLE
feat: expose probe

### PR DESCRIPTION
**Pull request by yyzxw**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Expose probe configurations to helm chart
```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/approve
/release-note-none

**Review by tenzen-y — COMMENTED** [review]
/lgtm

**Comment by alculquicondor** [comment]
/release-note-edit
```release-note
Expose probe configurations to helm chart
```

**Comment by alculquicondor** [comment]
Out of curiosity @yyzxw, why did you need to configure these parameters?
Are the default parameters failing for you in production?

**Pull request merged**
