### PR TITLE
Relax the CPU threshhold for the perftest

### LINKED ISSUE #2755: Flaky Test: TestScalability/CommandStats
**What happened**:

Flaky test for `TestScalability/CommandStats`.

```shell
{Failed  === RUN   TestScalability/CommandStats
    checker_test.go:87: Average CPU usage 516mCpu is greater than maximum expected 515mCPU
--- FAIL: TestScalability/CommandStats (0.00s)
}
```

**What you expected to happen**:

It never happened. 

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-scheduling-perf-main/1819194281240301568

Screenshot 2024-08-02 at 15 21 12

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
I relaxed the CPU usage threshold for the perftest for avoiding the flaky test.

#### Which issue(s) this PR fixes:

Fixes #2755

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
/lgtm
I looked at the commits between this failure and the green ones before, and there isn't anything that could indicate there is a regression. Thanks for the update.

**Comment by mimowo** [comment]
/cherry-pick release-0.8
To make the release branch more stable too

**Comment by trasc** [comment]
We need to find a way to publish the stats as metrics and be able to tract the trends, continuing to just bump the threshold for any flake (most likely due to test infra overloading) will just get us to a pint where a real regression cannot be detected.

**Comment by tenzen-y** [comment]
> We need to find a way to publish the stats as metrics and be able to tract the trends, continuing to just bump the threshold for any flake (most likely due to test infra overloading) will just get us to a pint where a real regression cannot be detected.

That makes sense. Additionally, I'm wondering if we should reevaluate average value here: https://github.com/kubernetes-sigs/kueue/blob/facc679eebb7fd02ac0d91321a342d15d8c56885/test/performance/scheduler/default_rangespec.yaml#L1-L6

It seems that the data are a bit out dated.

**Comment by mimowo** [comment]
I think we could help with both things with the script https://github.com/kubernetes-sigs/kueue/issues/2077:
1.  we could use it to quickly collect data from before a given time interval, and see if there is any difference comparing to time intervals.
2. we could quickly collect data to refresh any data

**Comment by mimowo** [comment]
> We need to find a way to publish the stats as metrics and be able to tract the trends, continuing to just bump the threshold for any flake (most likely due to test infra overloading) will just get us to a pint where a real regression cannot be detected.

That is true, however:
1. I checked the commits, and there was nothing that would indicate there is a regression. 
2. overloaded infra happens, we need to take it into account. Otherwise, everyone will suffer failures on branch builds, and this really makes developer experience not good. 
3. I'm really not sure how overloaded infra would contribute to higher CPU usage as indicated in this failed test - I flagged this early on with @alculquicondor that the metric is hard to make sense, during the review, and we suggested to drop this threshold entirely. 

Given the above, I think bumping is justified in this case.

Having said that, I see value in the performance tests, and would support an effort to collect and process historical data quickly.

**Comment by trasc** [comment]
> 1. I checked the commits, and there was nothing that would indicate there is a regression.

For me this is an indication that the performance expectations should not change.

**Comment by trasc** [comment]
In my opinion the script approach is not the best, it will be ideal to be able to push the measurements in some Graphana like dashboard maybe with the option to setup alarms.

**Comment by mimowo** [comment]
> For me this is an indication that the performance expectations should not change.

None of the bumps to the thresholds so far was attributed to a regression. So following this idea would mean accepting continuous failures at the  constant frequency (for correct branches).

After we introduced the first thresholds we had the first flake reported 2 days later (reported as issue, there could have been more), so probably it would mean ~1 random failure every two days. Does not sound good, so I think the decision to bump was justified.

I doubt that if we kept accepting failures at the initial rate then people would diligently study the reason for failures. More likely, people would just keep ignoring, but get annoyed.

**Comment by mimowo** [comment]
> In my opinion the script approach is not the best, it will be ideal to be able to push the measurements in some Graphana like dashboard maybe with the option to setup alarms.

I agree, but it sounds like a lot of work. I would welcome contributors willing to do it, but I don't think we have capacity to do it. 

The idea to have a script that would iterate over builds in a time interval and compute time, average results within the time intervals and compare sounds relatively  simple enough that the contribution is more likely, but still quite involving.

I'm not sure what to do exactly, but accepting failures at constant rate is also not ideal to me.

**Comment by tenzen-y** [comment]
@mimowo @trasc Thank you for some comments. Let's keep discussing the better approach here: https://github.com/kubernetes-sigs/kueue/issues/2775

**Pull request merged**
