### PR TITLE
Update TAS KEP after API discussions

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

To follow up on the discussion in #3237 

#### Which issue(s) this PR fixes:

Part of #2724 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by PBundyra — APPROVED** [review]

**Review by tenzen-y — COMMENTED** [review]
Thank you for reflecting our discussions on KEP!
/lgtm
/approve

**Pull request merged**
