### PR TITLE
Use the capital case in the Cohort preemption reason

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Only the message preempted from Cohort, the Cohort is not defined as a capital case.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
As I can see in the commit history, Aldo defined this `Reason`. So, I would like to leave the final decision of this change to Aldo.

**Comment by alculquicondor** [comment]
Cohort is not an API object, so it shouldn't be capitalized.

**Comment by tenzen-y** [comment]
> Cohort is not an API object, so it shouldn't be capitalized.

That makes sense. Thanks.
Let me close this for now. Once we have Cohort as an API,  we can revisit here.

/close

**Pull request closed without merging**
