### PR TITLE
Automated cherry pick of #2873: Fixed overadmission after deleting resource from

### PR DESCRIPTION
**Pull request by mbobrovskyi**
Cherry pick of #2873 on release-0.8.
#2873: Fixed overadmission after deleting resource from
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
Fix over-admission after deleting resources from borrowing ClusterQueue.
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
@alculquicondor @tenzen-y shouldn't `hack/cherry_pick_pull.sh` add release-note automatically to NONE? Is it bug?

**Comment by tenzen-y** [comment]
> @alculquicondor @tenzen-y shouldn't `hack/cherry_pick_pull.sh` add release-note automatically? Is it bug?

Previously, we investigated the reason why the release note is not propagated to the check pick PR.
But, we could not found any issues.

https://github.com/kubernetes-sigs/kueue/issues/1715

**Comment by tenzen-y** [comment]
/release-note-edit

```release-note
Fix over-admission after deleting resources from borrowing ClusterQueue. 
```

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
