### PR TITLE
Remove unused kueue-viz frontend dependencies

### PR DESCRIPTION
**Pull request by akram**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Removes yet now unused chart.js and react-chartjs-2 as they are still not compatible with react 19 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
/lgtm
Thanks!

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
