### PR TITLE
Rename ResourceFlavor to Flavor

### PR DESCRIPTION
**Pull request by ahg-g**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This is in preparation to introduce the ResourceFlavor CRD type.

#### Which issue(s) this PR fixes:
Part of #https://github.com/kubernetes-sigs/kueue/issues/59

### CODE REVIEW

**Comment by ahg-g** [comment]
> /retest

prow is broken, check the referenced issue above

**Comment by denkensk** [comment]
/lgtm

Thanks @ahg-g

**Review by ArangoGutierrez — COMMENTED** [review]
/lgtm

**Comment by ArangoGutierrez** [comment]
> @ahg-g: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kueue-test-unit-main	[aaa6689](https://github.com/kubernetes-sigs/kueue/commit/aaa6689f86e5e7625d93b89ce508a29206401831)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/123/pull-kueue-test-unit-main/1504408649815035904)	true	`/test pull-kueue-test-unit-main`
> pull-kueue-test-integration-main	[aaa6689](https://github.com/kubernetes-sigs/kueue/commit/aaa6689f86e5e7625d93b89ce508a29206401831)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/123/pull-kueue-test-integration-main/1504408649848590336)	true	`/test pull-kueue-test-integration-main`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=kueue&pr=123). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Aahg-g). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/kueue/issues?q=is:issue+is:open) when you hit one in your PR.

https://github.com/kubernetes-sigs/kueue/pull/124#issuecomment-1070797940 Fixes this errors moving forward

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Comment by alculquicondor** [comment]
straightforward

/hold cancel

**Pull request merged**
