### PR TITLE
[kjobctl] Use busybox init image.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
Use busybox init image in kjobctl slurm mode.

#### What this PR does / why we need it:
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mimowo** [comment]
I heard from @mbobrovskyi offline that there are still some compatibility issues when testing e2e. Please ping reviewers when those are solved

**Comment by mbobrovskyi** [comment]
> I heard from @mbobrovskyi offline that there are still some compatibility issues when testing e2e. Please ping reviewers when those are solved

@mimowo Ready for review

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
thanks!

**Pull request merged**
