### PR TITLE
Update version references to v0.5.0

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind documentation

#### Which issue(s) this PR fixes:

Part of #1256

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/hold
for release to be published

**Review by tenzen-y — COMMENTED** [review]
/lgtm

**Comment by tenzen-y** [comment]
/lgtm cancel

Can we also update this?

https://github.com/kubernetes-sigs/kueue/blob/e94639c9e800b3261a143bb1c622474cbed32b07/site/config.toml#L92-L95

**Comment by alculquicondor** [comment]
Done....
I could swear I had changed it.
Thanks!

**Review by tenzen-y — COMMENTED** [review]
/lgtm

**Pull request merged**
