### PR TITLE
[kjobctl] Fix installation guide.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
As discussed [here](https://github.com/kubernetes-sigs/kueue/issues/2778) we will move `kjobctl` to another repository after MVP phase. Therefore, we can't use the Kueue release binaries and the Kueue release version. To avoid confusion, we should remove the 'Installing from Release Binaries' guide for now.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
/lgtm
/approve
I synced with @mbobrovskyi that currently the docs aren't exposed via https://kueue.sigs.k8s.io/ so I see no need to cherry-pick.

**Comment by mimowo** [comment]
On the other hand it affects `prepare-release-branch` which is part of the release process, so probably better to cherry-pick otherwise it might be confusing when releasing 0.8.2.

**Comment by mimowo** [comment]
Ah, I got confused, it seems the installation guide isn't present on 0.8.1 at all: https://github.com/kubernetes-sigs/kueue/blob/29b6e3564ab2bc04bdedc100bf6c3f74f66e3df7/Makefile#L279. So we are good without cherry-picking.

**Comment by mbobrovskyi** [comment]
Ah, you are right. These changes for v0.9. So, don't need to cherry-pick.

**Pull request merged**
