### PR TITLE
Make error matcher more verbosity.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Make error matcher more verbosity.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
The error matcher doesn't show actual error. This is an example https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3445/pull-kueue-test-multikueue-e2e-main/1853747452654391296.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
@mbobrovskyi By this PR, when the case failed, what is looking for us? We can look the gomega differences?
Could you put the example output?

**Comment by mbobrovskyi** [comment]
> @mbobrovskyi By this PR, when the case failed, what is looking for us? We can look the gomega differences? Could you put the example output?

Yeah, just now we have a message `NotFoundError expects an error`. But it would be great to see what the object come. This is here https://github.com/kubernetes-sigs/kueue/pull/3457/files#diff-27451991a8cdca4f9071dca2e2d47b9ac04338cc3d745ae4107b86dcef81ef7bR70.

Also in many cases we are propagate this error manually. Like this https://github.com/kubernetes-sigs/kueue/pull/3457/files#diff-6973a2a1153d80515ab7d33d5d59be2adf10eb2c4e4d0315e620a5eb542d0fe7L103.

**Comment by mbobrovskyi** [comment]
> https://github.com/kubernetes-sigs/kueue/pull/3457/files#diff-27451991a8cdca4f9071dca2e2d47b9ac04338cc3d745ae4107b86dcef81ef7bR70

Now we have:
```
[FAILED] NotFoundError expects an error
  In [It] at: /Users/mykhailo_bobrovskyi/Projects/epam/kueue/testbin/ginkgo/suite_test.go:37
```

Expects:
```
[FAILED] Error matcher expects an error.  Got:
      <mke2e.SomeObject>: {Foo: "bar"}
  In [It] at: /Users/mykhailo_bobrovskyi/Projects/epam/kueue/testbin/ginkgo/suite_test.go:37
```

Or maybe like this:
```
[FAILED] Error matcher expects NotFoundError.  Got:
      <mke2e.SomeObject>: {Foo: "bar"}
  In [It] at: /Users/mykhailo_bobrovskyi/Projects/epam/kueue/testbin/ginkgo/suite_test.go:39 
```

**Review by tenzen-y — COMMENTED** [review]
Thanks!
/lgtm
/approve

**Pull request merged**
