### PR TITLE
Update Job-integrated features table.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Update Job-integrated features table.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Thx
/lgtm
/approve

**Comment by mimowo** [comment]
/hold cancel
as https://github.com/kubernetes-sigs/kueue/pull/3414 is merged

**Pull request merged**
