### PR TITLE
[kjobctl] Move common SLURM_envs to container env vars.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Move common SLURM_ envs to container env vars on kjobctl.

#### Which issue(s) this PR fixes:

Prepare #3269

#### Special notes for your reviewer:
We have many variables that are the same in each container, so there's no need to generate them in the init container. Instead of that we can set it as a container env vars on builder. 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mwielgus** [comment]
I'm afraid this will make the already big slurm job/pod definition significantly bigger. Is why is it needed?

**Comment by mbobrovskyi** [comment]
> I'm afraid this will make the already big slurm job/pod definition significantly bigger. Is why is it needed?

We discussed on the previous weekly meeting to create init container on go. Before that trying to optimize init script.

**Comment by mbobrovskyi** [comment]
Another approach I also can see to get it from configmap.

**Comment by mwielgus** [comment]
Configmap sounds ok.

**Comment by trasc** [comment]
> In another way we need to create a lot of flags for go slurm-init to send all of this values.
> 
> @mimowo @trasc WDYT?

I don't think that loading the env vars from a `=` separated file is such a big challenge in a go app (split by `\n` then by `=`). So, at least for now, we should not add an extra config map just for this.

**Comment by mbobrovskyi** [comment]
/close

In the case where we are using the current ConfigMap, it will be addressed in https://github.com/kubernetes-sigs/kueue/pull/3293.

**Pull request closed without merging**
