### PR TITLE
Upgrade Go version to 1.23

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Before we release the next minor version (v0.9), upgrading Go version would be better.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
/hold 
for test-infra

**Comment by mbobrovskyi** [comment]
Also we should update https://github.com/kubernetes-sigs/kueue/blob/0d73e6a10a0b71110dd4f8706189d66085f69a58/Dockerfile#L1 and https://github.com/kubernetes-sigs/kueue/blob/0d73e6a10a0b71110dd4f8706189d66085f69a58/cmd/experimental/kjobctl/README.md?plain=1#L12.

**Comment by tenzen-y** [comment]
> Should we update minimal version to 1.23? Maybe it's enough to update to 1.22.7? WDYT?

As I described, before new release, it should be great to upgrade to 1.23.
If we do not update it now, we lose the chance about 4 months since after releasing 0.9, we want to keep using the same Go version for the Kueue patch version.

**Comment by mbobrovskyi** [comment]
> As I described, before new release, it should be great to upgrade to 1.23.
If we do not update it now, we lose the chance about 4 months since after releasing 0.9, we want to keep using the same Go version for the Kueue patch version.

That's a good point. Thanks for the explanation.

**Comment by tenzen-y** [comment]
> Also we should update
> 
> https://github.com/kubernetes-sigs/kueue/blob/0d73e6a10a0b71110dd4f8706189d66085f69a58/Dockerfile#L1
> 
> and
> https://github.com/kubernetes-sigs/kueue/blob/0d73e6a10a0b71110dd4f8706189d66085f69a58/cmd/experimental/kjobctl/README.md?plain=1#L12
> 
> .

Good point. Let me see it.

**Comment by tenzen-y** [comment]
> > Also we should update
> > https://github.com/kubernetes-sigs/kueue/blob/0d73e6a10a0b71110dd4f8706189d66085f69a58/Dockerfile#L1
> > 
> > and
> > https://github.com/kubernetes-sigs/kueue/blob/0d73e6a10a0b71110dd4f8706189d66085f69a58/cmd/experimental/kjobctl/README.md?plain=1#L12
> > 
> > .
> 
> Good point. Let me see it.

Done.

**Comment by mbobrovskyi** [comment]
/lgtm

Thanks!

**Comment by tenzen-y** [comment]
It seems that it takes a little time to synchronize the test-infra repository to the infra cluster.

**Comment by tenzen-y** [comment]
Get ready 🚀 
/hold cancel

**Pull request merged**
